### ISSUE TITLE
Allow injecting arbitrary ASM nodes

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#11]
Currently, Mixin injects the bytecode from a method with the `@Inject` annotation into the target method. While this is usually sufficient, there are some use cases where it isn't:

* Modifying arguments for method calls. In many places, Vanilla uses magic numbers, instead of using a constant with that value. In order to modify the value, the rest of the method (and all necessary `@Shadow`s) needs to be copied in. This could be solved by injecting a `POP` instruction to remove the constant, then pushing the desired value onto the stack.
* Skipping over a conditional, while preserving the rest of the method. This currently requires the same approach of copying in the method, as mentioned above. This could be solved by injecting a `JMP` instruction to the label node after the conditional.

This has several uses in `Sponge`. Many projectile-related classes, such as `EntitySnowball` and `EntityEgg` use a hardcoded value of `0.0` in the call to `attackEntityFrom`. To implement the `Projectile` interface, this value needs to be modified. If the ability to inject arbitrary instructions was added, this could easily be solved by the approach mentioned above.

I propose that the `Target` of the `@Inject` annotation be extended to include `ElementType.FIELD`.

An array of `AbstractInsnNode`s could then be annotation with `@Inject`. Instead of injecting the body of an annotated method, the instructions contained in the array would be injected, following the normal rules for `@At`.

**Comment by Mumfrey** [comment]
Okay, let me start by saying this: *the aim of Mixins is to remove the need for ASM hackery*, that is to say, just like you write a method *once* and use it many times, the aim I've always had with my transformers is to do all the ASM hackery in one place and have other things leverage that hackery. This makes the whole thing more stable and predictable than a dozen different transformers messing around with bytecode in their own way. By the same token, they're not some panacea, they can't cover all cases and it's never expected that *all* problems can be solved with mixins.

Mixins are a hammer, and there's a tendency for that to make all problems look like a nail, but some problems are screws and although we *could* solve them with the hammer, sometimes we need to dig in and go find a screwdriver.

Basically what I'm saying is: before saying *"mixins must have x feature"* we should look hard at the problems and see if we're bending mixins too far out of shape to solve those, and should be solving them another way.

The core tech that mixins are built on comes from two transformers which are part of LiteLoader's core, namely the `ClassOverlayTransformer` (which is Mixin's poor cousin) and `EventInjectionTransformer` (which is the *big* brother of the injection system that's in Mixin) and both of them had considerable development time expended which has lent to the rapid development of the features here in Mixin. The reason I mention this is that it was always my intention to provide a *suite* of transformers in LiteLoader, so that mod authors could pick the most suitable tool for the job and could still be insulated from the complexities of ASM. The same ethos still applies.

To be 100% clear, this framework will *never* make provision for injecting "arbitrary opcodes", because why would you not just write a regular transformer and dispense with the overhead of the mixin transformer at that point? I'm **all for** extending this framework to be more powerful, I'm **strongly against** lazy solutions like getting the implementor to write ASM.

Okay with all of that taken into account, to your points:

> * Modifying arguments for method calls. In many places, Vanilla uses magic numbers, instead of using a constant with that value. In order to modify the value, the rest of the method (and all necessary @Shadows) needs to be copied in. This could be solved by injecting a POP instruction to remove the constant, then pushing the desired value onto the stack.

Provided the constant is topmost on the stack, yes. But even if it's not the logic to do this is pretty straightforward even for reasonably complex invocations. I'm willing to consider writing a kind of injector solely designed to slurp an argument off the stack and modify it. In point of fact a more flexible solution would be the ability to just *proxy the method call* so that a proxy method receives *all* the args and can selectively replace the ones it wants to.

> * Skipping over a conditional, while preserving the rest of the method. This currently requires the same approach of copying in the method, as mentioned above. This could be solved by injecting a JMP instruction to the label node after the conditional.

Yes, and something like is on the cards, the issue is that it has to be easy for the end user to identify the insn actually related to the condition. Java uses conditionals for a lot more than just `if` statements, it uses jumps to implement arbitrary logic including simple things like boolean assignments and actually tracking down the precise opcode which represents a specific `if` can actually sometimes be a pain even if you're familiar with bytecode, next to impossible for a novice, and extremely tricky to do reliably in code. It's usually easiest by hand to look for the first opcode that you know to be *within* the conditional block, but of course how do you codify that?

Yes you can do this with a transformer, and yes I'm actually willing to think about a way of doing this and *have been doing so* since last february when development on event injector framework began. I still don't have a good answer and I'm open to suggestions. **Yes** it's pretty acceptable to look through the bytecode and find the opcode, **no** it just doesn't translate easily to something that can be done in code.

> This has several uses in Sponge. Many projectile-related classes, such as EntitySnowball and EntityEgg use a hardcoded value of 0.0 in the call to attackEntityFrom. To implement the Projectile interface, this value needs to be modified. If the ability to inject arbitrary instructions was added, this could easily be solved by the approach mentioned above.

I'm aware of the applications, which is why this has been a big consideration, it doesn't get around the issue above though.

> I propose that the Target of the @Inject annotation be extended to include ElementType.FIELD.

Um, no. I don't think you understand what `ElementType.FIELD` is. There is no meaningful way that that could make any sense. Fields don't have any code which could be injected into.[<sup>1</sup>](#n1)

> An array of AbstractInsnNodes could then be annotation with @Inject. Instead of injecting the body of an annotated method, the instructions contained in the array would be injected, following the normal rules for @At.

As I said above, no, absolutely no ASM will be exposed to the end user. If you want to do ASM hackery, use a transformer.

As I said at the start of this message, I'm totally behind the idea of expanding the scope of Mixins, and have various ideas already for doing so, although the argument manipulation one is a good one and I'll definitely look at that because it's pretty easy to implement. However I think you need to put some more thought into the rest of your proposal, because the jump-on-if is a tricky one to codify, and the annotated fields just flat out doesn't make any sense.

<a name="n1"><sup>1</sup></a> I did consider rewriting this sentence without ending on a preposition but then I decided that was too much effort.

**Comment by Aaron1011** [comment]
@Mumfrey: I'm interested in working on method proxying/argument maniuplation, unless you've already started.

**Comment by Mumfrey** [comment]
You're a couple of hours too late, was thinking about this today at work and sat down to work on it this evening when I got home.

In a nutshell the most elegant way I could think for single-arg replacements is doing this, method proxy is easy but I like the idea of a single-arg replacement too so I've basically done it so it works like this:

* You write a method which accepts and returns type of the arg, so for an int arg it's `(I)I` basically.
* The injector injects code immediately before the chosen method invokation which
 * Copies every arg *after* the one we want to replace to a local, effectively popping them off the stack, leaving the arg we want on the top of the stack
 * Invoke our injected method, which can modify the value and this obviously leaves the new value on the stack in place of the old
 * Push the remaining args back on the stack
* Then the original invokation goes ahead.

Just poking at allowing multiple hooks per method invokation, because it's actually better than method proxying for simple cases (leaves the original call stack intact, etc), so if it can do that then it'll be quite efficient to use.
