### ISSUE TITLE
Capture locals in Redirect

### ISSUE THREAD

**Issue by kashike** [SpongePowered/Mixin#110]
`@Redirect` currently supports capturing the arguments of the target method. Is it possible to add the option to capture locals as well?

**Comment by Mumfrey** [comment]
I'n not particularly against it, it was mainly omitted for ideological reasons rather than techincal ones; effectively with the aim of keeping redirectors as simple as possible. The spirit of a redirector is proxying a method call, in which all the "context" which should be required is part of the method call already. Essentially redirectors are there in place of a `@ModifyReturn` in that they get an awful lot of power for very little operational overhead. Capturing the target method arguments was provided because it's deterministic, and can be implemented without any performance penalty or complexity.

Unlike callback injectors, redirectors have a very straightforward contract which makes them easy to understand, write, and read.

Basically there's no technical reason why it wouldn't be pretty straightfoward to add; but I would like to see a very good use case presented for it which would justify the potential complexities introduced by it. If possible I'd like to keep local capture restricted to callback injectors, to promote good practice in mixins if nothing else.

Adding local capture to redirectors mainly means that they would have to support all the corner-case handling which callback injectors do, eg. surrogate overloads, `@Coerce` params, lvt truncation, lvt inflection, etc. and would basically blow apart the straightforward nature of redirectors as they exist now.

In a nutshell: if there's a really good use-case for this, then it's entirely possible. However if it's just "I don't want to pair an injector with a redirector", then that's not a compelling enough reason for me to erode the currently quite pure characteristics of redirectors.

**Comment by kashike** [comment]
Thanks for the explanation. In this case, it's to avoid pairing an injector with a redirector.
