### ISSUE TITLE
Documentation needed on when to use MixinEnvironment Compatibility Levels

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#120]
Recently, when a user was asking about what was wrong with his environment, he was using Java 8 etc. but it didn't occur to us helping to ask if the line:
```java
MixinEnvironment.setCompatibilityLevel(JAVA_8);
```
was set in his CoreMod.

It would be helpful I think if the wiki or somewhere else in the documentation (or maybe even use a `PrettyPrinter` for this) to explain why the compatibility level needs to be set or why the Java byte code is incompatible with the compatibility set with Mixins itself.

**Comment by Mumfrey** [comment]
Whilst I would normally agree with you, the `setCompatibilityLevel` thing is only a stop-gap until 0.6 and moves into the config at that point anyway. Since I will have to document all the config changes in any case I won't handle this as a separate issue but rather just roll it up with the documentation changes for 0.6.
