### ISSUE TITLE
How will Mixin be distributed to players?

### ISSUE THREAD

**Issue by RecursiveG** [SpongePowered/Mixin#121]
Since Mixin is a fantastic replacement of Forge's ASMTransformer and can be used by many mods, I wonder in that way mixin will be distrbuted.
I don't think it's a good idea to pack mixin banaries into every mod uses it.
Will it be distributed together with sponge? Or will it be a part of other mod loading frameworks like forge and liteloader?
If I want to use mixin in my mods, which situation I could assume?

**Comment by Aaron1011** [comment]
@RecursiveG: Sponge and liteloader both shade Mixin into their jars. As far as I know, Forge is not planning to move to Mixin, at least in the near future. So, if you're writing a Forge mod, you'll need to shade Mixin to ensure that it's available.

**Comment by Mumfrey** [comment]
As @Aaron1011 pointed out, Mixin is supported as a first-class library liteloader and is also shaded into Sponge.

Whilst in the long term I have no idea what will happen, it's worth noting that in its current form Mixin is designed so that whichever agent is responsible for Mixin's bootstrap, other Mixin consumers will still be able to take advantage of it, and version mismatches can be detected and a sensible error condition raised. This is achieved via several key design features working together:

* The mixin tweaker is designed in such a way that the first agent (container, jar, mod) to load the tweaker will co-operatively enumerate mixins present in all other available containers
* Mixin configs are able to stipulate the minimum version of the library they require, this means that if mod A uses mixin version 0.5 and shades version 0.5, mod B uses 0.4 and shades 0.4. If mod B is loaded first then mod A's mixins can *fail fast* by detecting the insufficient version level, at which point the user has an opportunity to correct the problem
* The general contract for shading Mixin forbids package renaming/relocating in order that all Mixins from all consumers operate in the same space. This ensures that the preceding mechanism of fail fast can occur, and preserves the general behaviour of multiple mixins targetting the same class
* Mixin has an explicit contract to maintain backwards compatibility, and make the **lack** of backward compatibility - where necessary in the future - also *fail fast* (note that no such situation exists currently). This is encoded in the concept of forcibly elevating the required compatibility level such that if in the future it is necessary to break backward compatibility, this situation is again easily detectable. With one notable exception, Mixins written for version 2 of the library will still work with version 5.

For now, the current preference if you plan to use Mixin should be:

* If you make Litemods, simply use Mixin as it's bundled with LiteLoader
* If you make forge mods, shade Mixin without package rename and leverage the co-operative loading behaviour
* If you use Mixin in a forge mod, keep the version of Mixin you distribute as up-to-date as possible since this aids with mod inter-operability

Hope this answers your question.

**Comment by RecursiveG** [comment]
@Aaron1011 @Mumfrey Thank you.
Clear and useful.
