### ISSUE TITLE
java.lang.IllegalAccessError when writing to @Final @Mutable field from mixin subclass (supermixin)

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#124]
When trying to set `@Shadow @Final @Mutable` field from Mixin that is subclass of other Mixin, it crashes with `java.lang.IllegalAccessError` at runtime.

Here is example code that shows the issue:
```java
@Mixin(World.class) public class MixinWorldTest {
	@Shadow @Final @Mutable protected ISaveHandler saveHandler;
}
```

```java
@Mixin(WorldServer.class) public class MixinWorldServerTest extends MixinWorldTest {
	@Inject(method = "init", at = @At(value = "RETURN")) public void init(CallbackInfoReturnable info) {
		ISaveHandler handler = this.saveHandler;
		this.saveHandler = handler; //this fails with IllegalAccessError
	}
}
```

A simple workaround is to crease a setter method:

```java
@Mixin(World.class) public class MixinWorldTest {
	@Shadow @Final @Mutable protected ISaveHandler saveHandler;
	protected void setSaveHandler(ISaveHandler handler) {
		this.saveHandler = handler;
	}
}
```
```java
@Mixin(WorldServer.class) public class MixinWorldServerTest extends MixinWorldTest {
	@Inject(method = "init", at = @At(value = "RETURN")) public void init(CallbackInfoReturnable info) {
		ISaveHandler handler = this.saveHandler;
		this.setSaveHandler(handler); //this doesn't fail
	}
}
```

It fails because access modifiers of the field aren't actually changed. JVM allows writing to the field from the same class, but writing it from other class results in `IllegalAccessError`.

**Comment by Mumfrey** [comment]
Yeah this is because `@Mutable` was really just there to suppress the warning when exploiting that particular JVM loophole, essentially just a way of acknowledging that you're being naughty intentionally rather than by mistake (which is what the whole `@Final` thing is about in the first place).

Whilst in general the idea is that if you want to do what you're doing then you're supposed to use an access transformer, I can see the utility in actually stripping the `final` flag from the field itself if a shadow is marked as `@Mutable` and the field is `protected`, `default` or `public`. This effectively does what an access transformer would do, but within the scope of the mixin and without the latter's need to `setupDecompWorkspace` in order to apply the change.

**Comment by Barteks2x** [comment]
I see why it works the way it works. It's not a major issue and it's easy to workaround it, so if it's a lot of work to fix it - I wouldn't see the point of doing that. 

Doing the same thing as access transformer would be one way to make it work, another way would be to generate synthetic field setter - which is what java compiler does for inner classes that access private field of enclosing class.

**Comment by Mumfrey** [comment]
It'd be a cool feature to have and it's actually easy to do.
