### ISSUE TITLE
Does Mixin handle mixin conflicts?

### ISSUE THREAD

**Issue by LinkTheProgrammer** [SpongePowered/Mixin#126]
I was wondering if Mixin handles conflicts between mixins? For example:

- Two or more Mixins want to modify the same variable
- Two or more Mixins want to modify the same method
- Two or more Mixins want to modify the same class
- Two or more Mixins want to modify the same constructor

And if it does handle these Mixin conflicts, how?

My proposed solutions to these problems are quite simple:

- if two or more mixins want to modify the same variable, dup as `mixinName + "_" + variableName`, then find all references to the variable and rename them.
- if two or more mixins want to modify the same method, dup method as 'mixinName + "_" + methodName', then find all references to the method and rename them likewise.
- if two or more mixins want to modify the same class, dup class as 'mixinClass + "_" + className', then find all references to the class and rename them likewise.
- if two or more mixins want to modify the same constructor, dup specified <init> and modify params as necessary with 'L(some.Identifier) tag', then find all references to constructor and place static final identifier in param location, respectively.

**Comment by Mumfrey** [comment]
This is why priority and `@Final` exist.

> Two or more Mixins want to modify the same variable

If you're talking about `@ModifyVariable`, these are injectors and thus no conflict occurs unless two mixins target the same instruction, in which case the priority semantics take over. If two mixins add the same variable there is no issue. It's not even an issue if two mixins add a field with the same name but different types because this is totally allowed in bytecode.

> Two or more Mixins want to modify the same method

Priority semantics govern `@Overwrite`, injector conflict resolution semantics apply for *redirectors* (`@Redirect`, `@ModifyArg`). For all other injectors multiple injectors are allowed, this is why injectors are recommended.

> Two or more Mixins want to modify the same class

This is built in, specific mixin features are governed by priority but there is as many mixins can target a single class as they want. You can also tune the behaviour of your mixin when other mixins target the same class using a *Config Plugin*.

> Two or more Mixins want to modify the same constructor

Modifying constructors is **prohibited**. The only changes applied to constructors are:

* Field *initialisers* are appended to all ctors, again this respects priority
* `@Inject("RETURN")` injectors are allowed, guess what, this also respects priority

> if two or more mixins want to modify the same variable, dup as mixinName + "_" + variableName, then find all references to the variable and rename them.

No.

> if two or more mixins want to modify the same method, dup method as 'mixinName + "_" + methodName', then find all references to the method and rename them likewise.

This is already governed by the semantics of overwrites, injector callback handlers already get renamed at application time in order to remove the possibility of accidental conflicts.

> if two or more mixins want to modify the same class, dup class as 'mixinClass + "_" + className', then find all references to the class and rename them likewise.

\*clears throat\* um, noooooooooooooooooooooooooooooooooooooooooo
That's literally the dumbest thing I've ever heard. I mean, notwithstanding the fact that it wouldn't work **at all**, if we put aside that tiny nugget for one second then you'll realise that Mixin is designed with ruthless efficiency in mind (note all the restrictions and flat-out prohibitions built into mixin's core) and to this end it **doesn't** do any kind of "wildcard" behaviour which can change the external contract of a class. This is why - for example - contract changes are strictly enforced via Java's `Interface` mechanism.

I mean, not to harp on about this too much, but you said:

> dup class as 'mixinClass + "_" + className', then find all references to the class and rename them likewise.

for the **specific case** that **more than one mixin** wants to modify a class. So how exactly do you "find all references to the class and rename" to **more than one class**. I'm just quite frankly flabbergasted that you would come here, and comment on one of the most patiently-constructed, fastidious and solidly-built bytecode engineering libraries with off-the-wall, half-baked nonsense like this. Stop wasting my time if you can't even be bothered to take the time read and understand my code in the first place, and realise that I have put **much**, **much** more time into designing this project than you can possibly comprehend in your addled mind, and that I might have already... you know... **actually thought this shit through**.

> if two or more mixins want to modify the same constructor, dup specified and modify params as necessary with 'L(some.Identifier) tag', then find all references to constructor and place static final identifier in param location, respectively.

What planet are you from? Please go back there.

**Comment by LinkTheProgrammer** [comment]
>*clears throat* um, noooooooooooooooooooooooooooooooooooooooooo
That's literally the dumbest thing I've ever heard. I mean, notwithstanding the fact that it wouldn't work at all, if we put aside that tiny nugget for one second then you'll realise that Mixin is designed with ruthless efficiency in mind (note all the restrictions and flat-out prohibitions built into mixin's core) and to this end it doesn't do any kind of "wildcard" behaviour which can change the external contract of a class. This is why - for example - contract changes are strictly enforced via Java's Interface mechanism.

>I mean, not to harp on about this too much, but you said:

>dup class as 'mixinClass + "_" + className', then find all references to the class and rename them likewise.

I was going to delete that bit because I realized it could not work.

>for the specific case that more than one mixin wants to modify a class. So how exactly do you "find all references to the class and rename" to more than one class??? I'm just quite frankly flabbergasted that you would come here, and comment on one of the most patiently-constructed, fastidious and solidly-built bytecode engineering libraries with off-the-wall, half-baked nonsense like this. Stop wasting my time if you can't even be bothered to take the time read and understand my code in the first place, and realise that I have put much, much more time into designing this project than you can possibly comprehend in your addled mind, and that I might have already... you know... actually thought this shit through.

    Ok, first of all, sorry I don't look at your code all the time to answer all my questions. As I said, I was going to remove that. 
    Secondly, not all my ideas are absolute, as I am certain not all of your ideas are absolute the first time; I think up ideas on the fly, not always planned except in *special cases*.
    Thirdly, I do not always have the right words for my ideas that would allow me to convey effectively without writing a 500-page book of *why* I had the idea, to *explain* the idea, and *how* the idea works.

>What planet are you from? Please go back there.

I take personal offense to this since I have been ostracized my whole life for being different.

I wouldn't have asked if your wiki actually stated this, or at least if it does, it isn't in the most salient position.

**Comment by modwizcode** [comment]
I would recommend asking questions not through issues but through IRC, this can help prevent confusion that might be clarified quickly in a more responsive conversation.

**Comment by Mumfrey** [comment]
> Secondly, not all my ideas are absolute, as I am certain not all of your ideas are absolute the first time; I think up ideas on the fly, not always planned except in special cases.

It's perfectly fine to have half-baked ideas, just keep them to yourself because you're wasting everyone's time by sharing them. If you want to get involved with something, at least have the common courtesy to spend more than 30 seconds daydreaming up random ideas, eg. do the "due diligence" research. The kind of nonsense posted above just screams of not having the decency to do even that.

> Thirdly, I do not always have the right words for my ideas that would allow me to convey effectively

I wouldn't have had any problems if you had posed this as a question. In fact, refer to my reply above and you'll see that I answered your **questions** succinctly and directly. However the second half of the post was utter nonsense and consequently solicits ridicule. 

> without writing a 500-page book of why I had the idea, to explain the idea, and how the idea works.

It's not unreasonable to expect the bare minimum of effort in communicating though, after all, you made this post expecting me to consider your points and donate my time to responding to you. It's frankly straight up common courtesy to take the time to formulate your argument and at least vaguely articulate your ideas and rationale. You did not do this.

> I take personal offense to this since I have been ostracized my whole life for being different.

And? I've taken my fair share of shit over the years as well, you shrug it off and move on, I don't make it other people's problem. Anyway, I fail to see how it's relevant. Your original post was tacitly offensive in that you chose to arrogantly assume that the issues you raised had *not* been considered and accounted for. Again if you'd stopped at just the question there would be no issues.

> I wouldn't have asked if your wiki actually stated this, or at least if it does, it isn't in the most salient position.

The wiki is designed to be a guide, and I work on it whenever I am able. However it should also be noted that my [javadoc on this project](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/) is **extensive** and explains a lot of the finer detail quite expressively.

Locking this because it's serving no useful purpose.
