### ISSUE TITLE
Mixin using anonymous class fails with Travis

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Mixin#13]
Here is what travis is seeing 
http://pastie.org/pastes/9886632/text

The problematic mixin is MixinBootstrap
https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/MixinBootstrap.java

I don't have this issue in dev nor when building locally.

@Mumfrey let me know if you need any other info. Thanks!

**Comment by Mumfrey** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  adam@eq2.serveftp.net
    Domain eq2.co.uk has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:15095)
	by web3.cov.yesit.co.uk with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-d0b0-adam=eq2.co.uk@sgmail.github.com>)
	id 1YJ4vt-0005tR-Gv
	for adam@eq2.co.uk; Wed, 04 Feb 2015 18:44:13 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=P57wHXD3zcPrWv6Z6fzjJODBr6M=; b=NSDKTYs3EwIa+H3E
	Cx8YrmCdYv89p3kJZ/av0pNNAywUfikRsit2RLrArKhLXED3yC4zzoBrdWcPhrUl
	ezsplyj5BPSNTTS5+2toemPnp0wqFebfV0jjdA7rRkLmEY8aNcLFP0exfI+YOQfo
	Xk56FQQ9Hc9g+RMbKTMRRfjjUig=
Received: by filter0126p1mdw1.sendgrid.net with SMTP id filter0126p1mdw1.25467.54D268772
        2015-02-04 18:44:07.084870145 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-038 (SG) with ESMTP id 14b55e810f8.f47.2c7fb
	for <adam@eq2.co.uk>; Wed, 04 Feb 2015 18:44:07 +0000 (UTC)
Date: Wed, 04 Feb 2015 10:44:06 -0800

**Comment by Zidane** [comment]
@bloodmc 

/home/travis/build/SpongePowered/Sponge/build/sources/java/org/spongepowered/mod/mixin/entity/vehicle/MixinEntityBoat.java:72: warning: Cannot find method mapping for @At(INVOKE.<target>) 'java.lang.Math.sqrt(D)D
    @Inject(method = "onUpdate()V", at = @At(value = "INVOKE", target = "java.lang.Math.sqrt(D)D", ordinal = 0))
    ^
/home/travis/build/SpongePowered/Sponge/build/sources/java/org/spongepowered/mod/mixin/entity/vehicle/MixinEntityBoat.java:77: warning: Cannot find method mapping for @At(INVOKE.<target>) 'java.lang.Math.sqrt(D)D
    @Inject(method = "onUpdate()V", at = @At(value = "INVOKE", target = "java.lang.Math.sqrt(D)D", ordinal = 1))

These two are because remap=false hasn't been set in the @Inject. Only obfuscated classes should be remapped and the jdk isn't obfuscated :p.

**Comment by bloodmc** [comment]
@Zidane Yes I saw that, will fix soon.

So I just ran the build locally to see if it would make a difference and it worked. But with Travis, it fails...

**Comment by Mumfrey** [comment]
I am aware, it seems like an issue which only occurs with travis but I haven't had time to look into it because I've been handling a complicated server migration the last week. I'm back in the real world now so once I've cleared the accumulated backlog I'll have a look.

**Comment by bloodmc** [comment]
After speaking with Lex, he recommended that we should support Class ID's that are generated at reobf time. Here is an example 

``` java
private static final String __OBFID = "CL_00001404";
```

This might help solve our issue when attempting to use strings for anonymous classes.

**Comment by AbrarSyed** [comment]
I wouldnt bother with those too much. grum tweeted that they have stopped ripping out the inner class table.. so those class IDs shouldnt be needed anymore in the next MC release..

**Comment by LexManos** [comment]
They will still be needed as it's not the inner class names that are the issue, it's the id shifting that happens across the recompile boundary.

**Comment by Mumfrey** [comment]
@bloodmc I think there's a potentially better way to deal with this anyway, so I'll likely rip out the problem classes. Basically the mirror API doesn't really support anoymous inner classes so this was an attempt to fill the gap. I think I just need to try a different approach.

Using the class IDs doesn't really help because they're not easily available to me at compile time because I only get a somewhat summarised view of the AST via the mirror API.
