### ISSUE TITLE
Add Decorator Annotation for Methods Expecting NOT to Overwrite

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#130]
There are a few methods that have at times overwritten target methods in development that have caused various issues in the past, and only when we debugged through to find which method it was, we found a new reason to add `@Intrinsic`. The problem however is that when a method *is* being overwritten because of an implementation of an interface, there's no real warning of the accidental overwrite.

While the warnings could be great to track down potential bugs here and there, it would also help if in solving this problem, the methods that do overwrite only in specific circumstances (like for a new method thats added by Forge, and we *know* we are overwriting it, but we can't overwrite it because it doesn't exist in vanilla) are decorated with perhaps `@SoftOverwrite` in the circumstance that while implementing an interfaced mixin to actually still perform the same logic of overwriting the target method.

**Comment by Mumfrey** [comment]
The semantics of `@Overwrite` are not to indicate an overwrite is occurring, because per the general contract of Mixins, overwriting should always be the anticipated action in the situation that a method already exists in the target. `@Overwrite` designates that an overwriting method targets an obfuscated method, and essentially says "handle obfuscation for this method, because its target will be renamed at obf-time".

I actually feel like the original name for this functionality "*overlay*" actually communicates this concept far better. It should always be expected that an undecorated method will overwrite an equivalent target. Having to decorate every method with an annotation to indicate what is already the general contract of Mixin would be a step backwards, because it would indicate a fundamental shift in the way people should be working with the library.

However turning the case around, what you're actually interested in are scenarios where the general contract *should not* apply. In effect, what you're talking about is indicating that a particular method should only ever be *added* and *should not overwrite* a target which already exists.

Being able to define, at the method or mixin level, that the general contract should be suppressed does make sense. This means that you can add a utility method safely and decorate it with an annotation which indicates it should only ever be *added* and never overwrite. Of course, for private it methods it would then be possible have mixin automatically rename the method if a conflict is found, much like the current behaviour for decorating callback handlers.

At the mixin level, this could be used if a mixin is implementing an interface and does not intend to overwrite methods unintentionally, however I would suggest that at this level the annotation only serves to raise a warning if an unexpected method overwite occurrs, rather than actually suppressing the existing behaviour. This is because at the method level an annotation is easy to spot, but having methods which look the same (eg. are undecorated) but behave differently because of a class-level annotation, doesn't seem like a very good idea.

To this end, I would suggest that appropriate remedial action might be to add a new annotation, eg. `@Isolated` or `@Unique` or something which designates a method which must not overwrite a target; and a class-level annotation which indicates that no overwrites are expected in this mixin, and any overwrites should raise a warning-level notification. The method-level annotations could also have an argument which only warns on unexpected overwrite rather than inhibiting it.

The other option would be to simply add a debugging option to verbosely emit information about overwrites which are occurring, simply to aid in tracking down this kind of problem. It would be nice to add some extra expressiveness to mixins themselves in this regard however if it's at all possible, so adding a mechanic isn't all that bad of an idea.

**Comment by gabizou** [comment]
> To this end, I would suggest that appropriate remedial action might be to add a new annotation, eg. @Isolated or @Unique or something which designates a method which must not overwrite a target; and a class-level annotation which indicates that no overwrites are expected in this mixin, and any overwrites should raise a warning-level notification. The method-level annotations could also have an argument which only warns on unexpected overwrite rather than inhibiting it.
> 
> The other option would be to simply add a debugging option to verbosely emit information about overwrites which are occurring, simply to aid in tracking down this kind of problem. It would be nice to add some extra expressiveness to mixins themselves in this regard however if it's at all possible, so adding a mechanic isn't all that bad of an idea.

Both of these would suffice. Ideally, we'd be using `@Unique` as it explains pretty well what the intention of the method is, for both implementing methods from interfaces, and adding helper methods (that are usually either private or protected).


> At the mixin level, this could be used if a mixin is implementing an interface and does not intend to overwrite methods unintentionally, however I would suggest that at this level the annotation only serves to raise a warning if an unexpected method overwite occurrs, rather than actually suppressing the existing behaviour.


I'd prefer as a debugging mode option for throwing an error instead of a warning for debugging modes ;) 


As a side note:
It was this sort of thing that I was eventually going to plan on figuring out how to parse over to add to @DemonWav's MinecraftDevIntelliJ plugin as performing some highlighting or gutter interactions would be interesting.
