### ISSUE TITLE
Wrapper Mixins

### ISSUE THREAD

**Issue by jamierocks** [SpongePowered/Mixin#131]
### Introduction
Before Mixin came along and revolutionised the way modding API's were implemented, wrapper implementation was common, and although mixins are greatly superior in most regards perhaps there is something to be learnt from wrappers: their simplicity (for the most part).

### Example
For example see how much shorter (were you to remove the javadocs) [CanaryMod's implementation of ItemFrame](https://github.com/CanaryModTeam/CanaryMod/blob/master/src/main/java/net/canarymod/api/entity/hanging/CanaryItemFrame.java) is comapred to [NeptuneVanilla's implementation](https://github.com/NeptunePowered/NeptuneVanilla/blob/master/src/main/java/org/neptunepowered/vanilla/mixin/minecraft/entity/item/MixinEntityItemFrame.java).

### The Problem
Mixins are full of `@Shadow public abstract String getName()`, etc. Wrappers have none of this because they have access to the Minecraft representation.

### My Proposal
I propose a new form of mixins are made (Wrapper Mixins), where they would implement an interface (interface as so mixins can still extend other mixins, but it could be a class if needed) from Mixin (WrapperMixin) with the type of the Minecraft representation and have access to that from a #getHandle() method. [Example](https://gist.github.com/jamierocks/0c6ffc73b9722115d1a5ea3e8477191e)

### Closing Notes
I have little to no knowledge using Java bytecode :( so unfortunately I don't know if this is technically possible (I would assume it is). My thought is that when it is mixed into the Minecraft class, #getHandle() is remapped to this. I also don't see this as a replacement for the current way mixins are used, but more an alternative way.

**Comment by Zidane** [comment]
I strongly disagree on wrapping for a number of reasons:

* Wrapping means each object creation essentially becomes two (ignoring the handle being remade, we'll visit that in a sec)
* Wrapping means anyone who decides to use the implementation code must know of the wrapping and handle it accordingly. While Minecraft projects like Bukkit/Canary frown upon this, Sponge does not and we embrace it to a point. We use the telemetry from people using NMS to focus on what needs to be made API.
* Wrapping means inconsistent state. Assuming that wrapper objects act as containers (CraftEntity/CraftPlayer from CraftBukkit are an example), the inner object can be disposed of at any time and ends up causing inconsistent state for the plugin API. It also makes for clunky implementation because the thing called "Player" that CraftBukkit feeds back as CraftPlayer is sometimes...not a player?
* Wrapping means that other modifications to the product now have to know how to unwrap your class. This isn't an issue for Canary but with Sponge we cannot wrap any game objects and pass them off without making damn sure that the wrapped object behaves 100% like the game object (and at that point why did you wrap it to begin with...?).

With the tools at hand and with Mixin's capabilities, I'm of the opinion that you would be nuts to wrap. Wrapper objects have their place but should be used with extreme caution.

**Comment by jamierocks** [comment]
My idea is that there is no wrapper object as such, but still a mixin. A virtual wrapper if you will.

It would give you the simplicity of a wrapper being able to use getHandle() (essentially this) either the power of mixin.

**Comment by Zidane** [comment]
@jamierocks 

That would simply remove the need to shadow public or protected. You would still have to shadow the private ones.

**Comment by jamierocks** [comment]
Come to think of it I suppose #getHandle might be as easy as (MinecraftObject) this to implement...

**Comment by Zidane** [comment]
@jamierocks 

;).

**Comment by jamierocks** [comment]
Yeah - either way it removes the need for some code (which is good in my eyes), but you can always use an AT

**Comment by Mumfrey** [comment]
This is basically already possible, though I would recommend casts.

Your `getHandle` is effectively an inefficient way of doing what is already possible using:
```java
(TargetType)(Object)this
```
which mixin is already smart enough to inline as a direct `this` reference (stripping the redundant casts).

If you're desperate for `getHandle`, simply have all your mixins implement a base interface which is defined thus:

```
public interface IWrapper<T> {
    default T getHandle() {
        return (T)this;
    }
}
```
