### ISSUE TITLE
How should I properly reobfuscate mixins with ForgeGradle 1.2?

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#133]
Yeah, I'm trying to get a final 1.7.10 release out with FG 1.2 before moving to 1.9/1.10/etc.

It seems that method definitions in @Redirect and @Inject annotations aren't being reobfuscated.

Take the following mixin:

https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/src/main/java/com/forgeessentials/core/preloader/mixin/network/MixinNetHandlerPlayServer.java

and reobf it, and you get this http://puu.sh/poNas/acf2910e27.txt . It seems that everything else, except the variables in the @Redirect and @Inject mixins are reobfed properly.

My build.gradle is here: https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/build.gradle and I'm not using MixinGradle because it doesn't seem to work with FG 1.x. So how would I do it?

**Comment by Mumfrey** [comment]
This is correct, the string references in the annotations are not obfuscated inline in the class file because there is no simple way to do this. Instead what happens is that the mixin AP generates what is known as a refmap file, which is a JSON file containing a mapping of method/field references to their SRG and NOTCH counterparts. The name of the generated file needs to be specified in your mixin config, and also supplied to the AP so it knows the name of the file to generate for your sourceSet.

Each sourceSet (in actuality, each compile task) will generate a single refmap, so if you have multiple mixin configs in a sourceSet, then specify the same refmap name for all of them. By convention, the refmap name is generally the config name with **.refmap** appended. Eg. if your mixin config is `mixins.mymod.json` then the refmap name should be (but doesn't have to be) `mixins.mymod.refmap.json`.

MixinGradle was designed to remove all the complexity of passing the resources that the AP needs into the compile task, and then slurping the generated files into the output artefacts (jars) but it's not actually a requirement to use it. All it means is that you have to do all the tasks manually. Since you already have the [basic options](https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/build.gradle#L296-L297) you will only need to supply the others.

The most important argument to supply is the `outRefMapFile` argument, which should be the fully qualified path to output the generated refmap to. MixinGradle defaults to using `compileTask.temporaryDir.refmapName` but you can use anything you like. You then need to simply include this generated file in your artefact using a `from` instruction in the relevant `jar` block.

Specifying a refmap in a mixin config causes it to be used only if present, this means that it's safe to include the directive and it will be ignored at dev-time. At production time it will be used by Mixin to reobfuscate string references on-the-fly. However, it should be noted that any mod depending on your jar will need to explicitly disable the refmap at dev-time, since otherwise Mixin will try to use the refmap even though the environment is actually deobf, this can be done by specifying `mixin.env.disableRefMap=true` as a java system property.

Once you have the refmap included in your artefact, everything should work as expected.

**Comment by luacs1998** [comment]
Alright, seems to work now. Thanks for the pointers!
