### ISSUE TITLE
Shadow Replaced Field Initializers Not Working

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#138]
This feature used to work, not sure when it broke:
![ChunkProviderServer](https://puu.sh/r2H4y/1cde134de6.png)

The field in the debugger is still showing a `Long2ObjectOpenHashMap` which should've been replaced with a `CachedLong2ObjectHashMap` from the mixin being applied.

**Comment by bloodmc** [comment]
I can confirm. I experienced the same issues trying to replace some fields in other classes.

**Comment by Mumfrey** [comment]
I'm not really sure what that screenshot is supposed to show, since it shows a mixin for `ChunkProviderServer` but the decompiled output of `WorldServer`, but I'll take a look into it anyway. I have no idea why it would have broken, unless it's something related to the newest JVM for example.

**Comment by Mumfrey** [comment]
Have you checked the logs to ensure you're not hitting an opcode blacklist?

**Comment by kashike** [comment]
The screenshot shows the debugger at the bottom, showing the `id2ChunkMap` field on `ChunkProviderServer`.

**Comment by Aaron1011** [comment]
I believe I ran into a similar problem before, where Mixin injects field initializers from the Mixin into every constructor. When one constructor calls another, the field initializers can end up overwriting any changing made from an injection at `HEAD`

**Comment by Mumfrey** [comment]
> The screenshot shows the debugger at the bottom, showing the `id2ChunkMap` field on `ChunkProviderServer`.

I can see that, but it's not relevant to the issue title because the issue says "initialisers not injected" and the screenshot doesn't show that. A screenshot showing an instance does not demonstrate that the Mixin was even applied for example.

> I believe I ran into a similar problem before, where Mixin injects field initializers from the Mixin into every constructor. When one constructor calls another, the field initializers can end up overwriting any changing made from an injection at `HEAD`

You cannot inject at `HEAD` into a constructor for this reason. Field initialisers are always appended to the very end of a ctor body.

**Comment by gabizou** [comment]
Found what's going on: the field initializers are being added at the beginning of the constructor instead of the end of the constructor.

![Constructor](https://puu.sh/r3287/c0b3e2b4de.png)

**Comment by Mumfrey** [comment]
Yes and looking at the code I now remember why, that's what's always happened because I had to remove the line-number based injection point detection because it doesn't work in production. We'll have to try and come up with some way of doing this which will work against a production environment, could be very tricky.

**Comment by bloodmc** [comment]
@Mumfrey I tested latest mixin with bleeding and noticed a ton of spam of
```
[mixin]: Could not parse unexpected value "null" for mixin.initialiserInjectionMode, reverting to DEFAULT
```
Can this message be removed?

**Comment by Mumfrey** [comment]
Do you have Mixin from somewhere else also on your classpath by any chance? That's the only thing I can think which would cause that. I'm not at home at the moment but I'll have a look when I'm back.

**Comment by Mumfrey** [comment]
@bloodmc should be fixed now dude.
