### ISSUE TITLE
source linking / line numbers?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Mixin#140]
**Motivation**:

>I managed to set up the .mixin.out classdumps as a provided library on one of the Early Access Builds of IntelliJ after filing a bug with their bug tracker. Once I had done this I was able to use the MixinMerged classes as alternate sources when debugging, this made it much much easier to debug.

This was some months ago, and since then either IntelliJ or my workspace has changed and I'm no longer able to replicate, I believe @gabizou has either seen this or replicated this setup previously.

----
**Backstory**:

@simon816 alerted me to the option "setSourceFile": true which lets you configure the mixins to reference the classnames of the mixins in stack traces.

![image](https://cloud.githubusercontent.com/assets/141554/18507619/422ba2dc-7ab0-11e6-82fd-d326bcae0e28.png)

But this doesn't appear to cause IntelliJ to link back to the Mixin when debugging? 

I was confused about the line numbers shown in the MixinMerged output, as the decompiled classes showed all the MixinMerged methods were being appended to the class?

Simon then enlightened me that the line numbers match the original ``Mixin classes`` source files.

---

**Requests**

I was wondering, are these duplicate / incorrect line numbers possibly confusing the IDE? 

Is it possible/wanted to improve the quality of life of people using mixins by having a debug mode where the line numbers match the debug MixinMerged output?

Is there any additional hinting that Mixin can output to help IDE's debug classes that have been Mixed into correctly?

And do you run into any of these issues using Eclipse, or does it have better/some tooling to deal with this?

**Comment by Mumfrey** [comment]
This is a bit of a long answer so take a seat, I will explain what the options are:

Basically for regular java, compiled class files have two bits of information in them: "source file name" which is part of the header, and the "line number table" which is (optionally) stored with each method and basically stores a mapping of opcode index -> (original) line number.

This is obviously a problem for post-mixed-in classes because they contain code from multiple original source files, but the class file spec doesn't actually support this (well, this isn't 100% true, see below).

So the current choices basically are:

* *leave the `SourceFile` attribute set and leave the line number tables alone*: This basically is what Mixin does by default, it basically means if you see "line 50" in a stack trace, you will need to look at the method name to work out whether it means line 50 in the *original* class or in a Mixin. This approach preserves purity of the line number tables so they are actually guaranteed to mean something.

* *change `SourceFile` attribute to the name of the mixin and leave line numbers alone*: this is at least useful when debugging a mixin because the source file name will be right in the instances that at stack trace involves a mixin method (and wrong for original methods)

As you can see, it's basically an either/or. **Both** of these approaches mean that line numbers are always "correct" for the bit of code they're referring to, but the file name shown in the stack trace is basically gonna be wrong at least half of the time.

*So why do decompiled classes show the methods at the end of the file, with new line numbers?*

Basically because they're decompiled. Decompilation does very little with the source file/line number information since as you can see, it's pretty unreliable. The decompiler concerns itself with converting the compiled information into a java file which represents it. This means that the mixin methods get shiny new line numbers, simply because they get appended to the *generated* (decompiled) java source.

Now there is some good news, though it turns into bad news pretty quickly:

As you are aware, there are other languages which target the JVM and can generate class files. Some of these languages can take multiple source files and generate a single output class! So how are these languages supported, since they must have a way of decorating the target class with information about the *multiple* source files involved?

Enter a part of the JVM spec called "SourceMap" or "SourceDebugExtension". This is a part of the class file spec which allows compilers to emit an intermediate "combined" file and accompany it with a `smap` file, the combined file and smap file are then compiled into the final `.class` file which contains both. The `smap` is stored as a string inside the `SourceMap` attribute of the class file. The key here is that the combined file moves the original line numbers around so that they don't overlap.

So for example, imagine you have file `a.src` and `b.src` which are both 100 lines long. The combined file would have `a.src` in lines 1-100 and `b.src` in lines 101-200. The `smap` file would then map the "combined" line numbers back to the original sources. This means the debugger can look at the SourceMap and determine that the line 221 in `a.b.combined.src` maps back to `b.src` line 21.

So why is this bad news?

Basically I experimented with generating this information 18 months ago and never got the debugger to actually use it. I still have the code on a local branch:

![](http://www.eq2.co.uk/screenshots/2016-09-14_11-36-50.png)

But it never worked. It wouldn't work in eclipse (it was just ignored), and in production the stack trace just seemed to ignore it too. So I gave up with it. I was never able to find any compiled examples of classes which use this attribute to be sure I was doing it right, and to make matters worse the documentation for this feature is pretty awful and assumes you're doing compilation in the two steps mentioned. So I could be missing something, but I have no way to tell.

So what's the good news?

Well, some people (@Aaron1011 is one, I think) have had some success in IDEA with *not* using `mixin.debug.export` decompiled classes, but using the export feature and then having IDEA do the decompilation itself. I'm not sure since I don't use IDEA, but you could ask in IRC to see if you get any help.

Suffice it to say I've explored the options available *in some depth* and really just drawn a blank in terms of actual useful functionality I can add. To address your questions directly:

> I was wondering, are these duplicate / incorrect line numbers possibly confusing the IDE?

Probably, but as you can see, the only other options are to renumber the mixin methods arbitrarily, which doesn't help either.

> Is it possible/wanted to improve the quality of life of people using mixins by having a debug mode where the line numbers match the debug MixinMerged output?

This is one of those "feasible, but really wouldn't pay much out based on the effort required" things. Short answer is "no", long answer is that it would require decompiling and then recompiling the post mixin class, and **even after doing that** the line numbers would still be wrong, although closer.

> Is there any additional hinting that Mixin can output to help IDE's debug classes that have been Mixed into correctly?

Yes but it doesn't work, see above.

> And do you run into any of these issues using Eclipse, or does it have better/some tooling to deal with this?

Eclipse deals with debugging differently, but unfortunately experiences the same issues. Eclipse is more tightly coupled to its compiler than IDEA (in eclipse, the work done by the compiler and the work done for what IntelliJ calls "indexing" are basically done by JDT) and so it ignores runtime modifications to the class because it believes that it knows the class (it doesn't).

> This was some months ago, and since then either IntelliJ or my workspace has changed and I'm no longer able to replicate, I believe @gabizou has either seen this or replicated this setup previously.

You are still better of pursuing this route, since as I have explained, there isn't really any alternative.

**Comment by ryantheleach** [comment]
Firstly, I greatly appreciate the long response, thankyou for taking the time.

>But it never worked. It wouldn't work in eclipse (it was just ignored), and in production the stack trace just seemed to ignore it too. 

Whilst I was researching the issue, I found reference that IDEA at some stage had a option for it's debugger to either compare bytecode or line numbers when debugging. I guess that comparing bytecode proved to be a reliable feature as I can not find the setting in the 2016 editions of IDEA

**Comment by Mumfrey** [comment]
If you are satisfied with your answer please say the words "I am satisfied with my care"

**Comment by ryantheleach** [comment]
[I am satisfied with my care](https://youtu.be/FmaJPV1okPo?t=2m14s)

**Comment by gabizou** [comment]
I've been able to use the export feature and associate the generated `.mixin.out/class` folder as a "Dependency" (with `provided` resolution) and IntelliJ will be able to associate it during debug time. It just gets a little funky since line numbers don't always match up.

**Comment by ryantheleach** [comment]
Maybe it was because I was using .mixin.out instead of .mixin.out/class

**Comment by gabizou** [comment]
> Further, instead of adding it as a dependency, what also works is under the libraries tab, creating a new library, then it's also possible to attach sources(when they exist, fernflower seems to throw exceptions occasionally preventing the sources from generating).

Yeah, adding it as a library works, it's just managed in the module's dependency tab. Note that making it provided doesn't require it to compile (if you have sources), nor does it use it at runtime.

**Comment by Mumfrey** [comment]
Pinging possible solution in #156, though it will require a plugin in intellij and possibly later in eclipse.

**Comment by ryantheleach** [comment]
Thanks, I've been a little distant lately, the ping was appreciated.
