### ISSUE TITLE
Allow @Redirect on Mixins with multiple targets

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#142]
I have this Mixin:

```java
@Mixin(value = {EntityPlayer.class, CommandBlockBaseLogic.class}, targets = IMixinCommandSender.EXECUTE_COMMAND_SENDER)
public abstract class MixinCommandSendCommandFeedback implements ICommandSender {

    @Redirect(method = "sendCommandFeedback", at = @At(value = "INVOKE",
            target = "Lnet/minecraft/world/WorldServer;getGameRules()Lnet/minecraft/world/GameRules;"))
    private GameRules onGetGameRules(WorldServer overworld) {
        // Check the game rules of the current world instead of overworld game rules
        return getEntityWorld().getGameRules();
    }

}
```

Basically, it hooks in very similar implementations of `sendCommandFeedback` in all 3 target classes. In development environment it applies without errors on all target classes. However, when compiling the project with Gradle the annotation processor complains:

```
error: Mixin with @Redirect members must have exactly one target.
```

In this case, since `sendCommandFeedback` is a method of the `ICommandSender` interface, the obfuscated name should be always the same, so it should be possible to have the annotation processor find the correct mapping.

Is there a special reason why this is not allowed? It would be nice if this could be written in one Mixin instead of having to create 3 identical Mixins.

**Comment by Mumfrey** [comment]
The main reason it's not allowed is for sanity. In this case because all of the methods inherit from a common interface they will have the same name, however this is not a cast iron guarantee. The single-target check was originally meant for shadows but the same logic was applied to injectors as well because they suffer the same potential problem.

Whilst it complicates the AP logic, it's not impossible to do what you want so I will at least look into it, I'm doing some refactoring on the AP at the moment so I will assess it for feasibility.

**Comment by Zidane** [comment]
@Mumfrey 

This is stalling https://github.com/SpongePowered/SpongeCommon/pull/498 from being merged (at least, without requiring additional mixins solely to work around this limitation).

I need a status on this.

**Comment by Mumfrey** [comment]
> I need a status on this.

I mentioned in IRC on saturday that this is effectively accepted but needs some serious overhaul in the AP. Once I've fixed #143 I will do it next but it's several days worth of work.

**Comment by Mumfrey** [comment]
Having looked at it a bit more, the refactoring I've already done makes this much simpler to do, so shouldn't be too tricky to tackle, at least in a basic manner.

**Comment by Minecrell** [comment]
It seems like it doesn't work in my case because one of the targets is an anonymous class:

```
@Redirect target requires method signature because enclosing type information for net.minecraft.command.CommandExecuteAt$1 is unavailable
```

It works fine if I remove the anonymous class from the Mixin targets.

**Comment by Minecrell** [comment]
Ignore what I said above, I just had to actually read the warning and add the full method signature. I basically only read `net.minecraft.command.CommandExecuteAt$1` and thought it isn't possible to use a `@Redirect` on multiple targets if one of them is an anonymous class.

**Comment by Mumfrey** [comment]
It's because Mirror won't let you access anonymous classes, so those injectors always required a signature. All I've done is promote that message from `WARNING` to `ERROR` if it's a multi-target mixin, because otherwise the fact that the other mappings succeed could hide the fact that the anonymous one is failing. By forcing it to be qualified, it can be properly grouped with the equivalent member from the normal targets.
