### ISSUE TITLE
No way to tell MixinConfig to load *both* client- and server-specific mixins

### ISSUE THREAD

**Issue by asiekierka** [SpongePowered/Mixin#144]
This would be useful for applying mixins into a "merged" Minecraft JAR file outside of runtime. I propose a dev property, perhaps "mixin.applyAllSidedMixins"? The necessary patch has to be done in MixinConfig.prepare.

EDIT: Apparently I don't strictly need this feature, so use your best judgement as to whether or not it should make it in.

**Comment by Mumfrey** [comment]
In general, this is what config companion plugins are for. Essentially in Mixin there are 3 mixin sets:

* Client
* Server
* Both

Of course if you want to put all mixins in the *Both* set and then decide whether to apply them based on side, you can do this with your companion plugin instead of letting Mixin itself decide.

Essentially, since Mixin can't know in advance about every possible scenario, config companion plugins are granted a lot of power with respect to application of mixins so that any gaps in functionality can be easily plugged using them.

I could potentially accomodate this by providing a `MERGED` "side" as well, so that platforms can report this side when they want to apply mixins from all 3 sets (normally only 2 will be chosen of course), though I don't really know that this actually provides any additional functionality over what I've described.

**Comment by asiekierka** [comment]
I see. If there's a way to do it already, the issue can be closed.
