### ISSUE TITLE
Changes to allow applying mixins in multiple runs

### ISSUE THREAD

**Issue by asiekierka** [SpongePowered/Mixin#145]
The case I have ran into requires us to "pre-bake" certain mixins into the JAR for easier accessibility by a potential developer. However, other mixins may still be applied at runtime. ~~This requires the Mixin API to be able to store the necessary state values in the class and/or have them be handled, possibly by the use of annotations - for instance, the counters for unique method/field names (which could be handled by either storing them in @Mixin... annotations, or by incrementing the counter until a "free" method/field name is found).~~ The best route is probably to make the Mixin API stateless across different executions and more graceful - to solve the counters for unique method/field names problem, you could try incrementing the counter until a "free" method/field name is found.

Note 1: The Session ID might need a redesign - right now, we have to work around it by ensuring it stays the same on both executions ourselves. However, it could be used to notify the mixin applier that a method belongs from a different mixin API instance, and have it simply find a different free method slot instead of erroring in that case.

https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/TargetClassContext.java#L82 is an example of two such stateful values. I'm not sure how many there actually are.

If this is too much to ask of the Mixin API, let me know as well and I'll try to find a different solution.

I'd love to discuss this more on TeamSpeak/IRC, but I couldn't reach you on the latter (I tried IRC first because I know my explanation of this here is poor).

**Comment by Mumfrey** [comment]
I see. It seems like you're trying to use Mixin in a way that it's not intended to function and I'm wondering why though?

The "state" as you have identified it, is intentionally created and preserved in order to facilitate efficiency, there are many aspects of the design which are intrinsically stateful (intentionally so) and the ones you have identified are really the trivial easy-to-spot aspects and not the more fundamental ones.

For example, session ID can be turned off with no ill effects, the point of session ID is actually to prevent someone using the annotation as a "defense" in an existing class against a mixin replacing a method (because `@Final` achieves this and misappropriating internals is a bad idea). Mixin would work fine without it though, it's a protection mechanism only. As you say, it would be trivial to change the decorator to work out ids rather than using sequential ones, but that misses the point of then being sequential - eg. they don't **need** to be computed.

Mixin operates by precomputing a lot of the information it requires about the target classes, their structure, and all of the other mixins which are going to be applied in the current environment, and then operating with those known precomputed parameters in order to avoid lots of unnecessary iteration, re-iteration or potentially cyclical classloading. Compute once, use many times. When mixins are loaded they are preprocesed and conformed, this is done in a single pass for each "environment" so that at each phase of classloading, the metadata stored by Mixin does not need to be recomputed.

My point is, the trivial things can be addressed easily, but you're ignoring the more fundamental aspects of Mixin which aren't designed to work this way. It seems like the easiest solution if you want to attempt this is to keep the two passes **entirely** separate and just "undecorate" the Mixins after the fact, or maybe I could make a debug switch to disable the decoration for "pre-processing" passes. Without knowing **why** you want to do this, I can't really understand what you're trying to do.

**Comment by asiekierka** [comment]
I'll open a new, clearer issue with Mumfrey. Wait for that.

**Comment by asiekierka** [comment]
No need for an issue, but I found something that looks like a bug:

As we discussed, I apply a mixin "A" in offline mode and a mixin "B" in online mode and "desprinkle" it. They both target the same function. However, the Mixin API does not seem to check if the unique method name for the injection is actually present:

        this.handler$init$zza000(new CallbackInfo("test2", false));
        this.handler$init$zza000(new CallbackInfo("init", false));
        this.handler$init$zza000(new CallbackInfo("init", false));

**Comment by Mumfrey** [comment]
As I said, solving this is as simple as just using an *ever so slightly different* conform mapping during offline application, even as simple as just appending a single extra character in offline mode. I had already accounted for this in terms of what will be needed to achieve "offline mode".
