### ISSUE TITLE
MixinEnvironment cannot determine the side when using a custom ITweaker 

### ISSUE THREAD

**Issue by modmuss50** [SpongePowered/Mixin#146]
There doesn't appear to be a way to specify the side when using a custom tweaker. 

After a bit of poking around I found that it appears to be hard coded to work with Forge and LiteLoader.

https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/MixinEnvironment.java#L196

I came across this as I noticed my mixins were not being applied and I was given this error: 

`Mixin environment was unable to detect the current side, sided mixins will not be applied`

I might be wrong with this so I look forward to your input. 

Thanks.

**Comment by Mumfrey** [comment]
I assume you're talking about SpongeVanilla? That message can be safely ignored because all it's telling you is that Mixin itself couldn't automatically detect the side. Sponge vanilla [just calls `setSide`](https://github.com/SpongePowered/SpongeVanilla/blob/da038acaea204be3e78e5526f61c182a5381ab57/src/main/java/org/spongepowered/server/launch/VanillaServerTweaker.java#L144) in order to set the side and so the side is still set correctly, just not detected automatically.

**Comment by modmuss50** [comment]
I am using it in fabric, but if its safe to ignore it thats fine. Looks like I missed setSide so that should fix the issue.

Sorry about that

**Comment by Mumfrey** [comment]
There are 3 mixin subsets defined in a mixin set (aka configuration). "Common", "Server" and "Client". The common mixins are always applied regardless of side, the server and client ones are only applied if the side is set (or detected) in the environment. So basically, if there are no sided mixins (or if sidedness is - for example - being determined by the mixin config's companion plugins) then it doesn't really matter. If you do have sided mixins then you need to set the appropriate side in the tweaker if the side cannot be automatically detected.

**Comment by modmuss50** [comment]
Yeah, once I set the side, the errors went away and the mixins started working. 

Thanks for the clearing that up with me.
