### ISSUE TITLE
Capture the target method's arguments in @ModifyArg

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#162]
I want to fix https://github.com/SpongePowered/SpongeCommon/issues/1129 using a Mixin.

I've created a `@ModifyArg` for the constructor to replace the second argument of the `super.<init>` call:

```java
@ModifyArg(method = "<init>(Lcom/mojang/authlib/GameProfile;Ljava/util/Date;Ljava/lang/String;Ljava/util/Date;Ljava/lang/String;)V",
        at = @At(value = "INVOKE", target = "Lnet/minecraft/server/management/UserListEntryBan;"
                + "<init>(Ljava/lang/Object;Ljava/util/Date;Ljava/lang/String;Ljava/util/Date;Ljava/lang/String;)V"), index = 1)
private static Date fixStartDate(Date endDate) {
    return endDate;
}
```

It applies correctly, however to fix this problem I'd need to access the method arguments of the enclosing target method. While `@Inject` and `@Redirect` support capturing these, I couldn't find any information if the same is possible using `@ModifyArg`.

Is there any way I can access the `startDate` of the constructor from the `@ModifyArg`?

**Comment by Mumfrey** [comment]
Yeah I think when I wrote `@ModifyArg` I didn't include this because the idea was that it's a very simple injector with a specific purpose. I could look at adding that feature though, not sure if it has any knock-on effects I'd have to check.

You could potentially access and store the value using `@ModifyVariable` or a second `@ModifyArg` beforehand, given the situation. At least as a temporary work-around.

**Comment by Mumfrey** [comment]
Okay I looked into this and really I don't want to change the behaviour of `@ModifyArg` because it already has an overloaded behaviour where it can capture all arguments being passed into the hooked method and adding an second overloaded behaviour to capture the target method args is just going to take it too far off-piste.

The idea with `@ModifyArg` was always that it would be a super-simple injection and anything more complicated would be handled by `@Redirect`.

For obvious reasons it's not currently possible to `@Redirect` a constructor call, and most of the ways I can think of modifying `@Redirect` come with an uncomfortable number of caveats. The only sensible way I can think of allowing `@Redirect` to modify a superconstructor call would be as follows:

* Insist that the handler is `static` - this prevents access to potentially uninitialised instance variables (including `this`)
* either provide some way of "shadowing" the constructor so that it can be called from within the static handler, or have the handler call *itself* (much like a intrinsic proxy would) and transform the call into a call to the `super` (not sure if this is even legal in the JVM, though I don't see why it wouldn't be.)

The alternative would be some kind of alternative to `@ModifyArg` (`@ModifyArgs`?) which can modify multiple variables and capture target method args, basically some kind of half-way house between the current `@ModifyArg` and a fully-fledged `@Redirect`.

I should also flesh out the documentation for `@ModifyArg` because it doesn't currently explain the mechanics of it very well (or at all) and that's part of the problem. `@ModifyArg` really deserves some examples like the other injectors have.
