### ISSUE TITLE
Replacing comparison with zero

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#165]
`@ModifyConstant` allows to replace a constant with something else. Originally the reason I needed is was that it would make replacing vanilla height checks easier. But JVM has special instructions for comparisons with zero, so `@ModifyConstant` turned out to be mostly useless in most cases where I wanted to use it. Instead I have to resort to a hack - redirecting `BlockPos#getY()` to workaround height checks.

It turns out there are some cases where even that is impossible - for example `Chunk.getBlockState(final int x, final int y, final int z)`, there is no BlockPos where I can redirect a method. And the Y coordinate is used one line later (and this was even the exampke I gave for array redirect, and didn't notice the height check)

Would it be possible to do that? Or is it already possible in some way I don't know about?

**Comment by Mumfrey** [comment]
So you basically mean where the:

```java
if (y >= 0 ...
```

is becoming

```java
ILOAD 2  # y
IFLT     # if < 0 jump over block
```

you want to have it effectively first expanded to:

```java
ILOAD 2   # y
ICONST_0  # load explicit zero
IF_ICMPLT # if y < 0 jump over block
```

which then lets you target the ICONST_0 with `@ModifyConstant` ?

**Comment by Barteks2x** [comment]
Yes, that's basically what I want. Or anything that allows me to do equivalent things.

**Comment by Mumfrey** [comment]
It's really not hard to expand the "implicit" opcodes (`IFLT`, `IFEQ`, etc.) out to their explicit counterparts with a zero, the problem is finding ones where the value is actually an integer.

As you may know, all types smaller than `int` (`short`, `byte` and `boolean`) are all stored internally as integers, and the same opcodes are used to manipulate them. So the tricky part if this expansion is allowed would be making sure you're not looking for an `int` but accidentally hook on a `boolean` comparison. My point being it's 100% possible but introduces another spot where it's up to the mixin author to ensure they hit the correct opcode.

I think the only way this is going to be realistic is if this behaviour is only enabled explicitly, eg. by forcing the mixin author to decorate their `@ModifyConstant` with `conditionals=true` or something, so that it knows to match and expand those opcodes in those circumstances. Of course this all only needs to happen when `intValue=0` so it's not like there should be  too much collateral damage either way.

**Comment by Barteks2x** [comment]
I didn't think about booleans, thinking only about ifgt/iflt which aren't used for booleans. And distibguishing between bytes, shorts and ints on the JVM seems like a flawed idea anyway. I've never encountered a direct `variable == 0` comparison I needed to modify, but I see how it could be needed sometimes.

**Comment by Mumfrey** [comment]
Oh yeah for sure, but I was just pointing out the possible pitfalls, as I always consider them before adding a feature to Mixin because the intention is always that Mixin will prioritise stability over features. If a feature introduces possible instability then either:

* The feature is not added
* The feature is added but I put as much reasonable detection in place to hard crash if things are not as expected

The potential here is for the ClassLoader's validator to crash when loading the class if accidentally hooking on a boolean. I think it's unlikely but it's possible.

Adding the feature to only transform `IFLT`, `IFGT`, `IFLE`, `IFGE` would be safest, because as you say those operators don't get used for boolean comparison, but then this would need to be clearly documented because it's inconsistent from a user's point of view, because they may expect that it's possible to hook onto `variable == 0` (`IFEQ`) and also `variable != 0` (`IFNE`) when in fact it won't be. So there's trade-offs.

**Comment by Barteks2x** [comment]
For documenting the inconsistent behavior - naming it something like `inequalityConditionals` would make more sense.

**Comment by Mumfrey** [comment]
Yeah or even provide a option which lets you specify which operator to match and then expand it internally (which I like more than exposing more bytecode-level stuff) for example

```java
expandConditions = ">"
```

which would then expand `IFLE` and `IFGT`.

I need to have a think about the best way to present this. It's definitely not off the table, but I want to expose it in a way which is consistent and at least reasonably easy to understand.

**Comment by Barteks2x** [comment]
I like that idea, may be better to do something more like `">0"` to indicate on which side the zero is, and that it's only the special case of 0.

**Comment by Mumfrey** [comment]
Yeah that's a good call actually.
