### ISSUE TITLE
Force injection of FML coremods/mods does not work on MC 1.7.10 and below

### ISSUE THREAD

**Issue by luacs1998** [SpongePowered/Mixin#17]
MixinTweaker only supports the post-MC 1.8 FML CoreModManager (net.minecraftforge.fml namespace), whereas other parts of the mixin codebase support the cpw.mods.fml namespace used by FML before MC 1.8.

This "bug" has prevented me from being able to test FE, which employs mixins in a 1.7.10 environment, within a production workspace.

Will this be fixed?

**Comment by Mumfrey** [comment]
That should fix it, let me know if it doesn't.

**Comment by luacs1998** [comment]
It doesn't. Here's a build of FE including mixins and this bug: http://1drv.ms/1EHWnl6

**Comment by Mumfrey** [comment]
What I don't quite understand is how this is working for @Zidane (who is also using it in 1.7.10) and not for you. The logic for the tweaker goes like this:

* Mixins **must** be loaded by a tweaker in production to end up in the correct classloader
* If FML parses a file and it has a tweaker, it does **no** further processing of that file and doesn't look for coremods or anything, this means the tweaker has to
* First, try to forcibly load a coremod specified in the manifest, this process should return a wrapper which is itself an `ITweaker` and is a handle to the coremod instance
* If this fails and the user specifies the `ForceLoadAsMod` key in the manifest, the tweaker attempts to remove its container from the loaded list in order to give FML a shot at loading the coremod normally on a second pass.

However, **all of this is based on 1.8 behaviour** because Mixins is a 1.8 project and that's all I care about, 1.7.10 compatibility is added as a courtesy but I cannot really devote the time to troubleshooting 1.7.10 issues.

Things I know:
* The current approach works fine in 1.8
* The current approach is working fine for @Zidane in 1.7.10
* It's entirely possible that some or all of the above assumptions that the tweaker makes are not valid for all historic 1.7.10 releases (they **must** be true for at least one release because it's working in at least one case)

This means you should:
* First, I suggest, chat to @Zidane on IRC and see if your approaches differ, and find out if he's doing something you're not
* Second, compare notes on which FML version you're both using. If you're using an outdated version of FML that may be the issue, or it could be some other combination of circumstances the current tweaker has not accounted for

This is the limit of support I'm prepared to provide for 1.7.10 though, developing for outdated versions of minecraft is something we should all collectively discourage because all it does is pour more fuel on the fire of modders not bothering to update their stuff because "everyone's still on x version".

**Comment by luacs1998** [comment]
Alright, thanks for the help anyway.

**Comment by Zidane** [comment]
@luacs1998 

https://github.com/AlmuraDev/AlmuraSDK

Take a look at how I use Mixins here. I can absolutely confirm that this does work for 1.7.10.

**Comment by Mumfrey** [comment]
> Alright, thanks for the help anyway.

Don't get me wrong, if you come back and say "you need to make *x, y, z* change and then this'll work in 1.7.10" then I'll add that no problem, but the focus of development has to be 1.8 and I can't really devote the time for troubleshooting on an outdated platform.

> EDIT: Is it possible for me to use my own tweaker to do mixin initialization?

Yes absolutely, the tweaker in the package is provided for convenience but ultimately it doesn't matter which tweaker actually gets the ball rolling.

**Comment by luacs1998** [comment]
Hmm, I'm doing the exact same things as Zidane (from what I see), but why is mixin complaining that it isn't in the right classloader? Must I reflectively call MixinBootstrap.init()?

Just thinking out loud here.

**Comment by Mumfrey** [comment]
Because you can't initialise the mixin environment from a coremod in production, as I said, the mixin environment *must* be initialised from a tweaker in a production environment. In dev, it's safe to dispense with the tweaker and use the coremod, that's why both bits of code exist: one handles dev, the other handles production.

Once it's successfully initalised in the right classloader, it's safe to call `getEnvironment` from elsewhere, but the `MixinBootstrap.init()` **must** be called in the system classloader. The bootstrap handles excluding the mixin package from the LaunchClassLoader in order that this state of affairs obtains.
