### ISSUE TITLE
Allow static injection methods for non-static methods

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#172]
Currently, Mixin requires injection methods to be non-static when injecting into a instance method of the target class. It makes sense to prevent this for the other way around (a non-static injection method for a static target method) but I was wondering if there is a special reason to forbid making the methods static if they don't access any instance variables/methods in the target class.

I noticed IntelliJ IDEA suggests making them static if they don't reference anything in the Mixin class so I thought I'd ask if this is something we could change before I suppress the inspection entirely for injection methods.

**Comment by Mumfrey** [comment]
Sorry for the delay in responding to this ticket, I've had a solid two months of back-to-back events, I'm back in the real world today so will resume triaging issues.

The restriction isn't there because it's impossible, and some injectors already support static-handler-for-instance-method in order to (for exaple) allow `@ModifyArg` to be used safely in a superconstructor call.

My recollection is that the reasons for the existence of the restriction are:

* It made the injector logic simpler, where in general simpler is better because simpler is less likely to container bugs. Ironically (and the reason I said *"made"*) is that I'm pretty sure that most injectors actually support this and it's only the sanity check which actually fails. It would need checking before removing the restriction, but I think 80~90% of the code would work without alteration. That's the technical reason.
* The other reason is that some of the restrictions in Mixin are there to make mixin code more consistent. It was just a design decision made early on in development that handlers would have this property of matching staticness with their target just as an added visual clue when reading mixin code, eg. you see a handler called `private static onSomethingHappened` and you know that its target is a static method in the target. Might not be the strongest of reasons but it's a reason all the same.

I have no particularly strong feelings either way. There's next to no performance penalty to the current paradigm, and in fact if the handler is `private` then there's no performance penalty, adding a `static` modifier literally only has the effect of reducing the method's frame by 1 dword. This is just one of those situations where (for normal code), Jetbrains are saying *"hey this looks like a utility method, it might as well be static"*, ReSharper does it as well.

Open to any kind of feedback on this, since it's literally only a style choice I'm not sure if we'll get any strong opinions either way but I'll throw it out there.

**Comment by kashike** [comment]
I think it's nice having them non-static when you aren't targeting non-static methods. It's more clear.

**Comment by Mumfrey** [comment]
@kashike not sure if you're in favour of or against changing it since I think one of your double-negatives got flipped?

> it's nice having them non-static when you aren't targeting non-static methods

They can't be non-static when you aren't targetting non-static methods (double-negative = *are targetting static methods*) because a static method can't invoke an instance method.

**Comment by kashike** [comment]
Fixed my command. :joy_cat:

**Comment by Minecrell** [comment]
Yeah, I see your point and I agree. Thanks for explaining it!
