### ISSUE TITLE
Redirect array length access

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#173]
For example to change code like this:
```java
                if (y >= 0 && y >> 4 < this.storageArrays.length)
                {
                    ExtendedBlockStorage extendedblockstorage = this.storageArrays[y >> 4];

                    if (extendedblockstorage != NULL_BLOCK_STORAGE)
                    {
                        return extendedblockstorage.get(x & 15, y & 15, z & 15);
                    }
                }
```
 `y >= 0` can be now targetted with expanding zero conditions but `[whatever] < array.length` can't be changed without creating a whole new array of needed length. Ff the needed length would be big (as it is in my case, as I'm also redirecting array element access here) it's impossible without seriously affecting performance (or preallocating a very big array, and completely impossible for negative values).

I see 2 possible ways to implement it using redirect: 
 * Special injection point that targets `ARRAYLENGTH`. Since it's not a real field, a special injection point would make sense
 * Make mixin pretend it's a field, and redirect it using field redirect, but silently looking for `ARRAYLENGTH` opcode. An argument for that is that in java code it looks like a final field in all possible situations except when using reflection (even compiler says it's a final field when trying to write to it).

**Comment by Mumfrey** [comment]
Given that array accesses can be redirected, this does make sense as a feature, since it would - as you point out - allow you to fully "virtualise" the array and have it call back into your own code to handle the actual access. Of course, any actual bugs created by this (eg. redirecting the array length access and subsequently failing to redirect the actual access) are on the mixin author!

Let me have a think about how I want to present this to make it consistent with how array access redirects work, at the moment they simply change their behaviour based on the targetted opcode so I see no immediate reason to deviate from that (as you say, combined with being able to target ARRAYLENGTH opcodes with an appropriate injection point). But let me think on it all the same. Treating it as a pseudo-field would seem to make sense.
