### ISSUE TITLE
How could  i overwrite a Single line of code?

### ISSUE THREAD

**Issue by kingcraftingnl** [SpongePowered/Mixin#178]
So i want to overwrite the line    this.ingameGUI = new GuiIngame(this); 
In the init Method in the Minecraft class,
Im using LiteLoader

**Comment by Mumfrey** [comment]
---
> ### **NOTE**: This is an *issue tracker* not a *support forum*. Please direct queries to IRC next time, or since this is a liteloader-specific query use the [forum thread](http://liteloader.com/discuss).
---

If you read [the documentation](https://github.com/SpongePowered/Mixin/wiki) then you will know that Mixins don't generally support overwriting "a line" of code, however certain accesses can be targetted for [injections of various sorts](https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors) including *Redirection* using [`@Redirect`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/Redirect.html) handlers.

In the case above, if you wanted to replace the call to the constructor of `GuiIngame` with a call to your own class which *subclasses* it, then you could do so using a `NEW` redirector.

_**However**_, even though this is supported, in this particular case that would come under the heading known as "*really fucking stupid things to do*" because replacing core game classes which may be hooked into by other mods (and - you know - LiteLoader itself) is a *Really Bad Idea*&trade;. Instead if you're planning to hook into the `GuiIngame` class you should mix into it directly and **definitely not under any circumstances** replace it with your own class. This goes for all core game singletons. Swapping out classes wholesale is exactly the situation Mixin is designed to avoid, and doing so just defeats the entire purpose of using them in the first place. There is nothing you can achieve by subclassing which you *cannot* achieve by mixing in.

If - on the other hand - what you're wanting to do is just have something happen *at that precise point during initialisation*, then all you need to use is an [`@Inject`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/Inject.html) coupled with the `INVOKE` injection point.
