### ISSUE TITLE
When using eclipse compiler, when 2 mixins targetting the same class have lambdas of the same class, mixin will use the wrong one for one mixin

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#181]
A simple test case:
```java
public class Test {
    public void test1() {  exec(() -> {});  }
    public void test2() {  exec(() -> {});  }
    private void exec(Runnable run) {  run.run();  }
    public static void main(String... args) {
        new Test().test1();
        new Test().test2();
    }
}
```
```java
@Mixin(Test.class)
public abstract class Mixin1Test {
    @Shadow protected abstract void exec(Runnable run);
    @Redirect(method = "test1", at = @At(value = "INVOKE", target = "Ltest/Test;exec(Ljava/lang/Runnable;)V"))
    private void redirectExec1(Test test, Runnable orig) {
        exec(() -> System.out.println("test1"));
    }
}
```
```java
@Mixin(Test.class)
public abstract class Mixin2Test {
    @Shadow protected abstract void exec(Runnable run);
    @Redirect(method = "test2", at = @At(value = "INVOKE", target = "Ltest/Test;exec(Ljava/lang/Runnable;)V"))
    private void redirectExec2(Test test, Runnable orig) {
        exec(() -> System.out.println("test2"));
    }
}
```
It should print first test1 and then test2. For me it prints out test1 twice when using the eclipse compiler. Works fine with javac.

**Comment by Mumfrey** [comment]
I am away on an event until the 12th, I'll take a look into this when I'm back.

**Comment by Mumfrey** [comment]
Effectively a duplicate of #100, which has remained open since I couldn't reliably reproduce the circumstances of its occurrence. However fixing this issue uncovered an underlying problem with the way `@Unique` was handled and remapping of method handles:

* If a method doesn't exist in the *original* target class, then the semantics of `@Unique` were defeated if two mixins added the same "unique" method.
* Renamed methods in the mixin were not properly redirected if referred to inside a `MethodHandle`

Fixing this issue involved applying the same semantics as `@Unique` to the lamba methods, but required fixing the second issue in order to actually work properly.

Lambda methods are now correctly remapped if a counterpart already exists, either in the target class or in an upstream mixin.
