### ISSUE TITLE
Bad debug message when loading a Mixin with a nested class

### ISSUE THREAD

**Issue by BigBastard** [SpongePowered/Mixin#187]
I was having trouble with this earlier, when I tried loading a mixin for the following code.

https://gist.github.com/BigBastard/89478a744e1853f45f95b2fbbcff00fa

When running this with debug logging, there is no error message, just a ClassNotFound exception.

The issue is coming from the Predicate itself, which Im assuming creates a hidden inner class that has the code. My guess is that this inner class comes into conflict with the inner class within the EntityRenderer.class, and the game freaks out in response.

                Predicate pred = new Predicate<Entity>() {
                	public boolean apply(@Nullable Entity p_apply_1_) {
                		return p_apply_1_ != null && p_apply_1_.canBeCollidedWith();
                	}
                };

The issue resolved itself after I created a separate class for the predicate object with the same override, and I changed it to 

                //New class made just for this
                Predicate pred = new StupidPredicate();

Either way, there is no proper log message for this, and it took me quite a while to scan for this. Please Fix.

**Comment by Mumfrey** [comment]
It's always been the case that inner classes are not allowed in mixins unless they are either `static` or are synthetic. Since you cannot create `static` anonymous inner classes this falls foul of that rule. However I agree that a better message could be provided, so I will look into making it more obvious when an inner class cannot be loaded because it doesn't exist.

**Comment by Mumfrey** [comment]
I've decided to just straight up support inner classes in Mixins from version 0.7 onward, so I'm considering this issue resolved.
