### ISSUE TITLE
Allow Mixin to be run outside of a launchwrapper context

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#19]
Currently, applying mixins requires that Mixin be started from a tweak class, invoked by launchwrapper. This means that a full server instance must be started just to see if a mixin will apply cleanly.

Allowing Mixin to be started without launchwrapper (with Forge on the classpath) would allow the actual application of mixins, not just their compilation, to be tested on a CI server, without the need to start a Minecraft server instance.

Normally, Mixin registers a classloader through launchwrapper. When a class is loaded, the class loader checks if there are any mixins for it. If so, it runs them on the class.

In the scenario I propose, Mixin would inspect that target(s) of each registed mixin, and load the class for it. The loaded class would then be processed as normal.

**Comment by luacs1998** [comment]
Wouldn't it fall on you to test your mixins locally before submitting to your CI, or is this for unit testing?

**Comment by jamierocks** [comment]
Not only will it allow it to be used on ci's but be able to be used in projects that aren't mc related.

**Comment by Mumfrey** [comment]
> Allowing Mixin to be started without launchwrapper (with Forge on the classpath) would allow the actual application of mixins, not just their compilation, to be tested on a CI server, without the need to start a Minecraft server instance.

No it won't, at least not very effectively, because you still need to instance the upstream transformers in order for application of the mixins to work in most cases. Applying mixins to un-transformed bytecode has applications when you're **not** using it for a downstream project (eg. say Lex wanted to use mixins to implement parts of Forge itself, he could write mixins which worked on the *un-transformed* bytecode and it would make sense to apply those outside of a real runtime environment) but when you're relying on the work of upstream transformers, all you're going to do is bring yourself pain and suffering if you attempt to apply the mixin to the "raw" bytecode.

In other words, if you're thinking of using a feature like this to test application of Sponge mixins then you're going to need some pre-transformed bytecode hanging around and/or to run the upstream transformers first as part of your test cycle. Even if it does work, applying mixins in a different context doesn't really provide any value add from the point of view of testing because it could still fail when run "for real" with the upstream transformers in play.

> Not only will it allow it to be used on ci's but be able to be used in projects that aren't mc related.

Launchwrapper is pretty much environment-agnostic, you can (and some of us already do) use launchwrapper on projects which aren't mc related, you can also use launchwrapper interfaces even if you're not using the launchwrapper classloader itself, for example in a custom classloader there's nothing which says you can't consume instances of `IClassTransformer`.

**Comment by Mumfrey** [comment]
Closing if there are no further comments, similar functionality to the proposed is already roadmapped and this issue doesn't really contribute anything.
