### ISSUE TITLE
Snapshot releases not working as launcher profile libraries

### ISSUE THREAD

**Issue by ZeroMemes** [SpongePowered/Mixin#191]
When adding Mixin 0.6.10-SNAPSHOT to a launcher profile config as so, the minecraft launcher failed to download the snapshot as a library.
```
{
  "name": "org.spongepowered:mixin:0.6.10-SNAPSHOT",
  "url": "http://repo.spongepowered.org/maven/"
}
```
This is due to the file being located at ``https://repo.spongepowered.org/maven/org/spongepowered/mixin/0.6.10-SNAPSHOT/mixin-0.6.10-20170525.114836-1.jar`` and not ``.../0.6.10-SNAPSHOT/mixin-0.6.10-SNAPSHOT.jar``.

Liteloader doesn't seem to have the same issue, where ``http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/liteloader-1.11.2-SNAPSHOT.jar`` will redirect to ``.../1.11.2-SNAPSHOT/liteloader-1.11.2-20170222.113404-8-release.jar``.

The only reason I can think of for this occurring would be a server-side fix for the liteloader repo that had to be made.

**Comment by Mumfrey** [comment]
This is an issue because the Sponge maven repo is not a "real" maven repo, it's just an FTP server, my repository at `repo.mumfrey.com` is a *Sonatype Nexus* installation. However you are correct to assert that there is some server-side magic in place, you just aren't using the correct URL, the server side magic exists on `dl.liteloader.com`.

To clarify, you should **not** use `repo.mumfrey.com` in build scripts or launcher profiles, that server is not a frontline server and should not be linked to directly since I make no guarantees about its long term availability. However you **can** use `dl.liteloader.com/versions` for launcher profiles and `dl.liteloader.com/repo` for build scripts. That server is configured with appropriate dynamic redirects so that requests for liteloader snapshots or mixin snapshots will always redirect to the correct location.

The `dl.liteloader.com` endpoints bounce via a `302` to handlers on `redirector.liteloader.com` which will always bounce to the correct location.

So the correct way to include mixin in a launcher profile is as follows:

```json
{
  "name": "org.spongepowered:mixin:0.6.10-SNAPSHOT",
  "url": "http://dl.liteloader.com/versions/"
}
```
