### ISSUE TITLE
Mixin does not work with Generics like normal Java

### ISSUE THREAD

**Issue by MCmodding4K** [SpongePowered/Mixin#192]
Hi,

I think this would be super cool because you can apply it to multiple classes and use the same code.
(and it might be easy to add to Mixin)

https://gist.github.com/MCmodding4K/254298dcd98b96d315b52048915b1798
instead of
https://gist.github.com/MCmodding4K/9a5cfc71cc5bbadee21ff65fdb505efc
and https://gist.github.com/MCmodding4K/99249f9f21d53feeb176873bd8b68203

**Comment by Mumfrey** [comment]
Oddly enough you are incorrect: the issue here is not actually about generics, since generics don't actually exist at runtime, the issue preventing this working as you hoped is that injector signatures have to match types exactly. To explain what's going on and how to deal with it, you need to understand a bit about what the generics on the classes in question **actually _mean_**:

### Explanation of generic methods

Firstly, if you have a generic type argument on a class with a concrete bound or a derived bound, then the *actual* signature of methods using that type argument will be of that type. So in this case for the class `TileEntitySpecialRenderer<T extends TileEntity>` the actual method signature in code says `T` but in the compiled class the signature will have `TileEntity` because the least derived type of `T` is `TileEntity`. Thus this Java code:

```java
public abstract void renderTileEntityAt(T te, double x, double y, double z, float partialTicks, int destroyStage);
```

has this signature in bytecode:

```php
renderTileEntityAt (Lnet/minecraft/tileentity/TileEntity;DDDFI)V
```

This is important to realise, since if the bound is not concrete then obviously derived classes can narrow the bound (or not of course), so let's look at the derived class `TileEntityEnderChestRenderer`. The `TileEntityEnderChestRenderer` class narrows the bound to `TileEntityChest`, so the new signature for the method is now

```java
public void renderTileEntityAt(TileEntityEnderChest te, double x, double y, double z, float partialTicks, int destroyStage) {
```

and in the bytecode:

```php
renderTileEntityAt (Lnet/minecraft/tileentity/TileEntityEnderChest;DDDFI)V
```

***However***, this magical change of signature does not come without cost. Imagine that an outside class has an instance of `TileEntitySpecialRenderer`, but does not know the specific *derived* class it has (obviously, thanks to object-oriented principles, it doesn't have to) but it wants to be able to call the `renderTileEntityAt` method. But there's a problem: because the signature of the `renderTileEntityAt` method is different to the base class, the `renderTileEntityAt` method in `TileEntityEnderChestRenderer` **does not actually override the base-class method**. So how can it be called?

The answer is that the compiler **does** override the method, it then has the overridden method call the new one. So in the compiled class, `TileEntityEnderChestRenderer` actually contains **two** `renderTileEntityAt` methods:

```java
@Override  // This method overrides the method in the base class, it is generated by the compiler
public void renderTileEntityAt(TileEntity te, double x, double y, double z, float partialTicks, int destroyStage)
{
    // just calls the new method
    this.renderTileEntityAt((TileEntityChest)te, x, y, z, partialTicks, destroyStage);
}

public void renderTileEntityAt(TileEntityChest te, double x, double y, double z, float partialTicks, int destroyStage)
{
    // actual code
}
```

The generated method is invisible to you, it is created by the compiler (such methods are called *synthetic* because the compiler creates them) and it is know as a **bridge method** or **synthetic bridge**. It exists so that outside code can call the base-class method and have it cast to the specialised type on-the-fly.

### So why do you need to know all this?

Well you can now probably see why your mixin is failing: **because you have only specified the _method name_ in your injector, Mixin will try to inject into _both_ methods, and only one will succeed!**

So you have a choice: The simplest approach -- given that you only want to inject at `HEAD` -- is to *use* the fact that the synthetic bridge method exists, and just inject into it. This is the simplest approach and can be achieved by simply appending the *base class* method signature to the injector target intention:

```java
@Mixin({TileEntityChestRenderer.class , TileEntityEnderChestRenderer.class})
public class MixinTileEntity_Renderer<R extends TileEntity> extends TileEntitySpecialRenderer<R> {
    R te;

    // This will inject into the synthetic bridge method because R is TileEntity
    @Inject(method = "renderTileEntityAt(Lnet/minecraft/tileentity/TileEntity;DDDFI)V", at = @At("HEAD"))
    private void renderTileEntityAt(R te, double x, double y, double z, float partialTicks, int destroyStage, CallbackInfo ci) {
       this.te = te;
    }
}
```

The alternative, which is by far less elegant, is to leverage *surrogate* methods and have a surrogate for each derived type, in which you cast down and call back to your actual injector method. This is inelegant because it relies on the fact that the "real" method occurs *before* the synthetic bridge, but it does work and has the advantage that it allows other injection points than `HEAD` so it can be useful in that regard:

```java
@Mixin({TileEntityChestRenderer.class , TileEntityEnderChestRenderer.class})
public class MixinTileEntity_Renderer<R extends TileEntity> extends TileEntitySpecialRenderer<R> {
    R te;

    @Inject(method = "renderTileEntityAt", at = @At("HEAD"))
    private void renderTileEntityAt(R te, double x, double y, double z, float partialTicks, int destroyStage, CallbackInfo ci) {
       this.te = te;
    }

    @Surrogate
    private void renderTileEntityAt(TileEntityChest te, double x, double y, double z, float partialTicks, int destroyStage, CallbackInfo ci) {
        this.renderTileEntityAt((R)te, x, y, z, partialTicks, destroyStage, f, ci);
    }
    
    @Surrogate
    private void renderTileEntityAt(TileEntityEnderChest te, double x, double y, double z, float partialTicks, int destroyStage, CallbackInfo ci) {
        this.renderTileEntityAt((R)te, x, y, z, partialTicks, destroyStage, f, ci);
    }
}
```

In essence, the `@Surrogate` methods become - themselves - bridge methods to your actual injector. As I said, I would only use this approach if you wanted a location in the target method other than `HEAD` though, since injecting into the synthetic bridge is in general perfectly adequate for the task.

### Possible enhancements to Mixin

As a possible enhancement to support this kind of scenario, the only thing I can imagine which could be done is to have Mixin auto-generate surrogates for generic methods, though this would mask the previous problem where there is ambiguity between existing synthetic bridges and the actual non-synthetic intended target. It's one of those situations where some of the compiler shenanigans that occur in Java actually need to be understood in order to properly interact with compiled classes.

I would like you to bear in mind also that generics in Java are a minefield at the best of times, and that expressiveness/reliability is always going to trump syntactic sugar in my mind. Thus if this can't be addressed without compromising integrity, then no changes will be made.

**Comment by Zidane** [comment]
Great explanation as always @Mumfrey ...especially for something many use but many have no clue on how  it actually functions.

**Comment by MCmodding4K** [comment]
dude, thank you SO much!

**Comment by Mumfrey** [comment]
@MCmodding4K further to the discussion above. I realised that as long as the type on the injector is a supertype of the argument in question, then it's possible to simply invoke the handler without a type cast or any other checking in the injection itself. *However* since this would require a superclass lookup for **every** reference type argument on every injector, it could get expensive very quickly.

With this in mind, I simply added a new purpose for the `@Coerce` annotation which can be used to indicate that the injector should attempt to resolve type covariance for the decorated argument. This means it's now possible to write your desired injector like this:

```java
@Mixin({TileEntityChestRenderer.class , TileEntityEnderChestRenderer.class})
public class MixinTileEntity_Renderer<R extends TileEntity> extends TileEntitySpecialRenderer<R> {
    R te;

    @Inject(method = "renderTileEntityAt", at = @At("HEAD"))
    private void renderTileEntityAt(@Coerce R te, double x, double y, double z, float partialTicks, int destroyStage, CallbackInfo ci) {
       this.te = te;
    }
}
```

Note the `@Coerce` annotation on the variant type argument. This tells Mixin that when injecting it should attempt to resolve the method argument as a superclass type of the target argument type. If the check succeeds, the injection will also succeed.

**Comment by MCmodding4K** [comment]
one last question...
Everything works fine, but when i try to build, it fails :(

MixinTileEntity_Renderer.java:35: error: Multi-target reference conflict for @Redirect target renderTileEntityAt: renderTileEntityAt -> func_180535_a(Lnet/minecraft/tileentity/TileEntityEnderChest;DDDFI)V previously defined as func_180535_a(Lnet/minecraft/tileentity/TileEntityChest;DDDFI)V
[ERROR] [system.err]     @Redirect(method = "renderTileEntityAt", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/model/ModelChest;renderAll()V"))

**Comment by Mumfrey** [comment]
You need to update to the latest snapshot, I [reduced this to a warning](https://github.com/SpongePowered/Mixin/commit/c6ce27efb06175843ac1ffff500635e1a88c44bc) for methods using `@Coerce`.

**Comment by MCmodding4K** [comment]
hm, now i have a warning and an error... xD
https://gist.github.com/MCmodding4K/3e949b934f8db41679524f683e86bfcb
