### ISSUE TITLE
Allow Inject local capture to only capture local variables specified in a slice

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#196]
I thought about this for the last few weeks and came to the conclusion that it may be a viable idea.

Mixin already has a way to know all local variables defined/used up to a specific point, so it shouldn't be too hard to discard all local variables specified up to a point somewhere before in the code.

Currently injecting with local capture into any non trivial method means that the injection will have a lot of arguments that are mostly completely irrelevant to what the injection is doing. And it breaks every time the LVT changes. Allowing to only use variables from a slice would bots make injectors less noisy and less prone to breakage by changing LVT.

**Comment by Mumfrey** [comment]
I'm not really keen on this for a couple of reasons:

Firstly, capturelocals is already the most brittle aspect of mixins, and adding functionality which makes it less deterministic doesn't really help in my opinion. You can already discard any local variables from the *end* of the signature, allowing you to only depend on the LVT being correct up to the point you want to use. This means that currently there's a level of sanity-checking built into the signature of the handler method itself, and obviously features like `@Coerce` allow some variance of types based on information lost in stripped LVTs.

Secondly, the concept of "local variables up to that point" doesn't really make sense either, since half the problem and brittleness of local capture in the first place is that such an assertion has no analogue in bytecode, so if you were to say capture only variables added in the last FRAME_FULL, FRAME_APPEND or FRAME_NEW then this still has very little meaning for any given point in the code. It doesn't even have meaning in its own terms since as we know from bitter, horrible experience, ASM quite often fucks this up and that's what's lead to a lot of the horribleness in `Locals` in the first place!

Even then, assuming that's possible, how would you define where the current "partial frame" starts? If your slice misses a stack map frame then you're back to square one anyway, and even if you somehow magically hit that spot, what does your handler signature look like in order to specify a slice out of the frame?

The code in `Locals` is an insanely delicate and temperamental state machine, and in order to get even to the point we're at now it has to make a lot of assumptions, handling for corner cases, etc. and there's just no way to get away from that whilst still being able to work with production Minecraft. In an ideal world yes, but in the environment we're working with it's just not feasible.

> And it breaks every time the LVT changes.

Yes that's intentional, it's dangerous code so you should *have* to update it if anything changes, your assumptions need to be revisited. The redundant arguments in local capture are there *on purpose* to provide some sanity over what the captured locals are supposed to be. There are already concessions in terms of truncating and `@Coerce` and ways of capturing a single local by leveraging `@ModifyLocal` and storing the value. Additional levels of complexity are just not something I'm willing to entertain in the name of just making handler signatures a tiny bit prettier.

**Comment by Barteks2x** [comment]
Ok, I didn't realize it's already in so bad situaton. It seemed much simpler when I imagined it myself. Mixin hides the complexity enough that it's not so apparent that it's such a hard problem.
