### ISSUE TITLE
Forge mod with mixin fails to work with Liteloader

### ISSUE THREAD

**Issue by ThisTestUser** [SpongePowered/Mixin#197]
For some reason, using a Forge mod with mixin and then running liteloader with Forge always results in a crash. Is this intended behavior?

[main/ERROR]: mixins.testmod.json:MovementForward: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateClassVersion(MixinInfo.java:470) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:444) ~[liteloader-1.8.9-SNAPSHOT.jar:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
...
It states that version 52 is unsupported, but I have Java 1.8 and I compiled it using Java 1.8 (by changing the Eclipse preferences)
But then if I don't run Liteloader with Forge, it works perfectly.
It even sets the compatibility level automatically.
[main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[main/INFO]: Compatibility level set to JAVA_8

I currently use mixin version 0.7.0, but I've tried to use older versions like 0.5.3 but it still shows the same error.

**Comment by gabizou** [comment]
Post actual logs, preferably using https://gist.github.com/ or something thereof.

**Comment by Mumfrey** [comment]
Wrong issue tracker. Normally I'd say open an issue on the LiteLoader tracker but since you're using an ancient version of the game I'm not really prepared to support it anyway since I only support back to 1.10.2.

The Version 52 error means you compiled a class with Java 1.8 but didn't specify 1.8 in your mixin config. This is not a bug and therefore not relevant on this issue tracker. If the bug is present on 1.12 then I might look into it, but this doesn't look like a bug to me.

**Comment by ThisTestUser** [comment]
@Mumfrey Sorry if I'm doing this wrong, but I already have Java 1.8 support added:
(Config mixins.testmod.json)
`
{
    "required": "true",
    "package": "com.testmod.mixins",
    "mixins": [
        "MixinMinecraft"
    ],
    "compatibilityLevel": "JAVA_8",
    "refmap": "mixins.testmod.refmap.json"
}`
I've also tried to use MixinEnvironment.setCompatibilityLevel(), but it doesn't work either. 
Also, a problem I've noticed in the logs is that it uses the mixin library from Liteloader, which is 0.5.3. I'm currently using 0.7-SNAPSHOT. I've tried to downgrade my mixin library to 0.5.3 but it didn't work.

**Comment by Mumfrey** [comment]
Being able to set the compatibility level in the config wasn't added until 0.5.6 so I would guess that the issue is that the 0.5.3 being used is the issue. You either need to put a newer version of mixin higher on the classpath than liteloader or specify `-Dmixin.env.compatLevel=JAVA_8` on the command line.

**Comment by Yuan-Quan** [comment]
Specifications:
  1.12.2-forge1.12.2-14.23.5.2847
  Windows x64
On one of my computers, A mixin based mod liquidbounce just won't work with liteloader.
Another computer, with liquidbounce and liteloader in `mods` works just fine, but if there are any liteloader mod it won't start.
