### ISSUE TITLE
I cant install Mixin

### ISSUE THREAD

**Issue by Tubbyboy05** [SpongePowered/Mixin#198]
Can someone help me install mixin I cant get it!

If you need anything to help ask me!

**Comment by Mumfrey** [comment]
This is an issue tracker not a support forum.

**Comment by Mumfrey** [comment]
You can thumbs-down all you like, and you know what? When people have come here and asked a serious question with time and thought put into it, I've closed their issue *and answered their question*!

You wrote

> Can someone help me install mixin I cant get it!

The question makes **no sense**. Do you mean *maven install*, *deploy with your mod*, *use with your project*? What? You don't say what you're trying to "install" in the first place, and since there are already instructions for all of the common use cases, I can only take away that you are either too lazy to read the documentation or have a use-case outside the common ones which you're too lazy to describe.

> If you need anything to help ask me!

No. As I said **this is an issue tracker** not a support forum. **Issue**. **Tracker**. It's an area where users can make feature requests and report bugs with the software. The onus is **not** on me to hand-hold you through pressing the buttons on your keyboardification mechanism to describe in detail the dimensions of your request. If you **cannot even be BOTHERED** to describe the barest outline of your issue then how in the hell do you feel it's appropriate to demand that I expend my time and effort to play some sort of bizarre guessing game to try and fathom what in blue blazes you're going on about.

You can take your thumbs down and your entitled, childish attitude and find somewhere inventive to stick it.
