### ISSUE TITLE
Mixin reports invalid usage of LOAD injection point as STORE injection point

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#199]
I tried to use `LOAD` injection point in `@Slice` (why isn't it even allowed anyway?), I noticed that mixn reports it as `STORE` in exception:

```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: STORE injection point must be used in conjunction with @ModifyVariable
```

**Comment by Mumfrey** [comment]
The error message being wrong is just a minor oversight in the error message.

The reason that `LOAD` and `STORE` can only be used with `ModifyVariable` is because they are not normal general-purpose injection points. They are special injection points for use with `ModifyVariable` which use the `@ModifyVariable` annotation as a *discriminator* to locate the correct local variable. Without the outer annotation there is nowhere for the injection points to obtain the discriminator from.
