### ISSUE TITLE
Platform manager can be instanced multiple times in development environment leading to coremods being injected more than once

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#206]
My mod has optional dependency on MalisisCore, which recently started using Mixin. Now when running my mod in dev environment, it's transformers break because they are applied many times on already transformed code.

The dependency transformers end up being added 3 times to the transformer list, with me being able to remove one by adding `--noCoreSearch` argument:
 * The first time, it's added as a resule of me calling `MixinBootstrap.init()` in my coremod
 * The second time it's added by ForgeGradle's coremod discovery
 * The third time it's added by `MixinPlatformAgentFML` because the mod has `FMLCorePlugin` specified in `MANIFEST.MF`

The ideal solution would be to make mixin not add the coremod by itself when it's a dependency (how could it be detected?) and just let ForgeGradle add it.

Note: I'm using mixin 0.6.15 (still) but I wouldn't expect this issue to be gone after updating to 0.7.*.

This also seems to be the same issue someone linked me: https://forums.spongepowered.org/t/spongeforge-plugin-development-crash-after-setting-up-environment/20457

**Comment by Mumfrey** [comment]
This seems to be tied to the platform manager being instanced more than once, most likely because it's a static field on mixinbootstrap which is being loaded in both classloaders.

**Comment by Mumfrey** [comment]
Try that, it might work or it might explode, it should theoretically work with forgegradle's scanning too, I haven't got an environment I can actually test this in so I'm just guessing.

**Comment by Barteks2x** [comment]
I will test it tomorrow when I'm back at the computer where I have the dev environment.

**Comment by Zidane** [comment]
@Mumfrey @kashike is reporting that after bumping Almura to latest Mixin, we're now experiencing Sponge getting double-loaded.

https://gist.github.com/kashike/d818797ed90cee7a677b1463c54c00c9#file-gistfile1-txt-L3478

**Comment by kashike** [comment]
I don't think this worked. It seems to still be happening with Almura:
https://gist.github.com/kashike/d818797ed90cee7a677b1463c54c00c9#file-gistfile1-txt-L115
https://gist.github.com/kashike/d818797ed90cee7a677b1463c54c00c9#file-gistfile1-txt-L355

**Comment by Mumfrey** [comment]
Looking at your logs it looks like the changes fixed the problem *as described above*. Mixin platform now:

* Only gets initialised once ✔️ 
* Properly ignores the command-line coremod for Almura ✔️ 
* Only bootstraps and injects SpongeForge once ✔️ 

However, I think we now have a corollary problem which is that in production, Mixin has to co-initialise the tweaker wrapper because it's injected too late for Launch to catch it. I **think** what's happening now is that the tweaker cycle is still active so the tweaker wrapper *does* get visited, so mixin successfully injects the coremod but **doesn't** need to co-initialise it. I'll have to work out a way to detect and handle that :/

**Comment by Mumfrey** [comment]
Ok this might work now. Using `--noCoreSearch` seems to be basically required if you have more than one coremod because it nukes any coremod specified on the command line, so we'll just take it as read that that option needs to stay enabled.

@Zidane in my investigations I also found a bug in the AP which means that [these mixins](https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/java/net/malisis/core/asm/mixin/core/MixinClientNotif.java) wouldn't work in production because the AP wasn't generating the correct name. This is fixed by 5a1a51a2f059a1a62c32741422b3032591537b29 so you can tell Ordinastie that he needs to update to the latest 0.7.2 snapshot to use nested mixins like that.

**Comment by Barteks2x** [comment]
Works fine for me.

**Comment by Mumfrey** [comment]
Fantastic, I shall consider this resolved.
