### ISSUE TITLE
Possible bug with @ModifyVariable

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#209]
I'm trying to mixin the method NetHandlerPlayServer.processPlayerDigging(CPacketPlayerDigging packetIn) to modify the variable declared as 
`double d3 = d0 * d0 + d1 * d1 + d2 * d2;` (L:690) https://puu.sh/xDPiH.png

The code I have : 
```java		
@ModifyVariable(method = "processPlayerDigging", at = @At(value = "STORE", ordinal = 4), require = 1, print = true)
private double onPlayerDigging(double distance)
{
	return distance;
}
```

I couldn't make it work and always got : 
`[23:15:29] [Netty Local Client IO #0/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method localvar$onPlayerDigging$zze000(D)D in mixins.malisiscore.core.json:MixinChunkCollision$MixinNetHandlerPlayServer failed injection check, (0/1) succeeded`

Coded (commented) can be found here : https://github.com/Ordinastie/MalisisCore/blob/1.12/src/main/java/net/malisis/core/asm/mixin/core/MixinChunkCollision.java#L75

@kashike said it might be a Mixin bug, so here it is.
> \<kashike> it's only finding one target, the method's `packetIn` variable

**Comment by Mumfrey** [comment]
There actually was a bug, but not the actual bug you were thinking of. In investingating this I realised that the interaction of a failing implicit discriminator and the `print` option actually leads to no useful output, so that's the first bug I fixed. The second bug was in the [Locals](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/util/Locals.java) class which resolves the method LVT at each opcode which was failing when frame trim occurred after a precise match on a var instruction, because the termination check was short circuited accidentally in this case.

This was masked by your injection itself being incorrect, and I would assume that this is because the way `ModifyVariable` works is not clear enough, so explanation follows. I should also mention that this:

> &lt;kashike&gt; it's only finding one target, the method's `packetIn` variable

is complete nonsense and I'm not sure where he got that idea from. Anyway, the explanation:

The `STORE` and `LOAD` injection points do not work like normal injection points, they are specifically designed to work with `ModifyVariable` and the context of the outer annotation is important. The values defined on the outer annotation are used to *discriminate* the correct variable in the target method. The discriminator can be completely omitted if there is only one variable of the specified type in the method body (useful for reference types), this type of discriminator is called an *implicit discriminator* because the variable to match is implied. *Implicit discriminators* will **fail** if more than one variable of the specified type is present in the LVT. In your injection, you have not specified the `ordinal`, `index`, or `name` of the variable to match and therefore the discriminator has failed (it would have failed anyway because of the bug in `Locals`, but now it fails because it's wrong).

Of course, the one time you might want the discriminator to deliberately fail is when using `print` to see what possible values of `ordinal` and `index` there are, the fix for this issue now means that if `print` is set to `true`, the implicit discriminator is allowed to fail and the LVT will be printed instead.

The discriminator also decides what opcodes will be targetted, and in the case of a `double` modifier, the opcode in question is obviously `DLOAD`. In the target method you wish to target the 4th DLOAD opcode and since ordinals are zero-based, the actual `ordinal` value you needed was `3`. With the fixes in place, and changing the ordinal to 3 we now get:

```java
/*****************************************************************************************************************/
/*         Target Class : net.minecraft.network.NetHandlerPlayServer                                             */
/*        Target Method : processPlayerDigging                                                                   */
/*        Callback Name : localvar$onPlayerDigging$zzc000                                                        */
/*         Capture Type : double                                                                                 */
/*          Instruction : LabelNode UNKNOWN                                                                      */
/*****************************************************************************************************************/
/*           Match mode : IMPLICIT (match single)                                                                */
/*        Match ordinal : any                                                                                    */
/*          Match index : any                                                                                    */
/*        Match name(s) : any                                                                                    */
/*            Args only : false                                                                                  */
/*****************************************************************************************************************/
/* INDEX  ORDINAL                            TYPE  NAME                                                CANDIDATE */
/* [  1]    [  0]            CPacketPlayerDigging  packetIn                                            -         */
/* [  2]    [  0]                     WorldServer  worldserver                                         -         */
/* [  3]    [  0]                        BlockPos  blockpos                                            -         */
/* [  4]    [  0]                          double  d0                                                  YES       */
/* [  5]                                    <top>                                                                */
/* [  6]    [  1]                          double  d1                                                  YES       */
/* [  7]                                    <top>                                                                */
/* [  8]    [  2]                          double  d2                                                  YES       */
/* [  9]                                    <top>                                                                */
/* [ 10]    [  3]                          double  d3                                                  YES       */
/* [ 11]                                    <top>                                                                */
/* [ 12]                                        -                                                                */
/*****************************************************************************************************************/
```

So from this we can see that for the discriminator you can use the ordinal of the `double` to target, in this case also `3`, or the lvt index, which is `10`. If we use the ordinal, the final injector looks like this:

```java
@ModifyVariable(method = "processPlayerDigging", ordinal = 3, at = @At(value = "STORE", ordinal = 3), require = 1)
private double onPlayerDigging(double distance)
{
    return distance;
}
```

Thanks for reporting the bug, even though it wasn't the bug you thought it was, it's still useful in identifying an unwanted behaviour in the injector, so now it works as intended.

**Comment by Ordinastie** [comment]
Thanks for the quick fix. And for the explanation.
It's true I wasn't understanding what each ordinal truly represented. The print output really clarifies it.

I still have questions if you don't mind.
Why is the `@At` ordinal necessary if the lvt index is different for each variable ?
How can some context be passed to the annotated method ? I was advised to have an `@Inject` to capture necessary data, is this the proper way to go ?

(Side note: all credits go to @kashike. He was the one to debug my mixin, I was just miserably failing to understand why it failed :p)

**Comment by kashike** [comment]
> > \<kashike\> it's only finding one target, the method's packetIn variable

> is complete nonsense and I'm not sure where he got that idea from.

I based that off the output only having one "full" entry during debug:
```
/* INDEX  ORDINAL                            TYPE  NAME                                                CANDIDATE */
/* [  1]    [  0]            CPacketPlayerDigging  packetIn                                            -         */
/* [  2]                                        -                                                                */
/* [  3]                                        -                                                                */
/* [  4]                                        -                                                                */
/* [  5]                                        -                                                                */
/* [  6]                                        -                                                                */
/* [  7]                                        -                                                                */
/* [  8]                                        -                                                                */
/* [  9]                                        -                                                                */
/* [ 10]                                        -                                                                */
/* [ 11]                                        -                                                                */
/* [ 12]                                        -                                                                */
/* [ 13]                                        -                                                                */
/* [ 14]                                        -                                                                */
/* [ 15]                                        -                                                                */
/* [ 16]                                        -                                                                */
/* [ 17]                                        -                                                                */
```

**Comment by Mumfrey** [comment]
> Why is the @At ordinal necessary if the lvt index is different for each variable ?

So the discriminator `ordinal` or `index` will identify *which* local variable you're talking about. `ordinal` should in theory be more reliable over time since if the number of arguments on the method change then all the indexes are gonna shift along accordingly whereas ordinal will only change if another variable of the same type is added.

So let's assume that from our example we're identifying the "correct" `double` using `index=10` or `ordinal=3` in the *discriminator*. The injection point will now search for `DSTORE` opcodes which match the discriminator, of which there might be more than one. So the `ordinal` on the `@At` identifies which particular `DSTORE 10` instruction we're interested in.

> How can some context be passed to the annotated method ? I was advised to have an @Inject to capture necessary data, is this the proper way to go

Yes. In order to keep the `@ModifyLocal` injector quite simple it doesn't have any additional capabilities. However you can use any other type of injector (`@Inject`, `@Redirect`, `@ModifyConstant`) to capture the method arguments in order to provide context.

**Comment by Mumfrey** [comment]
> I based that off the output only having one "full" entry during debug:

Ah I see where the confusion is. The injector was actually finding the correct `DLOAD` but it was not determining the locals correctly because of the other bug.

**Comment by Mumfrey** [comment]
@Ordinastie I also realised while typing the explanation above that my example was wrong. Once the discriminator is configured, the `ordinal` in the `@At` becomes the ordinal index of the `DLOAD` which matches the discriminator, in this case you want the *first* one, so the correct `ordinal` for the `@At` is `0` not `3`. Apologies for that.

The correct handler looks like this (formatted for clarity):

```java
@ModifyVariable(
    method = "processPlayerDigging",
    ordinal = 3,           // double d3, using index = 10 would also work of course
    at = @At(
        value = "STORE",
        ordinal = 0        // first STORE of double d3
    ),
    require = 1
)
private double onPlayerDigging(double distance)
{
    return distance;
}
```
