### ISSUE TITLE
Methods in mixins not extending any other mixin are not transformed

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#21]
I'm trying to cast an instance of the target class to the Mixin itself so I can access a private field of it. Here is a small example:
```java
@Mixin(SomeClass.class)
public abstract class MixinSomeClass {
    @Shadow private List<SomeClass> children;
    private boolean someValue;

    private void findValues() {
        for (SomeClass child : children) {
            System.out.println(((MixinSomeClass) child).someValue);
        }
    }
}
```
Normally this should work in the `feature/supermixin` branch but it doesn't because only methods of mixins extending another mixin get transformed. When I [remove the check](https://github.com/SpongePowered/Mixin/blob/feature/supermixin/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTargetContext.java#L391-L393) it works fine, but with this check it tries to find the mixin class at runtime because the cast doesn't get replaced.

Maybe we can also extend this to mixins not extending another mixin?

**Comment by Aaron1011** [comment]
To fix this problem, I believe that the check in [`transformDescriptor`](https://github.com/SpongePowered/Mixin/compare/feature/supermixin#diff-c5603c752b2213f6705f33507868f2b8R391) needs to be removed.

**Comment by Mumfrey** [comment]
Ok, the check is just there for efficiency rather than because running the check will break anything, because looking up things in the hierarchy is expensive and thus to be avoided wherever possible. I think I'll change the logic for that flag to find if there are any mixins on superclasses of the target and that should fix the problem. I'm just going out but I'll fix it when I get back later.

**Comment by Mumfrey** [comment]
Should be fixed now @Minecrell, let me know.
