### ISSUE TITLE
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

### ISSUE THREAD

**Issue by Ordinastie** [SpongePowered/Mixin#211]
The class does appear in the JAR, I don't know if I did anything wrong : https://github.com/Ordinastie/MalisisCore/issues/123

**Comment by Mumfrey** [comment]
Can you reproduce without MultiMC?

**Comment by Ordinastie** [comment]
Got another report with MultiMC with same stacktrace. 
I don't have MultiMC but it doesn't happen with vanilla launcher. (On the other hand, I get that with the vanilla launcher : https://gist.github.com/Ordinastie/fee374187675138904ee6f2c3e9a5628#file-fml-log-L238. Should I open another issue ?)

**Comment by Mumfrey** [comment]
Something weird going on with MultiMC in that case perhaps? I have no idea why you'd get that error under normal circumstances.

The error you linked in vanilla is because [your refmap isn't being loaded](https://gist.github.com/Ordinastie/fee374187675138904ee6f2c3e9a5628#file-fml-log-L193) which more than likely is a gradle packaging error. Make sure you're running version `0.5-SNAPSHOT` of the *MixinGradle* plugin which fixes the refmap not getting included by under recent versions of gradle.

I added the note in the exception message about `"No refMap loaded"` to make it more noticable when the refmap is missing in production, before that you would receive failed injector messages but wouldn't know why. Basically in development you should see the `No refMap loaded` on those errors, in production you should always see `Using refmap 'foo.bar.refmap.json'`.

**Comment by Ordinastie** [comment]
I was indeed using MixinGradle 0.4 (I blame @Zidane :p for that one).
About MultiMC, what do I say to my users ? That you're currently investigating it ?

**Comment by Mumfrey** [comment]
If you're on IRC or discord, jump on their channel and see if anyone is about who could look into it. I'm not around until this evening so I can't currently ask anyone about it.

**Comment by tgstyle** [comment]
SpongeForge server logs this error

https://gist.github.com/tgstyle/65434bc190394409b886ea31703699a8

[main/WARN] [mixin/]: Mixin config mixins.malisiscore.core.json requires mixin subsystem version 0.7.4 but 0.7.2 was found. The mixin config will not be applied.

**Comment by Mumfrey** [comment]
That's intentional. If mixin is booted by a particular mod but another mod needs a newer version, it raises that error. It is necessary to shuffle the order of the mods so that the one with the newer mixin version loads first. This is one of the reasons that switching to jar-in-jar is happening, but at the moment it's not properly supported and doesn't work as intended.

Regardless, that error is nothing to do with the error mentioned in this issue.

**Comment by tgstyle** [comment]
OK, the server stops on that error though.

**Comment by Zidane** [comment]
@Ordinastie 

I completely forgot there was a newer MixinGradle build. My bad :p.

**Comment by Zidane** [comment]
@tgstyle As it should You're using a mod that requires a new version of Mixin when another mod loaded an older one.

**Comment by mcsnetworks** [comment]
My response:  https://i.imgur.com/91jOMpI.gif

**Comment by Mumfrey** [comment]
@tgstyle I do not tolerate people polluting tickets with unrelated idiotic prattle. Go and request advice either via an appropriate forum or via IRC.

**Comment by tgstyle** [comment]
@Mumfrey What did I do ?

**Comment by tgstyle** [comment]
@Mumfrey I do believe you confused my response with @mcsnetworks ?

**Comment by Ordinastie** [comment]
Ok, I think I found the MultiMC issue. Turns out the class was NOT in the jar.
Apparently, the base jar was getting uploaded to CurseForge instead of the shadow jar. I should have noticed that. Sorry.

**Comment by Mumfrey** [comment]
No worries, at least it was just derp and not anything serious.
