### ISSUE TITLE
Mixin @Static fields and methods, and constructors

### ISSUE THREAD

**Issue by Sollace** [SpongePowered/Mixin#217]
Over the last few days I've been looking at the mixins to see what it can can can't do, and trying to see if I can get rid of the access transformer we're currently using. After a while, though, I noticed there were a few limitations. 

The first one (Static members): The docs already say that you can inject static members, but that static methods are pretty much useless because you wouldn't have any way to call them.

There _is_ a use for wanting to inject static methods through.

Taking an example from The Game*, I have a scenario where I need to be able to overwrite CreativeTabs.CREATIVE_TAB_ARRAY. The original is public-static-final. Trying to do that with the current system (though I have no idea if this will actually workd) becomes a bit of a mess, and involves overwriting the original field which has obvious issues.

	public interface ICreativeTabs {
		//Inject an instance setter
		public void impl$setCreativeTabsArray(CreativeTabs[] tabs);
		
		//Expose a static setter ducked through an existing instance
		public static void setCreativeTabsArray(CreativeTabs[] tabs) {
			((ICreativeTabs)CreativeTabs.BREWING).impl$setCreativeTabsArray(tabs);
		}
	}

_

	@Mixin(CreativeTabs.class)
	public abstract class MCreativeTabs implements ICreativeTabs {
		//Overwrite(?) the original field
		public static CreativeTabs[] CREATIVE_TAB_ARRAY = new CreativeTabs[12];
		
		//Implement the interface
		public void impl$setCreativeTabsArray(CreativeTabs[] tabs) {
			CREATIVE_TAB_ARRAY = tabs;
		}
	}

After a bit of considerations I've come up with a (hypothetical) addition to the Mixin parser that might work and could solve the problem of statics, though I don't know how much would have to change to implement this.

	/**
	 * Use to signify a field or method that will be injected as a static member to the target class.
	 * 
	 * After injection, static methods in the Mixin class are converted to forward calls to the injected method inside the target class. Methods must be public.
	 * 
	 * Fields marked as {@link Static} and {@link Mutable} will be made non-final if necessary
	 */
	@Target({ ElementType.METHOD, ElementType.FIELD })
	@Retention(RetentionPolicy.RUNTIME)
	public @interface Static {
		
	}

_

	@Mixin(CreativeTabs.class)
	public abstract class MCreativeTabs {
		//Shadow the original field and make it mutable
		@Shadow @Static @Mutable
		public static CreativeTabs[] CREATIVE_TAB_ARRAY;

		//Inject a static setter
		@Accessor("CREATIVE_TAB_ARRAY") @Static
		public static void setCreativeTabsArray(CreativeTabs[] tabs) { }
	}

Any members in a Mixin class that is intended to become static members in the target class would recieve the @Static annotation. I decided to do it this way because starting off I couldn't really tell whether Mixin even accepted static fields. There wasn't any way to tell, so I decided it would be worthwhile having an annotation to make the intention explicit.

Fields can be marked @static alongside any of the pre-existing annotations, and will work as normally. @Mutable can also be applied alongside @Static, and the Mixing would then change the matched field in the target class to make it mutable as well. I also considered the idea that @Static could have the option to increase the visibility of the static field to be at or higher than the shadow field in the mixin, but I figured it wouldn't important considering the next part...

Just like static fields, static members can be defined using the @Static annotation in combination with other annotations (like @Accessor). The processor would then inject them with their body or a body generated by the accessor into the target class as a static method. Once that's done, the original method in the Mixin class can simply have its body overwritten to forward any of its calls to the new method in the target class.

That effectively solves the problem of not being able to call these static methods, as outside code and simply refer to the Mixin class.

	MCreativeTabs.setCreativeTabsArray(tabs);

The second limitation I found is relating to constructors. Specifically, you can't extend a class where all of its contructors are private.

This one was a bit trickier to figure out, but at the end I came up with something that looks like this:

	/**
	 * Used to indicate a mixin class constructor that is used to allow access to the underlying class.
	 * 
	 * This is usually used in conjunction with {@link Shadow} on any used or overriden members when the given class has no public constructors of its own.
	 */
	@Target({ ElementType.CONSTRUCTOR })
	@Retention(RetentionPolicy.CLASS)
	public @interface Constructor {
		
	}

_

	@Mixin(WorldType.class)
	public abstract class MWorldType {
		@Constructor
		protected MWorldType(int id, String name, int version) {}
		
		@Shadow
		public abstract String getTranslationKey();
		
		@Shadow
		public abstract boolean canBeCreated();
		
		@Shadow
		public abstract boolean isVersioned();
		
		@Shadow
		public abstract boolean hasInfoNotice();
	}

Here what I've done is added a constructor to the Mixin class. It has the same parameters of an existing constructor in the target class, and is annotated as a @Constructor. When the mixin processes this class, it would then find a constructor with a matching signature and change its access level to something equal or above that of this constructor.

Classes intended to extend the target class would then be written to extend from this one and have their superclass swapped out at runtime. One tiny caveat in this, though, is that any members the subclass accesses would also have to be shadowed in the Mixin.

With these two combined, there shouldn't be any need to use access transformers at all. These are just my ideas for how it could work. Feedback is, of course, welcome.

**Comment by Mumfrey** [comment]
This seems like an insanely complicated way of just achieving what you can already do with a static `@Accessor` method in Java 8+ mixins? Or am I misunderstanding your use case? For example like [this example](http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/client/java/com/mumfrey/liteloader/client/mixin/IKeyBinding.java)

> The second limitation I found is relating to constructors. Specifically, you can't extend a class where all of its contructors are private.

Correct, there is no use-case for this.

**Comment by Sollace** [comment]
> This seems like an insanely complicated way of just achieving what you can already do with a static @Accessor method in Java 8+ mixins? Or am I misunderstanding your use case? For example like this example
The wiki specifically said that your example wouldn't work though. I don't know if that's changed since, but it said you'd have no way to call that method at all because it has to be called on the destination class. They recommended that any methods you do add all be declared as private, which kind of defeats the purpose.

My use case is like this:
- CREATIVE_TAB_ARRAY is defined as "public static final CreativeTabs[]" in its source class
I can read from it but there's no way to write to it, so I need some way to make it mutable and, because it's static, the method to set it would ideally have to static as well. The only other way is to fudge it by going through and instance of the class, but that's a bit of a kludge.

> also putting two issues into one issue is just unhelpful.
Sorry~ I didn't think of that until after I created the issue. I can move it out to a separate one.

>there is no use-case for this,
I wouldn't be bringing it up if that were the case. <see net.minecraft.world.WorldType>Currently Blazeloader is using access transforms to get around this, but I want to try and move everything to using mixins so I don't have to run gradle, the transformer, and gradle again before developing.

**Comment by Mumfrey** [comment]
> My use case is like this:
> CREATIVE_TAB_ARRAY is defined as "public static final CreativeTabs[]" in its source class
> 
> I can read from it but there's no way to write to it, so I need some way to make it mutable and, because it's static, the method to set it would ideally have to static as well. The only other way is to fudge it by going through and instance of the class, but that's a bit of a kludge.

Making a `public static final` member mutable in any way other than allowing it to be changed at initialisation time is a bad idea. There are fundamental reasons I'm opposed to access transformers in general and these stem from *contractual assumptions* made both by the compiler and the JVM which mean that certain types of transformation are inherently dangerous to make at runtime. To take a stupid example to make the point:

```java
private static final int SOME_CONSTANT = 3;
```

Cannot be made `public` and non-final without some knock-on effects, this is because the integer value will almost certainly have been inlined by the compiler, and even though the member will still exist, and making it `public` has no ill effects, making it non-final would have the (non-obvious) effect that the value wouldn't be changed in places it is used in the owning class. For reference types this is obviously different, my point is that understanding fundamentally how the compiler and the runtime treat `final` is vital in responsible use of access transformation.

The JVM makes other assumptions about `public static final` members, for example allowing values to be cached locally to threads (though this is largely true of any variable which is not `volatile`) but the point is that the JVM will make assumptions about what it can do with those references, and it's why you cannot alter `public static final` members in any meaningful way using only reflection, you *have* to dig into `Unsafe` to make those changes and even then, chances are those changes will be ignored.

The point is that the `final` has semantic meaning far beyond "cannot be changed" because the "cannot be changed" contract has some instrinsic implications which extend far beyond the simple fact of immutability.

This means that you can alter `public static` members in two ways:

* Use a transformer to transform the access and remove the `final`, this means that from the very start the field is known to be mutable and none of the runtime problems occur. Eg. you need an "access transformer"
* Leave the access alone but just change how the field is initialised. You can already do this easily with mixin.
* Leave the access alone but modify the field anyway - this falls foul of the same problems as above, where you cannot guarantee that the change will be "seen" by any part of the JVM which has assumed it's safe to cache the value for performance reasons.

This boils your choices down to "modify the field at initialisation time" and "use an access transformer", there *are* no other choices. Since I don't wish to put any access transformation facilities into mixin, and the other function already exists, I don't see that there's a feature request here.

> I wouldn't be bringing it up if that were the case. Currently Blazeloader is using access transforms to get around this, but I want to try and move everything to using mixins so I don't have to run gradle, the transformer, and gradle again before developing.

**Fair warning: if you do this again and try to cram two issues into one ticket, I'm just going to close it and ask you to open two issues. Tickets should discuss one issue because otherwise it is utterly impossible to be able to close a ticket with a commit, track progress on a specific issue, etc. _Do not do this, this is not how GitHub issues work, this is not a discussion forum_.** I'm being lenient because this is your first ticket.

I really dislike access transformers in general and see them as a huge anti-pattern, this is why they are not supported in LiteLoader and will not be supported in Mixin. However as you have correctly observed, Mixin *does* provide mechanisms for working around some of the limitations of private members, but always does so in an *additive* way (eg. adding accessors) and not by brute-force changing of access flags. This basically makes accessors parallel to getting/setting fields and calling members with reflection, but in a performant and type-safe way.

I think you misconstrued my comment:

> there is no use-case for this,

as being "nobody wants to do this", when what I meant was "there is no sensible way to use this".

If a class is `final` (either explicitly, by declaring with the `final` keyword, or implicitly by having all constructors be private), then that attribute is part of the class's external contract and it should not be subclassed. Mixins provide you with unique ways to *extend the class from within* by adding new functionality and contract, however the `final` nature can only be overcome by using - you guessed it - access transformers, which I won't add to Mixin.

Both of your feature requests effectively are asking for features to replace things that can be achieved with access transformers, and that's just outside the purview of Mixin's feature set. Mixin is never meant to be a drop in replacement for access transformers, it's designed to make you find *better* solutions that the brute-force approach that access transformers employ.

To take some samples from your first post and put them in context:

> I have a scenario where I need to be able to overwrite CreativeTabs.CREATIVE_TAB_ARRAY. The original is public-static-final. Trying to do that with the current system (though I have no idea if this will actually workd) becomes a bit of a mess, and involves overwriting the original field which has obvious issues.
> 
> ```
> public interface ICreativeTabs {
> 	//Inject an instance setter
> 	public void impl$setCreativeTabsArray(CreativeTabs[] tabs);
> 	
> 	//Expose a static setter ducked through an existing instance
> 	public static void setCreativeTabsArray(CreativeTabs[] tabs) {
> 		((ICreativeTabs)CreativeTabs.BREWING).impl$setCreativeTabsArray(tabs);
> 	}
> }
> ```
> ```
> @Mixin(CreativeTabs.class)
> public abstract class MCreativeTabs implements ICreativeTabs {
> 	//Overwrite(?) the original field
> 	public static CreativeTabs[] CREATIVE_TAB_ARRAY = new CreativeTabs[12];
> 	
> 	//Implement the interface
> 	public void impl$setCreativeTabsArray(CreativeTabs[] tabs) {
> 		CREATIVE_TAB_ARRAY = tabs;
> 	}
> }
> ```
Here, you're (in an extremely long-winded way) asking for Mixin to **access transform the field for you**. In your example, the field would need to be annotated with `@Shadow` to connect it (obfuscation wise) to the target field, your `@Shadow` can of course be `@Final` so I think you're misunderstanding what your code does. This part:

```java
public static CreativeTabs[] CREATIVE_TAB_ARRAY = new CreativeTabs[12];
```

is **two distinct actions in Java**, the part to the left of the equals is the field declaration. The part to the right is the *field initialiser*, which Mixin will add to the target class. You don't need to "overwrite" the field, you just need to declare it as a shadow and inject your new initialiser. The code you've written will work absolutely fine, but your new initialiser will be appended (that's great) and your setter will likely cause weird shit to happen because the `final` modifier is still there on the target field and so parts of the runtime will cache it. This means that **you still need the access transformer**.

Likewise:

> The second limitation I found is relating to constructors. Specifically, you can't extend a class where all of its contructors are private.

Yes, exactly. There's a good reason for that, and again you're asking for me to add access transformers, which I will not. Come up with a better solution (eg. mix in extra functionality into the final class) instead of extending it.

> Here what I've done is added a constructor to the Mixin class. It has the same parameters of an existing constructor in the target class, and is annotated as a @constructor. When the mixin processes this class, it would then find a constructor with a matching signature and change its access level to something equal or above that of this constructor.

Here you explicitly ask for access transformation.

It's clear what you're asking for is access transformers, so really your ticket title is a red herring. I'm not going to add access transformers when **A** I hate them and **B** they're going to be supported natively in the Java 9 modlaucher anyway. Closing this ticket.

**Comment by Sollace** [comment]
Okay, well thanks for explaining it all, and sorry for wasting your time.

**Comment by Mumfrey** [comment]
It's not a waste of time if you get something out of it, it's always worth having a discussion.

Some notes for next time:

* One issue per issue, it's impossible to track multiple feature requests/bugs/questions if they are asked in one ticket. Whilst it might seem frivolous, like I said this is not a forum and it's infinitely easier to manage that way.
* If you want to ask a question, go ahead. Rather than worrying about formulating an entire solution to a perceived problem, ask the question first because there may already exist functionality to solve your problem and/or a solution to the problem may be out of scope. Both were true in this case.

**Comment by Sollace** [comment]
Yeah. I feel really silly now. I dove right into "how can I make something _really cool_ to add to this" and didn't think there was any room to ask for help. A lot of what was done with ATs could already be replaced with Mixins. The number got cut from ~12 to now 2, plus one reflection call to instantiate new objects:

    Constr<WorldType> worldTypeConstructor = Reflect.lookupConstructor(...);
    WorldType result = worldTypeConstructor.call(id, name, version);

(Couldn't this be replaced by an Invoker though?)

**Comment by Mumfrey** [comment]
Invokers can't (currently) invoke constructors, though it's a sensible addition and I would accept it as a feature request. Calling a constructor is more than just a regular method call because internally it's actually two steps: create the object using the `NEW` opcode and then ctor is called on the newly created object, and invokers don't currently have a generator which supports this, though it wouldn't be difficult to add one.

**Comment by Sollace** [comment]
Okay, that'd be perfect!

Shall I make an issue out of that so it can be tracked?

**Comment by Mumfrey** [comment]
No it's fine it's already on my mind to add anyway, I'm going to be away next week at the paris games week so I'll take a look at it when I get back.

**Comment by Pannoniae** [comment]
Can I ask about what is wrong with ATs? I searched everywhere, and there's been no mention of it. I know what is that, and I don't see the problem. Can you please explain? ;)

**Comment by Sollace** [comment]
@Pannoniae IIRC I recently discovered that Liteloader uses some TSs to remove the final modifier from the fields in `Blocks` and `Items`.

Working in forge, and I have to resort to _this_ [monstrocity](https://github.com/Sollace/Unicopia/blob/675cea57b8135a6c6efd87e5a1477975968f0768/src/main/java/com/minelittlepony/unicopia/forgebullshit/RegistryLockSpinner.java#L73).
