### ISSUE TITLE
Allow @Overwrite to work like @Inject

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#22]
There are a few cases where we want to replace some existing bytecode, but not all of it. By adding an optional @Inject type parameter to @Overwrite along with a specifier for how many instructions we would want to overwrite, this situation can be handled without duplication of entire methods, or confusing blocks of code that null out other blocks of code to get the features of @Inject. 

I'm planning to add this myself, but I figured I would see if there was some strong opposition before I got started with this.

**Comment by Mumfrey** [comment]
> how many instructions we would want to overwrite

This on its own makes this utterly no-go. There are plans for block replacement injections which would address this use case, however the implementation of these is quite complicated and needs to be tackled alone.

If you want to do ASM-y things, write a transformer and do them with ASM, but the aim of mixins is and always will be to completely decouple transformations from having to understand bytecode. Injections already come too close to the line really but there's no other way and they're also fail-safe in that a bad declaration will only lead to a failure to inject or at worst injecting in the wrong place, and will never corrupt the actual target.

This type of thing has been discussed over and over and I have not rejected block injections in any way, shape or form. However, I **absolutely will not** allow some half-baked, shortcut approach. It'll be done and done well, or not done at all.

> I'm planning to add this myself, but I figured I would see if there was some strong opposition before I got started with this.

Since this is something of a personal project I'd much prefer that pull requests be restricted to bug fixes or simple changes, entirely new features are not what I'm looking for.

**Comment by modwizcode** [comment]
If you wish to think of this as a personal project that's fine. But it's still part of the larger SpongeProject, which I'm perfectly capable of contributing to, don't attack my ability as a developer. Closing something without any active discourse on IRC or through the issue beside a brief explanation is not fair to progress. My plan to work on this is because having one person (you) do all the work causes it to stall when you're busy or unavailable. 

The normal number of instructions to overwrite is one, just like @Inject has a by specifier, this would need a similar extendable variable. 

If there are plans for block replacement injections, that is what this is, it seems inappropriate to put that in @Inject which has extra code to prevent accidental (or purposeful) overwriting.

Please discuss further on IRC.

**Comment by Mumfrey** [comment]
It's been extensively discussed, we were even discussing it last night. Happy to discuss more but you're not on IRC right now. I didn't close *this* issue without discussion because the wider issue is invalid, but because *this specific issue* you've proposed is invalid and doesn't really need any further discussion.

To clarify: `@Inject` does not *replace* **any** code, that's why it's "safe". It's designed to be completely stack- and local- neutral. The thing you're proposing is *not* stack/local-neutral and does not fit with the `@Inject` model at all.

Whilst Sponge is using this project, it's still a very personal project for me and that doesn't say anything about your capability as developer or anything like that, so don't take it as an attack because it's not meant as one in the slightest.

Happy to discuss on IRC when you get online.
