### ISSUE TITLE
Mixin bootstrap loading in the wrong order

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Mixin#227]
@Zidane asked me to post this.  We had an unusual instance where Mixin bootstrapping should have taken place within the almura.jar but instead MalisisCore loaded it instead.

Log:  https://gist.github.com/Dockter/97fe3513d192088dd19cfa326cf18f23

Zidane was confused if Almura's was asked to start first by did Malisis start before Almura's did.  This error was not immediately re-producible.

**Comment by Mumfrey** [comment]
It's not so much "started first" as an artefact of the interaction between FML and Launchwrapper. The coremod jars get injected by FML and the tweaker names get queued for Launchwrapper to process on the next pass (tweakers get spun up by launchwrapper but the jars are added to the classpath by FML). This leads to an irritating kinda-sorta-but-not-really nondeterministic behaviour with who is really gonna get bootstrapped first and which jar is going to end up being the candidate for loading the actual mixin classes.

This whole thing is the reason I emit the owner jar in the banner message, because otherwise it's a pain in the arse to determine where mixin is loading from definitively.

Really the solution to this lies in changes which are incoming in Forge to properly support the jar-in-jar packaging that will basically make this whole situation go away (in the short term) because packed dependencies can be reliably enumerated for version and only the latest version will "win" the deployment war. In the longer term, this all goes away because of ModLauncher.

There aren't any immediate solutions to this which aren't ugly as hell (eg. creating hybrid jars) but then you end up invalidating the jar signatures.

I can't propose a solution to this in mixin itself because this is a characteristic of the environment more than it is an intrinsic behaviour of mixin. Possibly all I could offer is somehow detecting this situation and emitting a more useful crash?
