### ISSUE TITLE
Running Mixins on mod classes

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Mixin#23]
I currently have a situation where i would like to run a mixin on a mod, but the current setup seems to run mixins as they are loaded, so this causes a class not found because it runs before the class is actually loaded,

is there a way to run a mixin after a mod is loaded?

**Comment by Mumfrey** [comment]
Mixins are never "run". A mixin is **applied** to its target classes on **class load**, there is *no* way around this because it's an intrinsic feature of transformers - you can only transform a class when it is loaded.

I have no idea what you're trying to describe but it makes no sense whatsoever because there is absolutely no physical, possible, conceivable way that a mixin could "run" (whatever you mean by that) *after* something you're trying to transform is loaded, because by then you can't transform it!

I suggest you explain further on IRC when I get home a couple of hours.
