### ISSUE TITLE
Unexpected (Wrong?) Injection Location

### ISSUE THREAD

**Issue by Desetude** [SpongePowered/Mixin#230]
Mixin: 0.7.4-SNAPSHOT (as depended on by SpongeCommon)

I have the following mixin: https://gist.github.com/Desetude/1a7462fecdeac91c8e13ee65ccef4594.

With this mixin, the following class (decompiled) https://gist.github.com/Desetude/aae68b852dbe7d2fd1a656f1b7feff59 is exported. 

onBreedFeed is injected into the location I targetted (L132), however onAgeFeed is injected into the locations at: L133 and L140. As onAgeFeed's Slice is from isChild() to ageUp(...), it should only be injected into the location at L140.

**Comment by Mumfrey** [comment]
I don't see anything wrong with the injection itself looking over it, so it would seem to be a bug. I will take a look into it and see what's going on.

**Comment by Barteks2x** [comment]
I'm not sure if that matters, but in the bytecode, isChild and ageUp are invoked on EntityAnimal, not EntityAgeable (`INVOKEVIRTUAL net/minecraft/entity/passive/EntityAnimal.ageUp (IZ)V`). Does mixin actually handle that case?

**Comment by Mumfrey** [comment]
I noticed that too, but honestly if the slice is invalid then the behaviour should be to either *report* the invalid slice or select **no** nodes, so I'd still consider it a bug either way, since the behaviour isn't what is expected.

**Comment by Desetude** [comment]
@Barteks2x Oh thanks, I didn't see that, I just got the target from IntelliJ minecraft-dev.

**Comment by Mumfrey** [comment]
As I mentioned above, I still consider the behaviour a bug since if the slice is wrong then really it should report that or inject no nodes. Maybe report a related bug over at [minecraft-dev/MinecraftDev](https://github.com/minecraft-dev/MinecraftDev) if it's that which was giving you the wrong target for the invocation.

**Comment by Mumfrey** [comment]
So it turns out the issue was I wasn't differentiating between a slice endpoint being *unspecified* (eg when just specifying `from` but not `to`) and an endpoint being *specified* but not actually succeeding.

I have adjusted the behaviour of slice matching so that in the situation that a slice endpoint is specified but doesn't match any nodes, the slice will be zero-sized (causing any injectors using the slice to fail) and will raise a warning in the logs when debug verbose is enabled, this should allow developers to easily spot the issue at development time.
