### ISSUE TITLE
ModifyVariable does not warn when handler signature is invalid

### ISSUE THREAD

**Issue by DaMatrix** [SpongePowered/Mixin#232]
I'm trying to modify the `x`, `y` and `z` arguments of `Entity#move` at HEAD. I can't use ModifyArgs because that needs a method to inject at. So I tried this somewhat hacky code:

https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/aae7645fd30f1da5f00ba86548a2b1efaaa3424d/src/main/java/valkyrienwarfare/mixin/entity/MixinEntityIntrinsic.java#L51-L86

In theory, it works. In practice, I get this:

https://pastebin.com/suQSH5hU

Any help is much appreciated. Thanks!

**Comment by Mumfrey** [comment]
Arg, ASM and stack map frames. I'll look into that.

**Comment by Mumfrey** [comment]
Okay so I've looked into this and there are two problems:

* Your code is wrong
* My code doesn't warn you when your code is wrong.

Of the injectors you defined, only one was actually injecting, and wasn't actually the right thing. The correct injectors look like this:

```java
@ModifyVariable(method = "move",
    at = @At("HEAD"),
    ordinal = 0
)
public double changeXArgAndInitLocals(double dx) {
    return dx;
}

@ModifyVariable(method = "move",
    at = @At("HEAD"),
    ordinal = 1
)
public double changeYArg(double dy) {
    return dy;
}

@ModifyVariable(method = "move",
    at = @At("HEAD"),
    ordinal = 2
)
public double changeZArg(double dz) {
    return dz;
}
```

Note the use of `ordinal` instead of `index`. The `index` discriminator is used to point to an explicit position in the locals, whereas `ordinal` points to an offset within variables of the same type. So in this case the `ordinal`s of the 3 doubles are 2, 4 and 6 (because doubles occupy two "slots" in memory). The `ordinal` of the doubles is 0, 1, 2 because the ordinal numbering starts at zero for each type and ignores spacing. In general `ordinal` is more robust than `index`.

You can always determine the ordinals/indices by simply setting the `print` argument on the discriminator to `true`, yielding the following output:

```
/************************************************************************************/
/*         Target Class : net.minecraft.entity.Entity                               */
/*        Target Method : move                                                      */
/*        Callback Name : localvar$changeXArgAndInitLocals$zbd000                   */
/*         Capture Type : double                                                    */
/*          Instruction : LabelNode UNKNOWN                                         */
/************************************************************************************/
/*           Match mode : EXPLICIT (match by criteria)                              */
/*        Match ordinal : 0                                                         */
/*          Match index : any                                                       */
/*        Match name(s) : any                                                       */
/*            Args only : false                                                     */
/************************************************************************************/
/* INDEX  ORDINAL                            TYPE  NAME                   CANDIDATE */
/* [  1]    [  0]                       MoverType  arg0                   -         */
/* [  2]    [  0]                          double  arg1                   YES       */
/* [  3]                                    <top>                                   */
/* [  4]    [  1]                          double  arg2                   YES       */
/* [  5]                                    <top>                                   */
/* [  6]    [  2]                          double  arg3                   YES       */
/* [  7]                                    <top>                                   */
/* [  8]                                        -                                   */

... etc.
```

Notice that `index` increases for every slot in the local table, but `ordinal` starts at zero and increases by one for each *type* of variable.

The actual problem is that your method signature was wrong, per [the documentation for `@ModifyVariable`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/injection/ModifyVariable.html):

> `ModifyVariable` callbacks should always take one argument of the type to capture and return the same type. For example a `ModifyVariable` for a local of type `String` should have the signature:
>
>     private String methodName(String variable) { ...

But in your original code the method signatures had all of the target method arguments present. So the **actual** bug here is that Mixin was not warning you that the handler signature was incorrect, and that's a pretty serious bug because the injector was proceeding anyway with the incorrect handler, and leading to unrunnable code.

I will add detection for this to rectify the issue going forward, but for the moment if you fix your injector declarations then everything should work as intended.

**Comment by DaMatrix** [comment]
Alright, thanks!
