### ISSUE TITLE
Mixin target owner Type check is incorrect

### ISSUE THREAD

**Issue by Foghrye4** [SpongePowered/Mixin#242]
Apparently owner name should start with "L" and ends with ";"
https://github.com/SpongePowered/Mixin/blob/2f63e40255f81a9f69b15d7b15e464bcfe0705ea/src/main/java/org/spongepowered/asm/mixin/injection/struct/MemberInfo.java#L682

In next line of code this "L" is stripped from owner string.
Mixin use a stupid check which detects if owner type class descriptor gained via Type.getType(String) is a same as owner string itself:
https://github.com/SpongePowered/Mixin/blob/2f63e40255f81a9f69b15d7b15e464bcfe0705ea/src/main/java/org/spongepowered/asm/mixin/injection/struct/MemberInfo.java#L447

And thats how this check is done:
https://pastebin.com/FwHRzuaA

Since every class name usually starts with small letter (for example "net/minecraft..." and so on) this check results in Type with number 11. This check is ridiculous.

**Comment by Mumfrey** [comment]
Even though the code in question does not actually do what it's supposed to, it was originally added for a purpose and that purpose is not fulfilled by either of the proposed "fix" PRs referencing this issue. One simply removes the check (which doesn't catch the original intended problem the check was intended to catch) and one fixes the "bug" without actually fixing the check.

Whilst I appreciate this being brought to my attention to fix it, please consider using less nettling terminology than "stupid" next time. We all make mistakes and code which doesn't do what it's supposed to is sometimes just accidental derp pure and simple.

**Comment by Foghrye4** [comment]
Ok, sorry.

**Comment by Mumfrey** [comment]
No worries. I'll try and think of a better way to detect the issue @gabizou was originally having with badly formatted descriptors. The reason this code was added was because it was possible to supply descriptors which passed the regex check but failed when handed into `Type`. This does work for a small subset of descriptors but as you have pointed out, in most cases it doesn't actually work as intended and is kind of redundant and it's not even really obvious why it's doing what it's doing.

I will devise a better check for the invalid descriptors in question and push up a fix soon.
