### ISSUE TITLE
Provide finer-grained control over generic parameter assignment

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#254]
Let's say we have two interfaces, each with a type parameters `T`:

```java
public interface TargetInterface<T>
```

```java
public interface AddedInterface<T>
```

and an interface mixin which makes `TargetInterface` extend `AddedInterface`:

```java
@Mixin(TargetInterface.class)
public interface MixinTargetInterface<T> extends AddedInterface<T>
```

After applying the mixin, `TargetInterface` should look like this:

```java
public interface TargetInterface<T> extends AddedInterface<T>
```

However, Mixin's logic for merging generic signatures will cause a new type parameter to be created, causing `TargetInterface` to look like this:

```java
public interface TargetInterface<T, U> extends AddedInterface<U>
```

This is a breaking change to the generic signature, which now has two parameters instead of one. Normally, this isn't an issue, since the JVM ignores these generic signatures at runtime. However, libraries like the Kotlin reflection API may actually check thse signatures at runtime, and become confused by the mismatch (other classes will reference `TargetInterface<T>` in their generic signatures). 

It would be helpful if Mixin provided a controlled way to turn off this merging behavior, allowing the user to indicate that they really do want the same generic parameter used multiple times in the final signature.

**Comment by Mumfrey** [comment]
This is related to #169 and boils down to needing to not just merge generic signatures based on symbols but also on type. It turns out that this is quite complicated, though this scenario is simpler it still involves a lot of additional scaffolding which is also needed by the other problem.

> It would be helpful if Mixin provided a controlled way to turn off this merging behavior, allowing the user to indicate that they really do want the same generic parameter used multiple times in the final signature.

I don't undertsand. So you're saying a way to force type tokens to be merged without checking the bounds at all?

**Comment by Zidane** [comment]
Here is another case of fun issues with kotlin:

https://github.com/SpongePowered/SpongeCommon/issues/1845

**Comment by Mumfrey** [comment]
> Mixin could avoid changing any generic parameters shared between TargetInterface (in this case, T) and any other interfaces in the same signature.

@Aaron1011 I see, that should be possible in a naïve way as long as the type parameters are identical. In [ClassSignature::merge javadoc]() I explicitly say:

> No attempt is made to combine formal type parameters, this method merely ensures that parameters do not overlap.

Basically some level of merging, even if it's only very basic, is what you're asking for? That should be possible. However bear in mind that this means that your situation is only fixed in the case that the type parameters are **literally identical** and no other cases.

**Comment by Aaron1011** [comment]
It would also be helpful if Mixin were to log a message when it makes a breaking change to a generic signature (e.g. adding another generic parameter). This would make it much easier to debug this kind of mod compatibility issue in the future.

**Comment by Mumfrey** [comment]
Having looked into this issue some more, I think my original approach is the only one that works and turning off class signature merging when it's either not needed or deliberately excluded is the only sensible way to do this, barring some sort of mapping being created for formal type parameters in the base interfaces.

The purpose behind merging the signatures in the first place was to allow decompilation to succeed; there was no need for the signatures to "make sense" in the traditional way since they were only used in the direct context of the class and then only by the decompiler in order to compute formal types for otherwise generic methods.

The issue basically boils down to there being no intrinsic intent or purpose associated with a particular formal type parameter, and though it may be easy for a human to understand the relationships, the computer doesn't have the necessary contextual information to make informed decisions.

Consider a class `Foo<V>` which implements `Callable<V>`. A Mixin is added which implements `Comparable<T>` and the relevant `compareTo(T other)` is added by the mixin. The new signature of the class after merging is `Foo<V, T> : Callable<V>, Comparable<T>`. This is is the situation which breaks Kotlin, though it provides a very useful context for the decompiler.

The formal parameters `V` and `T` *can* be merged because they have the same bound, however we don't know that this merging is sane (it's not in this case but it might be in others).

This means that there are two options:

* Indicate in some way which formal type parameters can be merged, this preserves both use cases, but puts a burden on the developer to decorage all situations where merging is possible and risk things breaking in situations where the mappings get out of sync.
* Only enable signature merging when the decompiler is active, this is more robust and possibly saves some wasted effort as well in situations where the signature merging is redundant.
