### ISSUE TITLE
Support working around projects that won't support Mixin

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#255]
Some projects like [AstralSorcery](https://github.com/HellFirePvP/AstralSorcery/issues/644#issuecomment-383394696) won't address any issues that occur with Sponge or other Mixin-using projects. It would be helpful if Mixin provided a way to exclude certain class transformers from being run twice (once during startup, and once when the class is actually loaded) without needing to modify the transformer.

**Comment by gabizou** [comment]
If I remember correctly, we ended up supporting transformers if they used `@Resource` as a class annotation. Not sure if that system has been advocated yet, but it's something simple that is available from the JVM itself.

**Comment by Mumfrey** [comment]
@gabizou that contravenes the premise of the above request, this specificially covers the situation where the mod author isn't going to cooperate. Though it looks like they actually [fixed their issue](https://github.com/HellFirePvP/AstralSorcery/commit/7a0e16406690b136df04407f2055cccaea60127f) so that the transformer contract is not being violated anyway.

However if a transformer doesn't want to exlcude itself using the `@Resource` method there is no way for Mixin to detect this so you will have to exclude them from delegation manually in the consumer.

The consumer can call

```java
MixinEnvironment.getDefaultEnvironment().addTransformerExclusion(transformerName)
```

and I don't really think there's any more that can be reasonably done to work around this. If people are going to violate the transformer contract and won't cooperate to remove the violation (which in this case and most others they have) then Mixin cannot detect and enforce this any more than it already does (with re-entrance).

Closing as invalid.
