### ISSUE TITLE
Reorder version history in readme

### ISSUE THREAD

**Issue by DemonWav** [SpongePowered/Mixin#261]
Yeah I expect to be murdered for this.

But seriously, the release order goes from oldest to newest, so you have to scroll all the way down to the bottom of the page to get information about the most recent versions - information that is likely to be a lot more relevant and useful to someone other than the first versions.

**Comment by Mumfrey** [comment]
Honestly the only reason it's still like this is that I didn't honestly think anyone would read it and appending to the bottom just became a habit. I mainly just wanted to provide a list which could be grepped for certain features so that people wanting to put `minVer` entries in their configs could look up the most recent feature they're using and see like "oh, version foo.bar was when this was added". I'm really not that hung up on the order so I guess I can flip it around.
