### ISSUE TITLE
'remapRefMap' option causes BeforeInvoke ordinals to be wrong

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#266]
When the `remapRefMap` option is set (which happens automatically in development), all `BeforeInvoke` injectors [will attempt to search for a 'permissive target' if searching for the normal @At#target fails](https://github.com/SpongePowered/Mixin/blob/81a22a4f1d1cf59089bed40cdab4913860340c22/src/main/java/org/spongepowered/asm/mixin/injection/points/BeforeInvoke.java#L128).

However, since the 'permissive' target has `null` descriptor, more instructions will be considered by the [`target.matches` block](https://github.com/SpongePowered/Mixin/blob/81a22a4f1d1cf59089bed40cdab4913860340c22/src/main/java/org/spongepowered/asm/mixin/injection/points/BeforeInvoke.java#L149). Since the `ordinal` is incremented each time through the block, a different instruction may be picked using the permissive target than would have been picked with the normal target.

The end result is that, under certain circumstances, a `BeforeInvoke` injector will pick different instructions depending on whether or not `remapRefMap` is set. This leads to confusing issues such as https://github.com/SpongePowered/SpongeForge/issues/2244, where an injector stops working in production despite the fact that no relevant bytecode changes have occured.

**Comment by Mumfrey** [comment]
Hm, that is *sort* of working as intended, but obviously having an unintended side-effect. I assume that basically this happens when the original injector is actually wrong and therefore only succeeds because of the permissive search, which is not what is intended.

I guess a sensible improvement would be to make the following changes:

* Don't use permissive search when a refmap doesn't actually exist for the parent config. This would mean refmap remapping would continue to work for deps imported into a dev workspace, but would disable it for the project itself.
* Log a `WARN` level message when a permissive search matches more than once, so that it's clear what's going on.

Thoughts?

**Comment by Mumfrey** [comment]
As a corollary observation, this is also why slices are preferable to ordinals wherever possible.

**Comment by Aaron1011** [comment]
@Mumfrey: Both of those changes sound good to me. The second one especially would have made debugging the SpongeForge issue much easier.

I also forgot to mention - I actually experienced this issue while using a slice. The `to` target was a `BeforeInvoke` injector with an ordinal - necessary because of the long and complex method that was being modified.
