### ISSUE TITLE
Elide accessors when the underlying field is package-visible

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/Mixin#269]
Currently, it's not possible to use a package-private field or method from another class (or private field from an inner class) without having a mixin that adds a getter in the other class.

But that's unnecessary overhead since the code should have access to the other field once it's mixed in and its package is changed. A compile-time only access transformer doesn't work in all cases, for example when the target field belongs to another mod or forge. Instead, the shadow annotation could be extended with a target parameter:

    package mypackage;

    import otherpackage.SomeClass;

    @Mixin(SomeClass.class)
    public class MixinSomeClass {
        @Shadow(target = "Lotherpackage/SomeOtherClass;someStaticField:I") private static int SomeOtherClass_someStaticField;

        public void someMethod() {
                SomeOtherClass_someStaticField *= 2; // Converted to SomeOtherClass.someStaticField *= 2 by Mixin
                ((SomeOtherClassFields) (Object) instanceOfOtherClass).someField  *= 2; // Converted to instanceOfOtherClass.someField *= 2 by Mixin
        }
    }

    class SomeOtherClassFields {
        @Shadow(target = "Lotherpackage/SomeOtherClass;someField:I") public static int someField;
    }

Mixin could check that the code is going to be correct once mixed in to avoid an illegal access exception, and check that the type matches.

**Comment by Mumfrey** [comment]
Whilst I agree this is desirable functionality, I fundamentally disagree with your proposed solution. Adding a shadow member that exists in another class into a mixin is horrible for a number of reasons. The one thing everyone seems to forget is that all of Mixin is written with multi-target support and the assumptions for single-target are immediately invalidated given the flexibility of supporting multiple targets in potentially different packages. It would be possible to make your solution work under some circumstances or under single-target but it's additional (unnecessary) restrictions which would be opaque to the author. Your proposed solutions is also ugly, on top of the other issues.

Thus I would definitely insist that declaring the shadow member in the Mixin for the desired target class is both consistent (eg. with the same semantics for supermixin) and also clear what's happening. The actual issue at that point is that the following code will compile but won't apply at runtime because referring to the mixin itself is not allowed:

```java
((MixinSomeOtherClass)(Object)instanceOfSomeOtherClass).someField;
```

Now obviously this is back to current functionality in terms of requiring the field to be then accessed via an accessor, which as you say is unnecessary overhead (though only a barely detectable amount).

I would propose then that under the following circumstances:

* A mixin is calling an accessor in a target class which was added by a mixin as an accessor method
* The underlying field is package-private and the mixin's target class (in context of current target) is the same as the accessor's owner (and thus the underlying target field is visible to the context target).

The call to the accessor is elided and replaced with a direct access of the field.

This solution allows mixins to be written in exactly the same way as at present but simply provides a minor performance improvement in situations when it's available. But allows the author to not worry about creating a lot of extremely ugly scaffolding to achieve an arguably fairly insignificant performance benefit.

This also has the benefit of keeping the current clarity of declaration and providing the performance benefit transparently, thus also retroactively applying this same boost to any other mixins which currently use accessors.

To be clear, this will only apply in situations where a accessor mixin getter is being called directly:

```java
value = ((IMixinSomeOtherClass)someOtherClassInstance).getSomeField()
```

becomes

```java
value = someOtherClassInstance.someField;
```

with the cast being elided and the method invocation being converted to a field access. Any other pattern, eg:

```java
IMixinSomeOtherClass foo = (IMixinSomeOtherClass)someOtherClassInstance;
myClass.someMethod(foo.getSomeField());
```

cannot be optimised because the cast is separated from the method call and thus the original target cannot be inflected.

This is **exactly the same** as this:

```java
SomeMixin self = (SomeMixin)(Object)this;
self.someMethod();
```

being **bad** versus the correct:

```java
((SomeMixin)(Object)this).someMethod();
```

because Mixin [already collapses such casts](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTargetContext.java#L637-L643) when they are inline and cannot collapse them in other situations.

**Comment by DemonWav** [comment]
I just feel the need to interject here and mention that I think this is ridiculous and a total non-issue. @Mumfrey shouldn't even waste the time to implement his proposed solution as far as I'm concerned.

There, I said it.

**Comment by Mumfrey** [comment]
> I just feel the need to interject here and mention that I think this is ridiculous and a total non-issue.

I assume you're referring to the fact that such accessor invocations are just JIT'd away in practice and thus in practice there is **no** performance gain to be had by eliding the calls in the bytecode? It honestly didn't cross my mind (embarrassingly) when writing the above reply that this is true.

> @Mumfrey shouldn't even waste the time to implement his proposed solution as far as I'm concerned.

I see what you're getting at. Basically for a net zero performance increase (and even in the situations where the elision actually does provide a performance increase, it's infinitesimally small, as mentioned above) it's actually **adding** the overhead of searching for these occurrences (which means maintaining the required metadata to do so, eg. decorating accessor members with the identity of the underlying field) and then replacing them. Basically achieving no performance gain for an actual performance impact, not counting the time required to actually develop that feature which could otherwise be spent on something useful.

Upon reconsideration, closing this as invalid because the actual cure is worse than the disease.
