### ISSUE TITLE
ModLauncher support for 1.13

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Mixin#271]
@cpw informed us that Forge 1.13 update will be replacing tweakers with the `modlauncher` system that you helped build. Any plans on updating mixin to support this in the near future? 

API for mixin to use is here
https://github.com/cpw/modlauncher/blob/master/src/api/java/cpw/mods/modlauncher/serviceapi/ILaunchPluginService.java

Thanks!

**Comment by Mumfrey** [comment]
I know, it's why the [entire surface area was refactored into service model](https://github.com/SpongePowered/Mixin/commit/d31ccf1220e31b875ab47a38c3d2ff6a05d961bf) last year. I've been planning for this for a while as you can see. I wasn't going to make an issue because its a fundamental project task which doesn't really need an issue to track it.

This isn't specifically for 1.13, this is mainly for Java 9 support, 1.13 is just when the transition is occurring.

**Comment by bloodmc** [comment]
OK thanks! I'll close ticket then =)

**Comment by Barteks2x** [comment]
Any updates on this? It's been almost a year and mixin is still the only thing I'm waiting for to start updating.
