### ISSUE TITLE
Allow injecting 'catch' block into method

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Mixin#274]
Sometimes, it's useful to be able add a 'try/catch' block to an existing method. Currently, the only way to accomplish this is to overwrite the method with a 'try' block placed around the original code.

This has all the downsides that come with Overwrites - it's incompatible with any other transformers that may have modified the method, and must be manually kept up-to-date as the target class changes.

It would be very useful if Mixin allows injecting a `catch` to a user-specified range of instructions. It could look something like that:

```java
@Catch(method = "some_target_method", slice = @Slice(from = @At("HEAD"), to = @At("RETURN"))
public void onIOException(IOException e) {
    e.printStackTrace()
}
```

**Comment by Mumfrey** [comment]
Already covered by EXIT and the associated issues. I have a working branch for it but obviously the problems which plagued EXIT basically still apply.

**Comment by gabizou** [comment]
I'm guessing the working branch is local? I didn't realize there was work being done on EXIT in this manner, this would definitely prove to be very useful, and while it would come at the cost of getting things to work to inject a catch essentially for a particular method call would be useful.

**Comment by Mumfrey** [comment]
End of last year was the last I looked at it. It needs a serious rethink because generating the code is pretty straightforward but the code needed when there are multiple exit points from a method violates the stack map validation so you can create "valid" code that the JVM chokes on.

Basically I originally thought it boiled down to "just wrap the whole method in a try/catch" but it's a more complicated than that if the method has a return value. What I have works fine for `void` methods and goes up in smoke any time there's a return value.

I mean possibly this is because EXIT does more than the suggested thing above here, because EXIT is looking to intercept the return value in all cases. Because all the issues boiled down to manipulations of the stack which weren't "allowed" (because a slot had to container different values for indistinguishable code paths). In particular EXIT has to cope with other injectors which manipulate the method and might cause it to return.

> I didn't realize there was work being done on EXIT in this manner,

Yes you did, you were the one who asked for it in the first place! And the code is on the dev server.

![](http://eq2.co.uk/pr/exitchat.png)

I'm obviously planning to revisit this, because it's a very useful feature, but it's just been on ice while dealing with a) real-world things that have been keeping me busy and b) other more important stuff which has come up in the mean time.
