### ISSUE TITLE
Classloader Restrictions in most recent SpongeForge builds

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Mixin#275]
Hello,
We are using SF: 3314 and we noticed the following:

https://gist.github.com/Dockter/7bd631029e1c2530d7dce41a6fdb70f4

@Zidane asked me to create an issue.  What is the restriction?

**Comment by Aaron1011** [comment]
This is an issue with MalisisCore - it's adding a transformer exclusion for its own Mixin classes. This (among other things) can prevent production jars from being used in a development environment.

**Comment by Mumfrey** [comment]
This is Mixin *telling you* about a problematic restriction, not imposing one. This message was added to fix #259 so that broken restrictions could be noticed and fixed.

> `@Zidane` asked me to create an issue. What is the restriction?

The restrictions in force are the ones in square brackets in the error message, in this case `PACKAGE_TRANSFORMER_EXCLUSION`, which indicates that the package is transformer-excluded.
