### ISSUE TITLE
No Precondition Or Propagation For Overriding Final Method In Target Superclass

### ISSUE THREAD

**Issue by InsomniaKitten** [SpongePowered/Mixin#293]
If a mixin declares a method with a signature identical to that of a method in the superclass of the target class, and that method is *final*, it will crash at class loader level with a `java.lang.VerifyError`. Although this could very well be considered a matter of common sense not to attempt this, it might be worth adding a precondition, or propagating the error with context of the mixin causing the error.

**Produced with Mixin version 0.7.11.3**

**Comment by DemonWav** [comment]
I think "don't" is a good answer here, but that could happen on accident between updates as well. Not that Mixin should support all versions of the same class or anything like that, but flexibility is a key feature here.

Maybe method name mangling could be used here to "fix" that at runtime? Not sure what downsides that would cause. My guess, though, is there's probably already either some way of handling this situation already, or documentation that already says to not do this somewhere.

**Comment by InsomniaKitten** [comment]
I feel the best solution to this would be my latter suggestion - propagating this internal error, providing context of the mixin class to be blamed for this crash. As stupid as it is for someone to attempt this (if not by mistake), it would still be beneficial to provide a blame rather than allow the class verifier to spit out its own error with no mixin context.

**Comment by gabizou** [comment]
I'd ultimately believe this to be an unintended side effect of your mixin and method naming structure. Case in point:

Sponge added some methods to a base class: `Entity` for sponge's usage and declared it final. That method can be named `foo()V`.

Another mod that extended `Entity` can make their own method called `foo()V` as well, not knowing that sponge adds a method called `foo()V` and when *that* mod class is class loaded, the class loader will throw a `VerifyError` as well. 

In this case, the problem doesn't lie with Mixins, because it's impossible for Mixins or Sponge for that matter to know that a *completely random mod, unbeknownst to the Sponge Team, has an exactly named same signature method to their mod class*. The fix here isn't so much something to be done with Mixin, but tossed as incompatibility fixes between the two mods.

The bigger issue here is that you're asking Mixin transformer to catch an **error**, not an **exception** for the class loader, which granted isn't in the contract of any transformer to handle. While the effort put in place to provide some sort of pointer about what Mixin can provide at that point is minimal, since Mixin may not even have transformed the class, I'd find it difficult to say that we can provide any more explicit information than the error provides from the class loader: Class B is overriding final method 1 from Class A. With that information, I don't feel Mixin can provide any more explicit information than that.

**Comment by Mumfrey** [comment]
> *@InsomniaKitten said* If a mixin declares a method with a signature identical to that of a method in the superclass of the target class, and that method is _final_, it will crash at class loader level with a `java.lang.VerifyError`. Although this could very well be considered a matter of common sense not to attempt this, it might be worth adding a precondition, or propagating the error with context of the mixin causing the error.

Yes, the key word in your issue is "**context**". As described in the documentation, in general Mixin is designed so that application of mixins is at best "do no harm" and at worst fail-fast. I would consider this a bug since a failure to fail-fast. Mixin can't do anything to address the problem, but it should fail at verification time with a useful error rather than letting a VerifyError pop up later. Really when a mixin is responsible for a crash this should be traceable back to the mixin so that the author or end user can understand and rectify the issue.

> *@gabizou said* In this case, the problem doesn't lie with Mixins, because it's impossible for Mixins or Sponge for that matter to know that a _completely random mod, unbeknownst to the Sponge Team, has an exactly named same signature method to their mod class_. The fix here isn't so much something to be done with Mixin, but tossed as incompatibility fixes between the two mods.

While this is true, the fact of the matter is that the VerifyError is cryptic and could (and should) be detected by Mixin and not allowed to propagate.

Of course in the instance that a mixin adds a method to a superclass and triggers a classloader error when a *subclass* is loaded with a conflict, unfortunately there's no way to deal with that. The solution is asymmetric but that doesn't mean that addressing the stated issue is not worthwhile.

**Comment by Mumfrey** [comment]
I'm going to consider this an enhancement (of detecting a problem) rather than a bug since it's not really a "bug" that I can "fix" in mixin, but an improvement of functionality where a code structure issue can be detected and reported.
