### ISSUE TITLE
Annotations allow for targets with spaces, but fail with refmaps

### ISSUE THREAD

**Issue by asiekierka** [SpongePowered/Mixin#296]
Fabric issue: https://github.com/FabricMC/Mixin/issues/1

In essence, the issue is as follows:

* The Mixin annotation processor sees target strings with whitespace characters as used,
* and are stored in the refmap .JSON as keys with whitespace characters,
* but [this line in MemberInfo](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/injection/struct/MemberInfo.java#L671) strips all whitespace characters *before* performing a refmap lookup!

The Fabric issue shows a reproducible example and comparison between a working and non-working @Inject. I'm opening the issue because I'm not sure which part of the issue the desirable fix should target.

**Comment by Mumfrey** [comment]
`MemberInfo` defines the contract for the string encoding of references, so the `ReferenceMapper` is actually the faulty component here since it should conform the keys in its map.

**Comment by asiekierka** [comment]
Should I look into this or leave it to you? If the issue comes down to ReferenceMapper is not enforcing the contract, it's not particularly urgent on our side.

**Comment by Mumfrey** [comment]
It's up to you really. I'm trying to get the 0.8 release sorted before I look at these more recent minor things because in some cases the classes in question have been moved around. At the end of the day it's easy to work around this by avoiding spaces in the references, so I'd say given the general lack of urgency I'd just triage it on the user end and then fixes can be rolled up after the major transition has been made.

I'm assuming the shift to modlauncher won't affect Fabric but some of the architectural changes might, I'm not sure.

**Comment by asiekierka** [comment]
>I'm assuming the shift to modlauncher won't affect Fabric but some of the architectural changes might, I'm not sure.

Don't worry about that. It probably won't, as we already moved away from Launchwrapper as a default and provide it only as a secondary solution.
