### ISSUE TITLE
Question: using ModifyArg with synthetic inner class constructors

### ISSUE THREAD

**Issue by InsomniaKitten** [SpongePowered/Mixin#300]
`@ModifyArg annotation on is targetting a non-method insn in net/minecraft/entity/mob/ZombieEntity::prepareEntityData(Lnet/minecraft/world/IWorld;Lnet/minecraft/world/LocalDifficulty;Lnet/minecraft/entity/SpawnType;Lnet/minecraft/entity/EntityData;Lnet/minecraft/nbt/CompoundTag;)Lnet/minecraft/entity/EntityData; in net/minecraft/entity/mob/ZombieEntity::modify$preventChildZombieSpawns$zzd000`

**Current version:** 0.7.11

Error produced in a [Fabric](https://github.com/FabricMC) environment.

Unless I'm mistaken, there is no reason for constructors to not be supported other than a possible oversight in the current implementation? The semantics of modifying arguments passed to a constructor invocation would be no different than modifying arguments passed to a normal method invocation, right?

**Comment by gabizou** [comment]
Could you provide the annotation in it's entirety? I can understand you might be using different mappings, but Sponge even has some [ModifyArg cases where we're modifying arguments in constructor calls](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityTrackerEntry.java#L133).

Also, do you have a stack trace?

**Comment by InsomniaKitten** [comment]
Here is the failing code: [InsomniaKitten/SimpleZombies:ZombieEntityMixin.java#L50-L59](https://github.com/InsomniaKitten/SimpleZombies/blob/cafccf408f633ac74ce750b3b1c93bd66eba7441/src/main/java/io/github/insomniakitten/simplezombies/mixin/ZombieEntityMixin.java#L50-L59)

And a stacktrace: [InsomniaKitten/f5937ba18d946483131e4c27b3960ca4](https://gist.github.com/InsomniaKitten/f5937ba18d946483131e4c27b3960ca4)

Apologies for not including the stacktrace in the original message.

**Comment by InsomniaKitten** [comment]
Oh, just looked at the code you linked. I didn't realise constructors were treated as regular invocations for a mixin target, considering there is `NEW`. I guess my issue is redundant then, unless additional support were to be added to support use of `NEW` too.

**Comment by InsomniaKitten** [comment]
For further context, this is where I am trying to inject:

![codeblock0](https://i.imgur.com/7mZT1og.png)

And this is the inner class:

![codeblock1](https://i.imgur.com/kqBcqO7.png)

**Comment by asiekierka** [comment]
Could you try with a non-Fabric environment? At least for a dev env without Fabric API, you should be able to just swap the latest Mixin build in with IDEA.

**Comment by asiekierka** [comment]
In general, please do not report Fabric environment issues in Sponge's repo. It's our duty to filter for my terrible coding first before they have to suffer.

**Comment by InsomniaKitten** [comment]
As far as I can tell - I did verify this as much as possible before reporting here - this is unrelated to Fabric and/or Fabric's fork of Mixin.

**Comment by asiekierka** [comment]
We've done some things which can mess up the entirety of Mixin, in particular the ASM 7.0 upgrade. Please test regardless, or - if you can't test - go through Fabric's issue tracker first. Seriously. I don't want to get a bad reputation among upstream for this.

**Comment by InsomniaKitten** [comment]
Tested with an official build of Mixin rather than Fabric's fork, and produced the same crash.

**Comment by Mumfrey** [comment]
Your second injection is almost correct. You have discovered one of Java's little dirty secrets.

*Non-`static` inner* classes don't look the same when compiled as when they're visible in the original Java code. This is because the inner class itself isn't really "inside" the containing class in any meaningful. Most of what makes a class "inner" in practice is just synthetic scaffolding added by the compiler to preserve the illusion of inner-ness. (*Synthetic* in this case meaning "added by the compiler not by the programmer").

In this simple example:

```java
class OuterClass {
    private int outerNumber = 0;

    class InnerClass {
        private int innerNumber;
        InnerClass(int initialValue) {
            this.innerNumber = initialValue;  // Instance field access
            OuterClass.this.outerNumber = 999; // Instance field on outer class access
        }
    }
    
    OuterClass() {
        InnerClass test = new InnerClass(123);
    }
}
```
Things are not as they seem because firstly `innerNumber` is private and we can magically access it from inside the inner class, even though the inner class doesn't seem to have any instance field which references the outer instance.

What's happening is that synthetic scaffolding is being added by the compiler and what we actually get looks like this when compiled (note I've used an imaginary `@Synthetic` annotation to show which parts are added by the compiler):

```java
class OuterClass {
    private int outerNumber = 0;

    OuterClass() {
        // Note that the instance is passed as the first argument, to
        // initialise the synthetic member in the "inner" class \/
        OuterClass$InnerClass test = new OuterClass$InnerClass(this, 123);
    }

    // The original field is private, but the compiler adds this synthetic accessor
    // with package-private access to allow the "inner" class to set the member
    @Synthetic static void setOuterNumber(OuterClass outer, int value) {
        outer.outerNumber = value;
    }
}

class OuterClass$InnerClass {
    @Synthetic private OuterClass outer;
    private int innerNumber;
    OuterClass$InnerClass(@Synthetic OuterClass outer, int initialValue) {
        this.outer = outer;
        this.innerNumber = initialValue;
        OuterClass.setOuterNumber(this.outer, 999);
    }
}
```

Note that I've given the synthetic fields and methods friendly names, normally access methods are named something like `access$0` and the outer field might be called something like `this$0`. Note that in this example the are no "closure-like" values, these also need to be passed to the constructor if there are any present.

So your new injector which targets the `<init>` method directly is correct, but has an incorrect signature because it's not taking into account the synthetic arguments added to the ctor. This is why it's usually a good idea to use [a tool](https://minecraftdev.org/) or *Bytecode Viewer* to grab the signatures directly out of the bytecode, rather than writing them by hand.

In your case, you can probably just omit the signature from the injector, alternatively you just need to correct the signature in your injection point to include the outer class reference which is passed to the constructor.

For additional (tangentially related) info: the `NEW` injection point can be used for callbacks and has special handling when used with a `@Redirect` in order to redirect an object construction to a factory method. Since `@ModifyArg` always operates on an invocation that is why you need to target the actual invocation of the initialiser rather than the `NEW` opcode itself.

**Comment by InsomniaKitten** [comment]
I figured it might be something related to the class being non-static, but was unsure of how to resolve it. I was able to resolve the issue with a stripped signature, as suggested:

`Lnet/minecraft/entity/mob/ZombieEntity$class_1644;<init>`

However, I am now curious why none of these worked, and produced the same exception as I last posted:

`Lnet/minecraft/entity/mob/ZombieEntity$class_1644;<init>(Lnet/minecraft/entity/mob/ZombieEntity;Z)V`
`Lnet/minecraft/entity/mob/ZombieEntity$class_1644;<init>(Ljava/lang/Object;Z)V`
`Lnet/minecraft/entity/mob/ZombieEntity$class_1644;<init>(ZLnet/minecraft/entity/mob/ZombieEntity;)V`
`Lnet/minecraft/entity/mob/ZombieEntity$class_1644;<init>(ZLjava/lang/Object;)V`

Looking at the class exported by Mixin, a third invalid(?) argument is being supplied?

![invalidArgument](https://i.imgur.com/73zxWF5.png)

And it also seems I have a new bug to report to the Minecraft Development plugin heh:

![invalidInspection](https://i.imgur.com/5A4bSiQ.png)

**Comment by Mumfrey** [comment]
You need to obtain the signature from the bytecode really in order to tell, using a disassembler on the target class can also give you the info you need.

I was truncating the story about inner class synthetic shenanigans for brevity and to stick to the point, there are however lots of things the compiler can do to honour the inner class contract by mutating inner classes to simulate the desired behaviour:

* If an inner class has a private constructor, then a second (package-private) constructor can be generated, this might clash with the existing (private) constructor though so the compiler will add fake arguments to the synthetic constructor to pre-emptively avoid this possibility. These might be of `Object` or might be an entirely synthetic, empty Class which is *only* used as a token to provide uniqueness to the new constructor, or might be the inner class itself.

* If a constructor is modified with synthetic arguments, the signature may clash with an existing user-visible constructor and this too will be decorated (for disambiguation purposes) with a meaningless synthetic argument.

* If the inner class is anonymous then any local (`final`) variables used as in a closure-like manner will also be passed into the constructor, further altering it.

So effectively this is because the constructor in the inner class is `private`, more synthetic shenanigans takes place when the "real" constructor is generated by the compiler, this includes a member which is (in this case) of type `Lnet/minecraft/entity/mob/ZombieEntity$class_1644;`. This argument is entirely fake, it's only used as a sanity check by the compiler to avoid possible clashes with the original constructor, as mentioned above.

I apologise if it wasn't clear from my previous message. Basically: **if in doubt, obtain the signature from Bytecode Viewer or via McDevIntelliJ**. Constructors are *not* ordinary methods and especially with inner classes may have "excess baggage" that's not obvious via the original source. The bytecode you're looking at isn't wrong, you just lack the necessary context of why the compiler would add that (seemingly random) extra argument but just set it to `null`.

It should be noted that `static` inner classes don't suffer from a lot of these issues, but do still suffer from the synthetic accesssor thing mentioned above.

> And it also seems I have a new bug to report to the Minecraft Development plugin heh:

Yeah I'm sure Kyle will be thrilled!

**Comment by Mumfrey** [comment]
If this issue has resolved your problem and educated you. Please use the close button or say "I am satisfied with my care". :smile:

**Comment by InsomniaKitten** [comment]
I honestly am satisfied with this, more than satisfied ^^ Thanks for being so helpful and informative. This was much more feedback that I expected with regard to my problem, and it means a lot more than just "here's what you did wrong, and this is how to fix it, now go and learn why this fixes it yourself" :P Once again, thank you for your response and help. <3

**Comment by DemonWav** [comment]
Wait you can just leave off part of the signature? Seriously?

What kind of crazy show are you running here.

**Comment by Mumfrey** [comment]
Well MemberInfo are basically describing a query, so you can be as vague or as specific as you need to be. They basically consist of 3 parts, `owner`, `name` and `descriptor` and if you omit one or more of those elements then the query just matches in a wildcard fashion. By default the query matches the *first* matching element, using `*` alters it to match all.
