### ISSUE TITLE
Mixins attempts to apply a field GET redirect as a field SET

### ISSUE THREAD

**Issue by Sollace** [SpongePowered/Mixin#301]
Someone just recently linked me this crash report when trying to use BigPony together with LLibrary:

https://gist.github.com/Febilian/1de0f31791ae7a9c80711b9441bdeb7b

I was able to track the problem down to this line:
```
[12:22:35] [Client thread/FATAL] [mixin]: Mixin apply failed bigpony.mixin.json:MixinEntityRenderer -> net.minecraft.client.renderer.EntityRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Redirect method setter net/minecraft/client/renderer/EntityRenderer::redirect$fixCameraDistance$zzn000 has an invalid signature. Expected (Lnet/minecraft/client/renderer/EntityRenderer;F)V but found (Lnet/minecraft/client/renderer/EntityRenderer;)F
```

It looks like gradle is failing to apply a redirect for a field write. The problem is that my mixins _don't have_ a redirect for a field write. What they _do_ have is a _read_!

```
@Mixin(EntityRenderer.class)
@Implements(@Interface(iface = IEntityRenderer.class, prefix = "bigpony$"))
public abstract class MixinEntityRenderer implements IResourceManagerReloadListener {

    private static final String DISTANCE = "Lnet/minecraft/client/renderer/EntityRenderer;thirdPersonDistancePrev:F";

    private float thirdPersonDistanceCustom;

    @Redirect(method = "orientCamera(F)V",
              at = @At(value = "FIELD", ordinal = 0, target = DISTANCE))
    private float fixCameraDistance(EntityRenderer thus) {
        return thirdPersonDistanceCustom;
    }
}
```

I checked in the documentation for @ Redirect and what I'm doing seems to be correct:

```
 *     <td>Read instance field (<tt>GETFIELD</tt>)</td>
 *     <td><code>private <b>FieldType</b> getFieldValue(<b>OwnerType</b>
 *     owner)</code></td>
```

So what? Does that mean the documentation is wrong? Or is this something wrong with that particular version of the mixin processor? 

I can't tell exactly what version they were using, or if it's even possible to change the version separately from upgrading liteloader. It did work correctly when loading through eclipse, and I IIRC there weren't any errors reported when building it with gradle either, so I have really no idea what could cause this to break in this specific circumstance.

**Comment by Mumfrey** [comment]
You need to add an `opcode` argument to your `@At` in order to limit the query results to GETFIELD. In the original method there are only field get accesses but it's entirely possible that another transformer can add a set at runtime. Because your `@At` is missing the `opcode` argument, it matches the instructions added by the other transformer.

In case you're wondering, `opcode` is not mandatory because you might be using the injection point for another purpose (like a callback) but in this case it's good practice because you specifically want your redirector to match GETFIELD only.

I'd suggest that maybe the documentation should be updated to indicate that `opcode` should be supplied when using field redirectors, but the behaviour itself isn't a bug because the output of the query just gets fed to the injector and in this case the injector is choking on the unexpected opcode.

**Comment by Sollace** [comment]
Ah, thanks for the clarification.

I would agree, at least some amendments to the documentation should be made. I remember being confused whilst reading the notes about redirectors and mistakenly assumed it would look at the method signature and got "hey, this looks like a getter, let's only apply it to GETFIELD opcodes!"

But I guess not. :T

Thanks again. Feel free to close this issue if you feel fit.
