### ISSUE TITLE
Do not display a warning when Invokers and Accessors harmlessly overlap, only when they genuinely conflict

### ISSUE THREAD

**Issue by InsomniaKitten** [SpongePowered/Mixin#307]
~~Would it be feasible to remap invokers and accessors to have them be unique - avoiding conflicts with other invokers and accessors injected by other mixins - at runtime? Or would this be too expensive?~~

~~Currently, if you were to have the following, `FooBarAccessor2` accessors would be skipped.~~

```java
public final class FooBar {
  private final String foo = "hello world";
  private final long bar = System.currentTimeMillis();
}
```
```java
@Mixin(FooBar.class)
public interface FooBarAccessor1 {
  @Accessor(value = "foo", remap = false)
  String foo();

  @Accessor(value = "bar", remap = false)
  long bar();
}
```
```java
@Mixin(FooBar.class)
public interface FooBarAccessor2 {
  @Accessor(value = "foo", remap = false)
  String foo();

  @Accessor(value = "bar", remap = false)
  long bar();
}
```
~~This means that for anyone injecting human readable accessors and invokers for class fields and methods, they will very easily conflict at runtime if more than one mixin attempts the same. This is inherently problematic behaviour given that the default approach to accessors and invokers is to name them after the target element with an additional prefix (`get`/`set`/`call`/`invoke`), meaning that *default* behaviour is at very high risk to naturally conflict.~~

**Comment by InsomniaKitten** [comment]
On the other hand, accessors and invokers wouldn't particularly have differing semantics.. Duh. So maybe the primary issue here is that Mixin warns on conflicting injected methods for accessors and invokers.

```
Method overwrite conflict for foo in mixins.mixintests.json:FooBarAccessor2, previously written by foo.bar.mixin.FooBarAccessor1. Skipping method.
Method overwrite conflict for bar in mixins.mixintests.json:FooBarAccessor2, previously written by foo.bar.mixin.FooBarAccessor1. Skipping method.
```

**Comment by gabizou** [comment]
To be honest, as long as the interface is being applied to the target, the methods themselves can conflict and still have the same signature, still identifying to return the same field. What would be considerable however, is when two accessor Mixins accidentally conflict same named and signature getters/setters for different fields (since the field name can be added to the annotation).

Example of what I mean:

```java
public class Foo {
  private Integer myInt;
  private Integer myInteger;
}

@Mixin(Foo.class) 
public interface FooAccessor1 {
  @Accessor(value = "myInt", remap = false)
  Integer getMyInt();

}

@Mixin(Foo.class)
public interface IMixinOtherFooAccessor {
  @Accessor(value = "myInteger", remap = false)
  Integer getMyInt();
}
```

I know this is an extreme, but I don't know if this is being handled similarly to how OP's issue originally started as.

**Comment by Mumfrey** [comment]
It would make sense that if the same accessor/invoker were supplied by two mixins that it could be silently ignored, and conflicting ones could cause a proper error. There's no way to conform them unless they're `private` since that would require finding all possible call sites and Mixin specifically avoids this kind of "global" transformation.

Having Mixin act a little bit more pragmatically when accessors simply overlap would be absolutely feasible though.
