### ISSUE TITLE
AOT Mixing

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Mixin#311]
Most of server admins won't update sponge very often.
It would be cool to have AOT Mixing feature, when starting sponge generates transformed image of minecraft with all changes.

I'm not sure where to create this issue, here or in Mixin repo.

**Comment by Pokechu22** [comment]
This sounds neat, but I don't think it could be done reasonably simply because you need to mix on top of other mods which might do a lot of other transforms (not to mention forge runtime deobf).  You'd need to wait for all of that to be done before you could apply the cached version (and make sure the existing one matches) or else you'd get massive issues.

It might make sense to do it for spongevanilla, though.  I'm not 100% sure about that.

**Comment by gabizou** [comment]
One thing for sure that throws a massive wrench in all of this: AccessTransformers. Since those are not AOT processed, it's not possible to cache pre-mixed classes when an AT is updated/changed.

Likewise, because of MixinPlugins, the ability to change a config value to enable/disable certain mixins also throws a wrench in the idea of caching the pre-mixed classes.

Lots of work for little benefit imo. Class transformation is relatively small cost for the overall startup time, and adding more costs to do hashing and comparison for caching is more than likely to slow down the process even more.
