### ISSUE TITLE
Mixins Update

### ISSUE THREAD

**Issue by MadcowD** [SpongePowered/Mixin#316]
HI there! 

My name is William Guss, I'm a PhD student at Carnegie Mellon Unviersity working on AI research in Minecraft. We've been developing a lot of interfaces for MC which use mixins of all thigns and one crucial next step for us is getting mixins in 1.13 so we can leverage LWJGL 3.  After reading up a bit, I can see that there a few barriers to getting mixins on 1.13, one of which being that 1.13 is apprarently not going to be a reccomended build of Forge. On SpongePowered's side, is there anyone who particularly maintains mixins or has the domain knowledge to push for an update thereto? I'm asking because we have a large amount of discretionary funding for someone willing to work on this, and we'd like to make this update a reality. 

Some links for reference (http://wguss.ml - my personal website, www.herobraine.com - an unofficial website fore the project, http://www.herobraine.com/paper.pdf - a link to our first white paper)

Feel free to shoot me email (wguss@cs.cmu.edu) or just respond here, I understand this isn't the best way to get a hold of someone, but I couldn't find any contact information.

Cheers,
William

**Comment by Mumfrey** [comment]
[Version 0.8](https://github.com/SpongePowered/Mixin/milestone/2) is the next version of Mixin, which adds support for ModLauncher, the new launching platform used in Forge 1.13.2. As far as I know, nobody is planning to support 1.13 since it was immediately superseded by 1.13.1 and 1.13.2. I had intended to release 0.8 last week but am still dealing with some interactions with Forge but that's the only blocking issue right now prior to 0.8 release.

This issue tracker is for reporting bugs and is not a general purpose discussion forum so I am closing this issue as question.

**Comment by MadcowD** [comment]
Apologies for placing this conversation in the wrong place, and thank you
for responding so quickly! Our team would love to support your work if that
makes it easier for you to contribute to this wonderful toolchain, so
please let me know if you're interested.

Thanks again!
