### ISSUE TITLE
(...).InvalidMixinException: Cannot handle AASTORE opcode (0x53) in class initialiser

### ISSUE THREAD

**Issue by matjojo** [SpongePowered/Mixin#322]
I came across an issue where mixin fails at opcode AASTORE. [I think it is at the Block[] in the class.](https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings).

The full stack trace and the code can be seen here: https://paste.ee/p/b0I14

Changing the code to include a real constructor like this: 
(...)
```
    public class OnPlayerAddStatisticsMixin {
        int threshold;
        Block[] blocksToTurnToPath;

    public OnPlayerAddStatisticsMixin() {
        this.threshold = 4; // Player moves 6, 22, 28 when crouching, walking, running.
        this.blocksToTurnToPath = new Block[] {
                Blocks.DIRT,
                Blocks.PODZOL,
                Blocks.GRASS_BLOCK,
                Blocks.COARSE_DIRT,
        }; // do this via JSON maybe?
    }
```
(...)

Solves the issue (Well the code still crashes in game, but that is an issue for me), but I felt like this should be supported, so I thought I'd report. If you need any more information just ask.

**Comment by phase** [comment]
I'd recommend keeping that array in a separate class and using it in the mixin, as well as making the mixin class abstract. Constant fields like this don't really need to be added to the class you're trying to mix into.

**Comment by Mumfrey** [comment]
Certain opcodes aren't allowed in mixin field initialisers because the initialiser has to be merged into the constructor and this is nontrivial for initialiser code which requires locals. Creating arrays is one such operation. This can be bypassed by having the initialiser logic in a static method which contains the necessary initialisation logic:

```java
private Block[] myBlockArray = MyMixin.initialiseMyBlockArray();
```

Since the logic to handle this particular case is quite complex and the actual functionality gained is not really significant, I've largely placed this on the "to add if I'm feeling particularly masochistic" pile.

> Changing the code to include a real constructor like this: [...] Solves the issue

No it doesn't, constructors in mixins are entirely discarded so your array will not be initialised at all. You either need to initialise the array in an `onConstructed` callback injector or via the method mentioned above where the array is constructed in a helper method.

> I'd recommend keeping that array in a separate class and using it in the mixin, as well as making the mixin class abstract. Constant fields like this don't really need to be added to the class you're trying to mix into.

This is also perfectly valid though I can understand keeping it private for encapsulation reasons.
