### ISSUE TITLE
Question - Targetting specific classes in SpongeForge does not work

### ISSUE THREAD

**Issue by TerminatorNL** [SpongePowered/Mixin#323]
I am trying to target `org.spongepowered.common.event.tracking.PhaseTracker` and `org.spongepowered.common.event.tracking.TrackingUtil` in SpongeForge.

I noticed that the Mixins never actually get applied, and no error is printed.
I tried the following:
* Changing the priority of the Mixin class
* Specify `require = 1` on all `@Inject` annotations
* Loading the class manually using `Class.forName()`

I verified that...
* The mixin version shipped with SpongeForge matches what I compile to
* All Minecraft/MinecraftForge mixins apply successfully
* Both `TrackingUtil` and `PhaseTracker` are accessible and loaded. I am able to invoke methods on them, but my mixins are not applied.

Questions:
1. How do I tell Mixin to crash when my Mixins are not applied?
2. Are there any special cases where Mixin does not attempt to transform the classes?
3. If so, can I get around this, regarding SpongeForge?

My mixins are linked here, locked to this current point in time: [MixinSpongePhaseTracker.java](https://github.com/TerminatorNL/Tiquality/blob/628b85c07d357de9ac1ba6d8b9893d315dfb9201/src/main/java/cf/terminator/tiquality/mixin/MixinSpongePhaseTracker.java) and [MixinSpongeTrackingUtil.java](https://github.com/TerminatorNL/Tiquality/blob/628b85c07d357de9ac1ba6d8b9893d315dfb9201/src/main/java/cf/terminator/tiquality/mixin/MixinSpongeTrackingUtil.java)

The class I use to detect if mixins are applied or not is [MixinValidator.java](https://github.com/TerminatorNL/Tiquality/blob/628b85c07d357de9ac1ba6d8b9893d315dfb9201/src/main/java/cf/terminator/tiquality/mixinhelper/MixinValidator.java)

Thanks in advance.

**Comment by gabizou** [comment]
Some classes can be [excluded from class transformations by telling the LaunchClassLoader](https://github.com/SpongePowered/SpongeForge/blob/dd589664efaf4c59c108e7baf496db17d39d9be3/src/main/java/org/spongepowered/mod/SpongeCoremod.java#L120-L126) to exclude them. I stumbled on some oddities in how the PhaseTracker was performing on some issues and stumbled on some injected bits that was breaking a few systems and expectations in the already tightly controlled tracker powering Sponge. Because of those exclusions, you won't be able to transform them. I suggest if you want to prevent certain `Entity`/`TileEntity`/`Block`s etc. from ticking/updating with Sponge, to inject into the methods that do these sort of sanity checks before setting up phases and throwing events etc. [like this method for updating entities](https://github.com/SpongePowered/SpongeCommon/blob/e81a3291ad8e903eb0f2e07682e54f9cac930303/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1757). 


Otherwise, this isn't really an issue with Mixin as it's abiding by the contracts laid out by Launcher.

**Comment by TerminatorNL** [comment]
This explains a lot! Thank you for your explanation.
It might be handy to have some form of error explaining why my Mixins are not applied though.
I will update my code accordingly to comply with SpongeForge's expectations!

**Comment by TerminatorNL** [comment]
@gabizou, how would I target the method you mentioned? 

I tried targetting like this:
```java
@Mixin(value = WorldServer.class, priority = 800, remap = false)
public abstract class MixinWorldServerSponge {

    @Inject(method = "onCallEntityUpdate(Lnet/minecraft/entity/Entity;)V", at = @At("HEAD"), cancellable = true)
    private void onCallEntityUpdate(CallbackInfo ci){
        throw new RuntimeException();
    }

}
```
I tried both priorities 800 and 2000, figuring that applying after SpongeForge would allow me to target the method. Instead, I got the following response: 
```[mixin]: Mixin apply failed mixins.tiquality.json:MixinWorldServerSponge -> net.minecraft.world.WorldServer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$onCallEntityUpdate$bbc000 could not find any targets matching 'onCallEntityUpdate' in the target class net.minecraft.world.WorldServer. No refMap loaded.
```

I see that the SpongeForge source contains the following:
```java
@Implements(@Interface(iface = IMixinWorldServer.class, prefix = "worldServer$", unique = true))
```
I am not sure what that does, since the documentation isn't mature enough yet. (Understandable)

I am willing to jump through some hoops to make a non-hacky solution. I just don't know how to do that at this moment.

Can you give me some pointers on how to hook into this method?
Thanks

**Comment by TerminatorNL** [comment]
I have figured it out.

My solution did not include the prefix and suffix.
Solved this using:
```java
@Mixin(value = WorldServer.class, priority = 3000, remap = false)
public abstract class MixinWorldServerSponge {

    @Dynamic(value = "onCallEntityUpdate is added by SpongeForge (redirect$onCallEntityUpdate$zmd000)", mixin = MixinWorldServer.class)
    @Inject(method = "redirect$onCallEntityUpdate$zmd000", at = @At("HEAD"), cancellable = true)
    private void onCallEntityUpdate(Entity entity, CallbackInfo ci){
        throw new RuntimeException();
    }
    
}
```
