### ISSUE TITLE
Bump commons-io dependency to 2.5

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Mixin#327]
Mixin currently depends on commons-io version 2.4. However, ForgeGradle ships with version 2.5, and some mods I've been testing with (specifically CodeChickenCore) crash when 2.4 is on the classpath.

**Comment by Mumfrey** [comment]
Looking at where commons-io is actually used I think I can safely remove it and switch to using guava for those functions anyway. Since 0.8 is backwards compatible and no further builds of 0.7 are going to be released, I'm going to fold this into 0.8 since it should then fix the issue without having to settle on a specific version.

**Comment by Mumfrey** [comment]
Labelling as "enhancement" because it's not really a bug or a feature.
