### ISSUE TITLE
@Inject on invokation of methods defined in super classes don't get reobfuscated

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#33]
When you try to add an `@Inject` at `INVOKE` of methods called in the target class (but defined in a super class) they don't get reobfuscated by the annotation processor. For example, these [3 injections in a mixin for `DedicatedServer` in Granite](https://github.com/SpongePowered/Granite/blob/master/src/main/java/org/spongepowered/granite/mixin/server/MixinDedicatedServer.java#L53-L69) are failing to reobfuscate because the annotation processor can't find the method mappings. (See [this Travis CI log](https://travis-ci.org/SpongePowered/Granite#L466-L473))

While using the method of the super class as the target (e.g. `MinecraftServer` instead of `DedicatedServer`) reobfuscates fine, the injection doesn't seem to work anymore because it is actually calling the method on `DedicatedServer` and not on `MinecraftServer`.

At runtime, Forge is checking for the method mappings of the super classes so these methods are getting properly deobfuscated, but the methods are not explicitely listed for sub classes in the SRG mappings. We should probably either get the mappings for the super classes in the annotation processor as well or allow the original owner of the method to be used so these can be properly reobfuscated.

**Comment by Mumfrey** [comment]
Whilst this is kind of weird (usually in bytecode method invocations are qualified by their owner) it does seem like in this case there's a mismatch between the invoked class and the owner class so there are two options you've identified, use the owner or use the invoked class.

In this case, I think it's easier to preserve the semantic that a method invocation is qualified with the name of the class specified in the INVOKE rather than the actual owning class. This is because to do the latter we'd need to walk **down** the hierarchy looking for matching invokes which is potentially expensive, versus just walking **up** the hierarchy at compile time looking for a valid owner, which is both cheaper and only has to be done once.

I can modify the AP's search behaviour to accommodate this scenario and it should solve this issue and allow reobfuscation to happen as intended.
