### ISSUE TITLE
Call mixed-in method on shadowed field

### ISSUE THREAD

**Issue by LoganDark** [SpongePowered/Mixin#349]
I'm making a mixin for GuiChat (for tab complete hooks on MCP, without forge). This works:

```java
    @Shadow
    private TabCompleter tabCompleter;
```

However, I have a mixin for TabCompleter that adds a method I need to call. So, I need to be able to do this:

```java
    @Shadow
    private MixinTabCompleter tabCompleter;
```

However, Mixin throws an error that it can't find the field (edited a bit for clarity):

```
Mixin apply failed mixins.baritone.json:MixinGuiChat -> net.minecraft.client.gui.GuiChat:
Shadow field tabCompleter was not located in the target class net.minecraft.client.gui.GuiChat. No refMap loaded.
```

I would cast `tabCompleter` to `MixinTabCompleter`, but `MixinTabCompleter` can't extend `TabCompleter`, since Mixin can't find `TabCompleter` in `TabCompleter`'s `extends` list... so I then tried `((MixinTabCompleter) (Object) tabCompleter)` for the method call, but then Mixin threw this exception (edited a bit for clarity):

```
Error resolving INVOKEVIRTUAL for baritone/launch/mixins/MixinTabCompleter.onGuiChatSetCompletions([Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.baritone.json:MixinGuiChat
```

Your wiki contains information on inheriting from mixins, but I can't find any information on casting a class to a mixin for that class. There's always the possibility of me missing something obvious, and if so, please tell me what it is, this is the first time I've ever used Mixin.

This could probably be solved by #284, either being able to specify the type of the field you're shadowing, if you take into consideration this use case, or Mixin looking for the class targeted by the mixin rather than the mixin class itself. This could also be solved by providing a more generic way of casting a class to its mixin without using reflection.

I have resorted to reflection for this, for now:

```java
    @Inject(method = "setCompletions", at = @At("HEAD"), cancellable = true)
    private void onSetCompletions(String[] newCompl, CallbackInfo ci) {
        try {
            tabCompleter.getClass()
                .getMethod("onGuiChatSetCompletions", String[].class, CallbackInfo.class)
                .invoke(tabCompleter, newCompl, ci);
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            e.printStackTrace();
            ci.cancel();
        }
    }
```

But that's a nasty hack and I'd prefer to have a proper solution.

**Comment by Barteks2x** [comment]
The way you usually do that is create an interface that your TabCompleter mixin implements, and case TabCompleter to that interface. You can't directly reference a mixin class except in some special circumstances.

**Comment by LoganDark** [comment]
> The way you usually do that is create an interface that your TabCompleter mixin implements, and ~~case~~ cast TabCompleter to that interface.

Thanks! That's a much, much less hacky solution.

**Comment by Mumfrey** [comment]
@Barteks2x is correct. A lot of things which seem like they should work on the surface actually don't have any ready translation into the target environment. To break it down:

> However, I have a mixin for TabCompleter that adds a method I need to call. So, I need to be able to do this:
> 
> ```java
>     @Shadow
>     private MixinTabCompleter tabCompleter;
> ```
> 
> However, Mixin throws an error that it can't find the field (edited a bit for clarity):

This happens because the field type for a shadow has to match the type in the target, it may be okay to cast it later on, but the field signature needs to match exactly.

> I would cast `tabCompleter` to `MixinTabCompleter`, but `MixinTabCompleter` can't extend `TabCompleter`, since Mixin can't find `TabCompleter` in `TabCompleter`'s `extends` list... so I then tried `((MixinTabCompleter) (Object) tabCompleter)` for the method call, but then Mixin threw this exception (edited a bit for clarity):

All mixins have to extend a type in the target's superclass hierarchy (even transitively, in the case of supermixins), this can include `Object` for classes with "no superclass" (implicit inheritance from `Object`). The reason mixin can't resolve the INVOKEVIRTUAL is because casting down to a mixin is only useful for *accessor mixins*, since they are "real types" (can be classloaded) - all other casts down to a mixin are for the situations where:

* Another mixin is applied *to the same class* and you want to access stuff from it: eg. `((SomeOtherMixin)(Object)this).someOtherMixinFunc()`
* Another mixin is applied *to a superclass* and you want to access stuff from it without actually extending the mixin (creating a supermixin relationship)

The idiomatic way of doing this is as @Barteks2x says. Use an interface to expose a getter for the thing you're interested in, and a companion mixin for the implementation. The [interface supplies the duck](http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/client/java/com/mumfrey/liteloader/client/ducks/IRenderManager.java) and the [mixin supplies the quack](http://develop.liteloader.com/liteloader/LiteLoader/blob/master/src/client/java/com/mumfrey/liteloader/client/mixin/MixinRenderManager.java), if you like.

You can cut this down to more simple wiring by using *accessor mixins*, which are simply interface mixins which **contain only** [`@Accessor`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/gen/Accessor.html) or [`@Invoker`](http://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/index.html?org/spongepowered/asm/mixin/gen/Invoker.html) methods.

Once you have your accessor mixin, you can simply cast the field to the interface in order to access the resources you need.

**Comment by LoganDark** [comment]
Well, the solution by @Barteks2x worked fine. I'm actually not sure how I didn't think of that, but here I am.

Your accessor mixin solution didn't work somehow - not sure why. I created an Invoker with the same method signature as the mixin, casted the TabCompleter to the interface, and called the method.

I set a breakpoint inside the method and it didn't get hit (and that method call just kinda made GuiChat fall apart a little, which completely broke tab completion). Before you chalk this up to the bytecode manipulation tripping up the debugger, the Minecraft Dev plugin allows me to use breakpoints in mixins (which did work before using the accessor mixin), so I know it's not getting called.

Again, @Barteks2x solution works perfectly. Thanks.

**Comment by Mumfrey** [comment]
Unlike other methods, an accessor as it appears in your code won't actually get called because the code is generated at runtime. Also accessors and invokers are only to provide access to methods and fields which *already exist* in the target class (so they can be used in place of "access transformers") and in the situation that you're calling your own mixed-in method, then using a Duck interface is still the idiomatic approach.

**Comment by LoganDark** [comment]
> in the situation that you're calling your own mixed-in method, then using a Duck interface is still the idiomatic approach.

Which is why I said that I don't know how I didn't think of it :P Since it's actually, kind of obvious... that's how interfaces work.
