### ISSUE TITLE
Better documentation (javadoc) for Inject and Redirect

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#350]
This has been bugging me since forever, it's unnecessarily hard to figure out the right arguments to use for Inject, and exactly how to use any other than the most trivial Redirect modes.

The Inject javadoc is very nonspecific and doesn't ever specify what arguments need to be accepted by the injector.

The redirect javadoc, doesn't for example specify how to exactly use constructor redirect - is it `@At` with `NEW` and class name, or `INVOKE` with `<init>` method?

Those little things add up, and without good IDE support (and MinecraftDev plugin really stagnated there) it's very hard to figure it out, except by trial and error.

**Comment by Mumfrey** [comment]
This is a fair comment. I think rather than trying to cram these things into the javadoc I need to just flesh out injectors in the main documentation. The incubating documentation articles I have cover local capture and redirects so I think I can probably upcycle a bunch of the stuff I've already written to construct a more focused set of examples and bake those into a mini documentation article. The main problem I have with documentation is that I set the quality bar so high for myself that trying to get articles finished can be a challenge.

I'll try to create something a little less detailed with some specific examples which should fill the gap between the javadoc and the (incomplete) more detailed tutorial-style docs.
