### ISSUE TITLE
Constructors

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#36]
This isn't an issue so much as a question.

For Map implementation I can mix my interface into the vanilla MapColor, however I need to create instances of my interface to complete colors that aren't in the original enum (shades). I can work around this, but is it possible to just do new MixinMapColor(MapColor nmsMapColor, int shade)? 
Or am I stuck with a static method that creates these?

Sorry if the explanation isn't very clear.

**Comment by Mumfrey** [comment]
Under no circumstances should you add values to an existing enum, for the same reason as we don't use enums in the API. See [this article](http://www.javaspecialists.eu/archive/Issue161.html) which talks about doing it with reflection but ultimately the reasons are the same.

You cannot instance a mixin because a mixin isn't a class, it only makes sense in terms of its target, and in this particular scenario creating additional instances would be bad.

The recommended way of handling custom "constructor" logic would be to mix in a `onConstructed` hook using an injector, then do your custom logic there. It's not possible to add constructors to a target class using a mixin for obvious reasons.

If you're talking about creating "extra" [pseudo-enum] instances of your mixin, then the optimal solution is to have a surrogate class which *also* acts as a target for the mixin, and provides the additional values.

**Comment by modwizcode** [comment]
Ah, why would I add the surrogate class instead of just using the surrogate class and no mixin?

**Comment by Mumfrey** [comment]
Because a surrogate allows you to reuse the code that you're mixing in to `MapColour`:

![](http://eq2.co.uk/minecraft/mixin/surrogate.jpg)

It's just an example of what's possible. I have no idea what your goal is so these are just random suggestions as to what you can try.

**Comment by Mumfrey** [comment]
@modwizcode Do you need further assistance with this or can I close this issue?

**Comment by modwizcode** [comment]
I think you covered exactly what I needed to know. Thanks, as always, for
the thorough explanation.

**Comment by Mumfrey** [comment]
Ok cool, re-open if any further related queries.
