### ISSUE TITLE
"Mixin Launch Plugin Service could not be located" (ModLauncher)

### ISSUE THREAD

**Issue by RoccoDev** [SpongePowered/Mixin#361]
Trying to load Mixin in ModLauncher 1.13.2.

ModLauncher is properly recognizing the TransformationService:
```
Found additional transformation services from discovery services: [path/to/mixin/jar.jar]
Found transformer services : [mixin,fml]
```
However, it can't find the launch service:
```
Found launch services [minecraft,testharness,fmlclient,fmlserver]
Found launch plugins: [eventbus,object_holder_definalize,runtime_enum_extender,field_redirect_net.minecraft.potion.PotionEffect/Lnet/minecraft/potion/Potion;,accesstransformer,capability_inject_definalize,runtimedistcleaner]
```
These last two are sent before the first two.

So then it crashes with
```
org.spongepowered.asm.launch.MixinInitialisationError: Mixin Launch Plugin Service could not be located

at org.spongepowered.asm.launch.MixinTransformationService.initialize(MixinTransformationService.java:77)
at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:43)
```
I'm loading my mod from the mods folder.
The META-INF folder contains all the services it needs (all the services from the Mixin jar are there).

Possibly related to cpw/modlauncher#31?

**Comment by Mumfrey** [comment]
Mixin under modlauncher is designed to be bundled with forge or at least added to the launcher configuration, it is **not** designed to be bundled with a mod.

**Comment by Barteks2x** [comment]
So as it is, there is no way to release a mod that uses it?

**Comment by Mumfrey** [comment]
The **-preview** is specifically there so that I can get feedback on the 0.8 and people can experiment with the changes since the changes to the pipeline to accomodate ModLauncher are not insignificant. Once I'm happy that it's stable then I'll make a proper release and chat with the Forge guys about how it will be deployed.

If you want to experiment in the meantime then it's pretty trivial to mod your Forge launch configuration to include a mixin library built locally.
