### ISSUE TITLE
Suppress warnings for public nested classes in private types

### ISSUE THREAD

**Issue by Chocohead** [SpongePowered/Mixin#372]
Say you want to inject into `Inner`:
```java
interface Outer {
    void take(Inner inner);

    public interface Inner {
    }
}
```
If `Outer` is not in the default package, Mixin will print a warning `Mixin target xxx.Outer$Inner is public and must be specified in value`. Previously this happened in the default package too but #338 allowed suppressing it. Similar to types without a package, when the outer type is private there is no way to specify the inner type in the source despite it technically being public.

The closest work around would be to place the Mixin in the same package as `Outer` is in, but of course that would then fail to load `Outer` as it would think it was a Mixin.

**Comment by Mumfrey** [comment]
I guess I'll just have to bite the bullet and let the suppress warnings be applied to any occurrence of this situation then, since ideally it would be possible to resolve the "outer" scope and figure out that the warning is bogus. It's possible to do this for the vast majority of common scenarios so I think this can be handled by both making the check more intelligent but also providing a `@SuppressWarnings` key for the situations where the warning is still raised.
