### ISSUE TITLE
INVOKEDYNAMIC call arguments incorrectly mapped for multi-target mixins

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#373]
This is an issue that's been cropped up since 0.8-SNAPSHOT being upgraded with Sponge, where essentially nested lambda calls will not get remapped appropriately and causes an AccessError at runtime.

The erroneous class output is viewable [here](https://gist.github.com/gabizou/590e8ce543228e39ba6accff1881363c#file-output-bytecode-viewer-L7875-L7883) where the lambda method is not being transformed.

**Comment by Mumfrey** [comment]
So it turns out the original issue was slightly misleading. What is actually happening is that bootstrap method arguments for `INVOKEDYNAMIC` instructions are not being correctly remapped when a mixin has multiple targets.

This is because the *first* mixin target is correctly remapped, but these remappings 'leak' into the master `ClassNode` because ASM simply passes the argument array by reference when visiting a target `MethodVisitor` from a `MethodNode`.

This has a simple fix because creating a shallow defensive copy of the args array should prevent this leakage into the master `ClassNode` held in the `MixinInfo`.
