### ISSUE TITLE
Mixin 0.8 TweakClass breaks RandomThings (Minecraft 1.7.10)

### ISSUE THREAD

**Issue by DarkShadow44** [SpongePowered/Mixin#374]
I'm working on a port of SereneSeasons to 1.7.10 and wanted to use Mixin for the hooks it needs.
Recently I upgraded from 0.7-SNAPSHOT to 0.8-SNAPSHOT, and that breaks RandomThings:
https://pastebin.com/iMPFdAM9

I bisected the problem it to commit fd2f2c79c574c0b40340d8977c0e9f284a6e17ed or 8965b0a3f20f11f6fa42188a01f422df7e868ead, but those are to big for me to really understand.

Mixin 0.7 with RandomThings Minecraft loads fine and both mods work.
Mixin 0.8 with RandomThings Minecraft crashes.
Mixin 0.8 without RandomThings Minecraft loads fine and both mods work.

Just having Mixin active, with 
```
TweakClass: org.spongepowered.asm.launch.MixinTweaker
```
is enough to break RandomThings - so the problem is not with my mod itself. Even when my jar only loads mixin without doing anything, RandomThings breaks.

To test just put those two files in a 1.7.10 mods folder:
Minimal shaded Jar: [EmptyMixin](https://www.mediafire.com/file/zvsmozh0jivt2j9/EmptyMixin.jar/file)
Download [RandomThings](https://www.curseforge.com/minecraft/mc-mods/random-things/files/2225310)

For reference, this is how I shade Mixin into the jar: https://github.com/DarkShadow44/SereneSeasons/blob/1.7.10/build.gradle

**Comment by Mumfrey** [comment]
Can you confirm this still breaks with newer versions of minecraft. Minecraft 1.7.10 is [over 5 years old at this point](https://howoldisminecraft1710.today/) and there are so many library changes between now and then (eg. you're still stuck using ASM 5.0.3) that supporting it is really only an "if it still works".

Most likely candidate for breakage is that 0.8 reverts to using provided ASM and doesn't use internal ASM any more. This change cannot be reverted because it's required for ModLauncher, so if 0.7.11 still works for you then I would consider sticking with that version.

There probably is some way to wrangle it to work, but honestly I'm not going to waste what little available dev time I have on fixes for a 5+ year old platform.

If you can demonstrate that this can be replicated on anything 1.12 or later then I will look into it, but as it stands this seems like basically a self-inflicted problem.

**Comment by DarkShadow44** [comment]
I understand. I can't reproduce the problem on 1.12, so I'll close this. Sorry to be a bother.
