### ISSUE TITLE
`@Accessor` and `@Mutable` do not work on private final fields

### ISSUE THREAD

**Issue by Jordin** [SpongePowered/Mixin#378]
The `@Accessor` annotation makes no attempt to make the field accessible if it is final. This causes setters to not work on any final fields.

The `@Mutable` annotation makes no attempt to make the targeted field mutable if it is private. This causes mutation attempts of private final fields to fail.

I propose stripping the final flag from all `@Mutable` targets (as Mutable implies non-final), and either stripping the final flag from all `@Accessor` setters or forcing the use of `@Mutable` with `@Accessor`.

**Comment by Mumfrey** [comment]
> The `@Accessor` annotation makes no attempt to make the field accessible if it is final. This causes setters to not work on any final fields.

I don't fundamentally see any problem with altering this behaviour. The finalness change happens at a stage where no other code which cares can act on the alteration so it's still not straying into access transformer territory. The question arises as to whether the default behaviour should be to raise an error in this instance and force the use of `@Mutable` on the accessor in order to force to developer to acknowledge they're altering the contract, similar to mutable shadows.

> The `@Mutable` annotation makes no attempt to make the targeted field mutable if it is private. This causes mutation attempts of private final fields to fail.

I don't see any detrimental side-effects to changing this, the original version just ignored `private` fields because the actual runtime never enforced the finalness behaviour anyway.

Related PR #377.

**Comment by Earthcomputer** [comment]
> the actual runtime never enforced the finalness behaviour anyway

Perhaps this is what changed in Java 12, and to preserve the expected behaviour, we now need to make private fields non-final.

As for `@Mutable` on setter accessors, the use case I can see is in interface mixins, where you can't have fields and therefore can't shadow fields either. If interface mixins didn't exist, I'd be against this as putting `@Mutable` on the field is more explicit.

**Comment by Mumfrey** [comment]
> As for `@Mutable` on setter accessors, the use case I can see is in interface mixins, where you can't have fields and therefore can't shadow fields either. If interface mixins didn't exist, I'd be against this as putting `@Mutable` on the field is more explicit.

Yeah accessor mixins are the real main argument in favour of this. I've pulled in Jordin's changes from the (now closed) PR and am working on the functionality to put the mutable annotation on setter accessors which should resolve this.
