### ISSUE TITLE
Validate shadow methods/fields and injections at compile time

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#40]
I'm not completely sure if this exists already, but it would be great if the annotation processor could validate the shadow fields and methods as well as injections at compile time and warn if they actually don't exist. While you'll notice it at runtime, it would be better if that could be reported already at compile time instead of only noticing once the mixin target class gets loaded.

For example, [this commit](https://github.com/SpongePowered/SpongeCommon/commit/b50d949028b9d24c1a1ece631a1a8f1a6382daf6) by @gabizou in SpongeCommon [compiles without any problems or warnings](https://travis-ci.org/SpongePowered/SpongeCommon/builds/59522601), but does actually [add an injection](https://github.com/SpongePowered/SpongeCommon/commit/b50d949028b9d24c1a1ece631a1a8f1a6382daf6#diff-dcfe7e9aa63b343150e8fbb6da0669d8R345) on a [method added by Forge](https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/world/World.java.patch#L561-L562) which will [fail when running in Vanilla](https://gist.github.com/Minecrell/523f550738e8dcfaa757).

It would be nice if we could have it fail the build, or at least warn about problems like this at compile time so we notice when adding Forge specific stuff to Common directly.

**Comment by Mumfrey** [comment]
Warning is definitely possible. It could never fail a build because there are perfectly valid circumstances in which a shadow field or method may not exist at compile time, or may not be visible via Mirror.

It's worth bearing in mind that the information the AP has to work with is kind of limited. Mirror is pretty shite and also can't account for things which are added at runtime (such as fields added to a target class by another mixin) and doesn't provide access to anything synthetic and/or inner. I could in the future simulate some of this up to a point, but recreating the entire mixin architecture inside the AP isn't really feasible.

I can try to add what output I can, but failing a build with these checks would be absolutely unworkable so it would rely on people actually reading the build output, and I'm not sure this has much in the way of advantages over developers just getting into the habit of running an audit before committing changes.

**Comment by Minecrell** [comment]
@Mumfrey Speaking of running an audit, is there a way to force-load all the classes (to check for apply errors) but without generating all the implementation reports? This is spamming the console quite a lot, but it is not running the audit if CHECK_IMPLEMENTS is not set.

**Comment by Mumfrey** [comment]
I could probably remove the `CHECK_IMPLEMENTS` requirement on the audit pass.
