### ISSUE TITLE
7.11 tag is gone

### ISSUE THREAD

**Issue by dominikaaaa** [SpongePowered/Mixin#420]
Hi, I couldn't help but noticing that the 7.11 tag is completely gone, which has broken a few projects which depend on it. Was there a reason for this change?

**Comment by Mumfrey** [comment]
> Hi, I couldn't help but noticing that the 7.11 tag is completely gone

What? There never was a tag or branch for 0.7.11, internally or externally.

> which has broken a few projects which depend on it.

How?

> Was there a reason for this change?

There has been no change, I don't know what you're talking about.

**Comment by dominikaaaa** [comment]
How come [this](https://github.com/kami-blue/client/blob/master/build.gradle#L81) has been in my gradle for years or [this](https://github.com/cabaletta/baritone/blob/master/build.gradle#L94) project with nearly 2000 stars also uses 7.11

**Comment by Mumfrey** [comment]
That's... not what a tag is.

The artefact is still on maven, I have literally no idea what you're talking about.

**Comment by dominikaaaa** [comment]
It's missing on jitpack

**Comment by Mumfrey** [comment]
Are you completely insane or just trolling me now?

**Comment by dominikaaaa** [comment]
I'm not, builds are failing and the tag is gone, which is why I asked.

**Comment by Mumfrey** [comment]
* The "tag" is not gone, there never was a tag.
* The artefact is **NOT** gone from the official maven server to which it is published (the sponge maven)
* Jitpack is **absolutely nothing to do with me**, and I suggest you avoid it and use the official maven
* Your sponge maven is using the wrong scheme, you should be using `https`, modern gradle doesn't like `http`

I honestly can't believe you're not trolling because as even a novice programmer you should damn well know the difference between a tag, a branch, an artefact, and a repository. It's not my job to instruct you to Google the difference between these things yet here we are.

Most importantly: **this issue tracker is for BUGS in the product not for "my build is broken because I don't understand my own toolchain**.

Kindly stop wasting my time.
