### ISSUE TITLE
Asserts in mixins

### ISSUE THREAD

**Issue by jk-5** [SpongePowered/Mixin#43]
When using asserts in mixin classes, the mixin applier fails with the following message:

    Mixin classes cannot contain visible static methods or fields, found $assertionsDisabled

When the java compiler finds an assert, it adds a static variable to the class indicating whether or not the -ea argument is added. As this variable is not visible in source, it is safe to whitelist it.

**Comment by Mumfrey** [comment]
The processor is actually supposed to exclude synthetic fields from that check and I've noticed that it [does here](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinApplicator.java#L291) but [doesn't here](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinPreProcessor.java#L251] so that's probably the issue.

I'll update the check in the pre-processor and then you can see if that rectifies the issue.

**Comment by Mumfrey** [comment]
I was able to successfully replicate this behaviour and the synthetic exclusion in the pre-processor does indeed rectify the issue.

**Comment by jk-5** [comment]
Thanks for the quick fix. It works properly now.

**Comment by jk-5** [comment]
Not really fixed yet. For some reason, the mixin system doesn't throw any error, but loading the class fails with
`java.lang.NoClassDefFoundError: nl/jk_5/pumpkin/server/mixin/core/server/management/MixinServerConfigurationManager`, while loading `ServerConfigurationManager` (the class containing the asserts). It looks like the reference to the static field is not renamed from the mixin class to the target class

**Comment by Mumfrey** [comment]
Ok I'll check it out when I get home later. I suspect I know what the issue is and it shouldn't be too tricky to fix.

**Comment by Mumfrey** [comment]
Sorry for the delay, I completely forgot about this yesterday. Should be properly resolved now.
