### ISSUE TITLE
Mixin does not handle the new modlauncher transformation reason

### ISSUE THREAD

**Issue by ichttt** [SpongePowered/Mixin#439]
To fix https://github.com/cpw/modlauncher/issues/57, modlauncher introduced a new reason for piping classes through the transformer: `computing_frames` (https://github.com/cpw/modlauncher/blob/e9771d85ae2b9118d41a5174dd924825957574e2/src/main/java/cpw/mods/modlauncher/api/ITransformerActivity.java#L26).
This reason is used when modlauncher needs to read a class to compute frames.
When this reason occurs, the actual code does not need to be transformed. The only transformation that is needed during this phase is regarding the class metadata, so if you need to change the superclass, or add interfaces, you should probably do that in this phase. If you know none of your transformations are ever relevant for `getCommonSuperClass`, you can skip all transformations when this reason is present
Example crash report when using modlauncher 7.0.1: https://gist.github.com/BedrockLegends/e1b4a08c61c2dd7724d9690defd2ae84

**Comment by TelepathicGrunt** [comment]
Yeah I am getting this issue on 1.16.2-forge-33.0.58 with Apotheosis with The Bumblezone on. It also happens with Apotheosis is with Botania as some examples to reproduce the crash. (There are also many other combinations of mods crashing due to this too but I listed two)

Log of the crash which gives the same Re-entrance error as the above log: https://hatebin.com/jfecelcowp

**Comment by Mystogrigen** [comment]
Throwing in a debug.log of my own: https://gist.github.com/Mystogrigen/c21e06dde29f8dfcea9beef6d19dafd0

If I have Xaero's map (or minimap), I crash with exit code: 0 (when I use the twitch launcher. When I use MultiMC? I get an Exit Code: -1. The above gist is from MultiMC, since getting a debug log from twitch is a pain.

**Comment by shartte** [comment]
I was trying to create a small example for this when I noticed it was already reported. 

Maybe this will be helpful, as it recreates this scenario with two empty Mixins and one empty Coremod on the latest 1.16.3 Forge:
https://gist.github.com/shartte/413857df4d018f43c0e35f532a8a91f1

**Comment by Mumfrey** [comment]
@shartte thanks that's just what I needed
