### ISSUE TITLE
Any `@...Inject` annotation is recognized as `@Inject`

### ISSUE THREAD

**Issue by ShadewEnder** [SpongePowered/Mixin#443]
Mixin seems to recognize a random annotation like `@NotAnInject` as an `@Inject` annotation. I stumbled upon this issue when making a custom injector for a mod, and the annotation was `@CustomInject`. Mixin treated the `@CustomInject` annotation as an `@Inject` annotation even though I registered the correct `InjectionInfo` class with the correct annotation.
I got a strange error and after three hours of debugging I found this code in `InjectionInfo.parse(MixinTargetContext, MethodNode)`:
```java
for (InjectorEntry injector : InjectionInfo.registry.values()) {
    if (annotation.desc.endsWith(injector.simpleName)) {
        return injector.create(mixin, method, annotation);
    }
}
```
Here the bug appeared: the descriptor of the annotation is checked to _end with_ the simple name of any of the registered injectors. Thus: if an injector for `@NotAnInject` or `@CustomInject` is registered, the injector for `@Inject` (`CallbackInjector`) will consume these annotations. Here's the above code again with a possible fix:
```java
for (InjectorEntry injector : InjectionInfo.registry.values()) {
    // Match full typename instead of only the end of the name
    if (annotation.desc.equals("L" + injector.annotationType.getName().replace('.', '/') + ";")) {
        return injector.create(mixin, method, annotation);
    }
}
```
Note that this issue is not only applicable to `@Inject` but also `@ModifyVariable` (i.e. `@NoModifyVariable` also works).
I had to rename my annotation to something like `@CustomInjection` in order to make it work properly - not that that's a problem, but this behaviour is just weird and inconsistent

**Comment by Mumfrey** [comment]
Well that's what I get for doing naïve matching on the class names, good catch. I guess the work around for now is use a more unique class name but I'll definitely fix this for the next release. 0.8.1 was going to be a bug fix release but I had to make it a hotfix because of the modlauncher changes. I'm working through open bugs for an 0.8.2 release so I'll roll this into that.

**Comment by ShadewEnder** [comment]
Ah great to see that it's fixed! I wanted to ask one thing still: is there a way to register custom annotations to the annotation processor (especially via Gradle)? As for now I had to specify both named and intermediary names when annotating with custom annotations because the annotation processor did not generate refmaps for my custom annotations.

**Comment by Mumfrey** [comment]
Not currently, but it's really something I need to add because custom target selectors are now supported and at the moment there's no way to register them for the AP to consume. I need to have a bit of a think about how to make that work though since it's a little bit "open the box with the crowbar that's inside" if custom selectors are part of the project that's being compiled.

Basically it's fully allowed for your project to contain injectors and injection points which are used at runtime, but they won't be available at compile time so I'm not sure of the best way to handle that without forcing the injectors into a dependency.
