### ISSUE TITLE
An instance Invoker for a static method causes a VerifyError

### ISSUE THREAD

**Issue by coderbot16** [SpongePowered/Mixin#444]
Using Yarn mappings with Fabric on 1.16.3 with Mixin 0.8.1.

This seems like a recurrence of https://github.com/SpongePowered/Mixin/issues/341. Or, at least, it appears related.

```java
@Mixin(TreeFeature.class)
public abstract class MixinTreeFeature<FC extends FeatureConfig> extends Feature<FC> {
	@Invoker("isDirtOrGrass")
	abstract boolean invokeIsDirtOrGrass(TestableWorld world, BlockPos pos);
}
```

Note that the target method is static, but my invoker is not:

```java
private static boolean isDirtOrGrass(TestableWorld world, BlockPos pos) {
```

While this is an obvious error on my part, I do think that Mixin could have a more descriptive error message here.

Please note that I haven't tested this on Forge.

**Comment by Mumfrey** [comment]
Confirmed this on stock mixin on MCP. I can see the cause as well, this combination of staticness (instance invoker for a static method) is actually supported but [this line](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/gen/AccessorGeneratorMethodProxy.java#L77) uses the staticness of the *target* not the invoker in order to determine the start index, so it's off-by-one in that situation.
