### ISSUE TITLE
Javadoc for @Pseudo mixins needs improvement

### ISSUE THREAD

**Issue by Extegral** [SpongePowered/Mixin#446]
I am not sure where I should ask this, but I couldn't find better place, so here I am.

So basically, my question is on this part of `@Pseudo` annotation javadoc:

```
In particular, the superclass requirement for pseudo mixins is extremely
important if the target has an obfuscated class in its hierarchy. For example
let's assume that we're mixing into a class SomeCustomScreen from
another party which extends GuiScreen which is obfuscated.
Attempting to inject into initGui will succeed at dev time and fail
at production time, because the reference is obfuscated. We can overcome this
by ensuring the mixin inherits from the same superclass, thus allowing
initGui to be resolved in the superclass hierarchy (this is not the
case for normal mixins).
```
I got the message of why example injection will not work, but didn't understand the second part about how to overcome it. Do I need my mixin to extend the same vanilla superclass as it's target? What do I do with all the constructors which I need to implement in such case? Do I need to do anything about target method specification?

The example doesn't extend as far as to showcase the implementation which would actually work, and it's not on the wiki or anywhere else I searched. On the similar note, the `@Pseudo` annotation itself isn't mentioned on wiki either and it's documentation is very abrubt, for instance, it doesn't tell that pseudo mixins should specify their target class through `targets` array in the annotation instead of just class literal, and the javadoc of target array itself tells you it will yeet an exception into the face of yours if you specify publicly available classes there. I guessed this statement must not take hold for `@Pseudo` mixins only because they don't make any sense otherwise, but ideally it should be documented somehow.

**Comment by Mumfrey** [comment]
I'll level with you, `@Pseudo` was just added quickly to allow some of the compile-time machinery to know that a target class isn't available, and at runtime to know it *might* not be available. That's not an excuse for why it's not documented, just an explanation as to why it's so sparsely documented. Will update this issue to actually refer to that shortfall in documentation.

> I got the message of why example injection will not work, but didn't understand the second part about how to overcome it. Do I need my mixin to extend the same vanilla superclass as it's target? What do I do with all the constructors which I need to implement in such case? Do I need to do anything about target method specification?

It depends really, a lot of this depends how much you want to happen automatically and how much you are happy to do manually. I think people take for granted that mixin is set up to make the obfuscation "not your problem" for the most part, but it honestly doesn't actually need to be like that. On the flip side, if you want the automation to do its job then you need to give mixin enough info to work with.

You don't need to have the same obf superclass as the target, but you do need to have **a** superclass which contains any obfuscated methods you care about, **or** you need to do those mappings by hand (because the AP can't resolve mappings with no info to go on). If you're only touching non-obfuscated methods/fields in the target then it doesn't matter, but like in the example, if you're gonna touch something which is inherited from an obf superclass then that'll need to be remapped.

In production, `initGui` might become `func_1234_z` but mixin has no way of resolving that mapping if it doesn't know where to look.

> The example doesn't extend as far as to showcase the implementation which would actually work, and it's not on the wiki or anywhere else I searched.

Because an implementation that would work isn't fundamentally different to any other implementation, the superclass requirement is stated and the contract of `@Pseudo` is very shallow. There isn't really anything **to** showcase.

>  it's documentation is very abrubt, for instance, it doesn't tell that pseudo mixins should specify their target class through `targets` array in the annotation instead of just class literal

This is the case for all inaccessible classes, not just `@Pseudo`, so I assumed that was obvious.

> and the javadoc of target array itself tells you it will yeet an exception into the face of yours if you specify publicly available classes there

That's a valid point, so that can be updated. There's also an annotation to suppress warnings now which could be mentioned there.

In general please ask questions in discord. I'll leave this open because it's a valid documentation issue aside from the question.
