### ISSUE TITLE
Using Mixin without Minecraft

### ISSUE THREAD

**Issue by ReneHollander** [SpongePowered/Mixin#46]
Hello!

Is there a way to use Mixin without Minecraft, Forge, Sponge, etc? I want to use it in some other projects and initially thought it would be able to be used in a standalone project as the repostitory description suggested: "Mixin is a trait/mixin framework for Java using ASM". I then read further and found out it won
't work for my application in for example a Bukkit Plugin (I am still using it because I am too lazy to move to the SpongeAPI...)

- Rene

**Comment by Mumfrey** [comment]
You can use Mixin in any application where you control the class loading, for example your own projects or by "wrapping" an existing application. This is possible because Mixin uses [LaunchWrapper](https://github.com/Mojang/LegacyLauncher/) and other than the "default" support for Minecraft, LaunchWrapper is basically an environment-agnostic extensible ClassLoader system.

So yes, other than LaunchWrapper, you can use Mixin without any of the other components like FML or whatever.

For obvious reasons you cannot use Mixin with Java EE applications, and obviously using it in a Bukkit plugin is completely impossible. But for standard applications all you need to do is write a Tweaker to plug in to LaunchWrapper and bootstrap your application using Launch.

**Comment by phase** [comment]
How would one initialize Mixins in a standalone project? Would you need to use LegacyWrapper if you weren't using Minecraft?

**Comment by Mumfrey** [comment]
Yep, but as I said, LaunchWrapper is entirely application-agnostic and is open source as well, so it's pretty straightforward to use.

**Comment by phase** [comment]
Would I need to make a new Tweaker & TweakerInjector for my application?

**Comment by liach** [comment]
https://github.com/thog/universalat

**Comment by Mumfrey** [comment]
> Would I need to make a new Tweaker & TweakerInjector for my application?

Just a tweaker is sufficient, the contract of tweakers is pretty straightforward and you can read any of the many examples which are floating around.

> https://github.com/thog/universalat
> 
> which works on bukkit.

Yes but not as a plugin, so that's a stupid example. As I said above, *"You can use Mixin in any application where you control the class loading"* and this is true of most applications, if you wrap the application then you can do mostly whatever you want. I mean, that's the entire *point* of LaunchWrapper in the first place!

There are ways around this limitation but they're hacky and far from straightforward.
