### ISSUE TITLE
mixin 0.7.11 support with 0.8

### ISSUE THREAD

**Issue by Niceghost21** [SpongePowered/Mixin#469]
If a mod uses 0.8 and another mod uses 0.7.11, is there any way I can make them compatible with each other, where the game won't crash on start?

**Comment by Geolykt** [comment]
https://github.com/SpongePowered/Mixin/wiki/PSA-Forward-Compatibility-Features-in-Mixin

**Comment by Niceghost21** [comment]
I see.  I've tried changing around min versions but I still end up getting a crash.  If you would like to, you can look at the mod and log file for the crash I'm having.  I'm currently trying to add the mod, baritone, to the mod pack, MC Eternal, but I get a crash, I believe related to mixin version incompatibility.  Here is the log I get:
[latest.log](https://github.com/SpongePowered/Mixin/files/6054071/latest.log)
Baritone uses 0.7.11 whilst, I believe the rest of the mod pack uses 0.8.  Here is baritone:
[baritone.zip](https://github.com/SpongePowered/Mixin/files/6054081/baritone.zip)

**Comment by Geolykt** [comment]
Well then, you'd need to manually try to update mixin to a newer version. Basically older versions of mixin cannot support features that haven't been implemented then.

**Comment by Mumfrey** [comment]
This is an issue tracker not a support forum, for support and questions please use the discord channel.

0.8 included some necessary breaking changes in order to support newer modding systems that are one of the few cases where mixin is not backward compatible (see [the release notes for 0.8](https://github.com/SpongePowered/Mixin/releases/tag/releases%2F0.8) which explained this in detail).

However 0.8 has been out for over a year now, so everything should have upgraded now to be honest, there isn't really any reason to continue to use 0.7.x because even after the changes, old versions of the game are still supported. If you find a mod still using an 0.7 release then it's definitely a good idea to tell them to upgrade because all they're doing by continuing to use the old version is introducing incompatibilities which don't need to be there.
