### ISSUE TITLE
Priority explanation or an issue (see inside)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#52]
@Mumfrey 

I'm seeing in a couple of Sponge mixins the priority being set in the @Mixin annotation (typically its set to 1001). Are we supposed to be setting Sponge's mixin priority in the json config? From my understanding, common's mixins should have the lowest priority and Sponge/SpongeVanilla's should have the higher priority. Otherwise, Mixin prints warning for duplicate overwrites.

**Comment by Mumfrey** [comment]
That's correct, by default everything [defaults to a priority of 1000](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/extensibility/IMixinConfig.java#L37) that includes the priority for configs *and* mixins themselves. Mixins *do not* inherit the priority from their config, but you *can* [specify a global default mixin priority in a config](https://github.com/SpongePowered/Mixin/commit/1218cc51e3259df2b3314f7cfb5d25188bc0bb91) if you want to.

*Config priority* determines the order in which configs are applied to their targets, lower numbers are applied earlier, higher numbers later, so if one config is downstream of another, it should have higher priority.

*Mixin priority* is used to determine which specific mixin "wins" in any given conflict scenario. When a method is mixed in (either overwritten or added) it is decorated with an invisible annotation which stores the priority of the source mixin, if a later mixin comes along then *its* priority is compared with the annotated value and if it's higher then the new mixin wins, and if it's lower or equal then a warning is raised so that you know the downstream mixin's method was not applied.

This gives you fairly fine grained control of the application process, of course you can use config plugins to refine the process further.
