### ISSUE TITLE
Inject doesn't make sense [Read description]

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#54]
It seems the behavior of `@Inject` is to actually call a method with the injected code. Which would make sense, it's a lot safer than just injecting the opcodes directly into the target class. However this makes captureLocals somewhat unhelpful when dealing with primitive types, namely int.

I need to increment an integer through an `@Inject` is the basic problem.

**Comment by Mumfrey** [comment]
"Inject" refers to the fact that it's injecting a callback, the full name of that feature is *Callback Injector*, you define a Callback Injector using `@Inject`. I haven't gotten to that part of the documentation yet.

"Capture Locals" lets you "capture" the "locals" from the point at which the callback injection is placed, this is sometimes necessary because the variable you need to access (say, a reference to an object that was just created, or a value returned from a prior function) is only available locally in the method, and not as a method parameter.

However, a new feature I've been working on will let you do what you want, I've been holding off pushing it any further until I was sure that the LVT inflection (which it relies on somewhat) is working as required, since we're still having issues with LVT inflection I'm sitting on it for now. Basically it adds the ability to make special callback injectors which can modify a single local variable, a bit like `@ModifyArg` but actually allowing modification of vars which are locals.

As for 

> It seems the behavior of `@Inject` is to actually call a method with the injected code

I'm not sure why you say "actually", since it's fairly explicit in the javadoc that this is exactly what it does. To quote the javadoc from `@Inject` verbatim:

> Specifies that this mixin method should inject a callback (or callbacks) to itself in the target method(s) identified by method().

**Comment by modwizcode** [comment]
I guess I missed that line. But it seems you're already one step ahead of me as usual ;)

**Comment by Mumfrey** [comment]
I knew it would be needed and I think it was @Aaron1011 who actually mentioned it a while back which is why I started working on it but then we had all that trouble with the LVT generator so I decided to sit on it for a while till that is sorted, there are work-arounds in the mean time, it depends what you need to do really.

**Comment by modwizcode** [comment]
I can accomplish the solution through an `@Redirect` but it's a bit of a hack.

**Comment by Mumfrey** [comment]
Use that for now and mark it with `// TODO - replace with manipulator` just as a reminder.

**Comment by modwizcode** [comment]
Aye
