### ISSUE TITLE
Refmap doesn't generate

### ISSUE THREAD

**Issue by AQRRastiq** [SpongePowered/Mixin#547]
Hi, I created this issue because when I test my tweaker client created with forgegradle and mixingradle, I get this warning :

`[10:06:12] [main/WARN]: Reference map 'mixins.arkemys.refmap.json' for mixins.arkemys.json could not be read. If this is a development environment you can ignore this message`

Then I get this error : 

`[10:06:12] [main/FATAL]: Mixin apply failed mixins.arkemys.json:client.MixinMinecraft -> ave`

Then my client crashes.

I think it is coming from the fact that my refmap isn't generating. I tried applying many fixes but it didn't solve my problem.

By the way here is my build.gradle :

https://pastebin.com/LF7Fx9bd

**Comment by Mumfrey** [comment]
This is a an *issue tracker* not a support forum. Normally I'd say go to discord for help but since you're using an ancient version of mixin with an ancient version of the game then you're not going to receive any help there either.

This problem is self-inflicted, use a current version of something up-to-date like fabric or forge, and don't open frivolous "help" issues on an issue tracker.
