### ISSUE TITLE
1.8.9 forge

### ISSUE THREAD

**Issue by xrnss** [SpongePowered/Mixin#549]
any docs on how to use mixins and @inject etc w forge 1.8.9 been looking but can't find much ty

**Comment by ItsDoot** [comment]
If you're looking for documentation on how to *write* a mixin: [Use the wiki.](https://github.com/SpongePowered/Mixin/wiki)

If you're trying to *setup an environment* to be able to write mixins, we do not help with setting up Mixin to work on ancient versions. Feel free to give it a try yourself, but we'd rather spend our time with recent versions of Minecraft, because of how drastically mod tooling has changed since 1.8 was released 6 years ago.

Those that continue to use Mixin with 1.8.9 are free to do so, but understand that any pain they may have is considered self-inflicted. **If you want help setting up your environment, use a recent version (such as 1.15+).**
