### ISSUE TITLE
DIstant Horizons mod + Optifine in Forge 1.18.1 causes mixin fail to load class: requires ASM9 

### ISSUE THREAD

**Issue by TomTheFurry** [SpongePowered/Mixin#550]
We noticed a strange issue with mixin in Forge 1.18.1 with the Optifine. Our Distant Horizons Mod need to mixin the `net.minecraft..client.renderer.LevelRenderer` class, which would be replaced with Optifine's modified version uppon startup. However, the Mixin throws up this error when trying to Mixin that class:
```
[11:39:25] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/LevelRenderer (java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9)

[11:39:25] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.LevelRenderer was not found lod.mixins.json:MixinWorldRenderer
```
I have asked in the discord about this and they said it probibly shouldn't happen.

Additional Info:
I am one of the dev on the Distant Horizons Mod, and we are trying to port the mod to 1.18.X. We use architectury to develop Forge and Fabric version at the same time. Interestingly, in Fabric, by using the Optifabric mod, this issue doesn't appear. Only with Forge do we see this issue.

Tested on all the available Optifine version, and tested with the mixin.json config 'minVersion' set to "0.8" or "0.8.2", and the config "compatibilityLevel" to "JAVA_17". Our Distant Horizons Mod does work fine when Optifine is removed, and with Optifine, only the Mixin patch for the `WorldRenderer` class didn't apply. Every thing else works fine.

For more info, you can come to the Distant Horizon discord or the Distant Horizon GitLab page. I could supply a dev build of our mods via Direct Messages in discord if it is needed.

GitLab link:
https://gitlab.com/jeseibel/minecraft-lod-mod/
Discord link:
https://discord.gg/Y8sZNWXQWx

The attached file is the full log.
[latest.log](https://github.com/SpongePowered/Mixin/files/7787250/latest.log)

**Comment by TomTheFurry** [comment]
The corresonding issue in Distant Horizon Mod gitLab:
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/139

**Comment by Mumfrey** [comment]
The `x requires ASM9` messages are raised by ASM when the API level passed to an ASM class is lower than the value *supported by* that version but the version knows about a feature you're trying to interact with. Mixin is version-agnostic in regards to ASM and passes the version in use.

Eg. If you're using ASM9 9.x, it passes Opcodes.ASM9. This isn't necessarily recommended, but it avoids problems like this.

Mixin will catch some thrown exceptions from elsewhere, which is what you're seeing here. Specifically you're likely seeing the error caught by `ClassInfo` when it attempts to load a target class for metadata generation. This means the error is happening somewhere else and mixin is just reporting it.

My first guess would be https://github.com/McModLauncher/modlauncher/issues/74, but breakpointing on the exception with the debugger would tell you exactly where.

If you require further assistance you can find me in [`#mixin`](https://discord.gg/tBcwxz2) on discord, but I'm pretty sure this isn't a Mixin bug. Feel free to reopen if you can determine otherwise.
