### ISSUE TITLE
Better document your maven in your README

### ISSUE THREAD

**Issue by alxpettit** [SpongePowered/Mixin#552]
You give some basic instructions on how to get started, with your `README.md`, but you do not mention to add your maven, or what the URL is. I only got it to compile after finding it elsewhere.

```gradle
maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
```

It would be cool to see this information added to your README.

**Comment by Mumfrey** [comment]
The maven repos are literally listed under the heading "binaries" and it's not mixin's job to teach people basic usage of build systems.

**Comment by alxpettit** [comment]
LOL, I have extensive programming knowledge and know many build systems, but I'm not an expert in Gradle in particular, so this point ended up wasting quite a lot of my time. I don't get this weird anti-documentation attitude, but you do you. :P

**Comment by Mumfrey** [comment]
> I don't get this weird anti-documentation attitude, but you do you. :P

There's a difference between anti-documentation and anti-filling-the-documentation-with-pointless-fluff. I go to some lengths to ensure things are documented effectively, but that doesn't translate into a duty to teach people Java bytecode, or build systems, or any number of other topics which it's reasonable to assume are better documented elsewhere.

The repositories are mentioned right near the top of the README under a heading "*Binaries*" and it's left at that because people using this library are going to be falling into one of two possible camps:

* People using mixin via a platform which already includes it, eg. Sponge, Forge, Fabric, Quilt, etc. In which case knowing where the binaries are is kind of moot since mixin is provided transitively
* People using mixin in some kind of custom platform, where the base level of programming knowledge is going to be much higher since this is intrinscially a pretty complex thing to be doing in the first place.

In the latter case, **extremely basic** knowledge about the build system is just taken as given. Adding repositories to obtain dependencies and then specifying those dependency artefact coordinates is "Java build systems 101", regardless of whether you're using Gradle, Ivy, Maven, or any one of a plethora of different systems. Maven repositories are a de-facto standard, and knowing this but being unfamiliar with a particular tool means it isn't hard to type _"maven repository gradle"_ into Google.

> LOL, I have extensive programming knowledge and know many build systems

Then you know that specifying repositories is pretty straightforward, and googling this would have taken you literal seconds.

> but I'm not an expert in Gradle in particular,

This does not require "expert" knowledge, this requires extremely basic knowledge and the ability to read the documentation.

> so this point ended up wasting quite a lot of my time.

No, you wasted your own time when you tried to use something without bothering to read the documentation first, or even just google "how to add maven repository to gradle" or any number of possible search terms which would have led you directly to the answer. Hell, there's a discord link at the very top of the README and you could have just asked for help there.

It should be pretty clear from the documentation available here and in the Javadoc that I take documenting this project pretty seriously, and devote a lot of time to it, so saying I'm "anti-documentation" is total nonsense. In no world is covering the precise syntax for declaring a dependency in a project build file (which doesn't have to be gradle, **you** are the one that chose to use gradle and then blame me for your decision to not learn about it first) an effective use of my time, or the time of anyone actually reading the README.

If you continue to blame others for your own shortcomings, you're not going to get far as a developer, regardless of how "extensive" your programming knowledge is.

**Comment by Aizistral** [comment]
Damn, not gonna lie - arguing with Mumfrey when he's got the point is like coming out with a stick against planet-killer class weapon.

**Comment by alxpettit** [comment]
WTF? Gotta remember to unsubscribe when I'm arguing with weirdos...

**Comment by alxpettit** [comment]
@Mumfrey 

LOL, not reading all that text. You could have just slightly tweaked your docs with the same effort. xD

**Comment by NicoleKai** [comment]
Bloating and redundancy is bad in software due to the nature of limited resources in computers and their general reliability.

However, you are giving instructions to humans. Redundancy and bloat is almost always better than an absence of information.
Humans have messy system architecture, imperfect retention, and may not arrive at advanced knowledge in the same linear path you did.

Some people are so autistically gifted, they can coast on raw intellect and self-taught advanced information for years but entirely lose out on the basics.
You made this software public with the assumption other people would continue to use it and improve on it.
Maximizing the success of this project will mean you will have to teach people, and everyone learns differently. 

> you're not going to get far as a developer, regardless of how "extensive" your programming knowledge is.

What you are performing is technical communication. Be concise, and be thorough, but most of all: **COMMUNICATE**
THAT is what will get you far as a developer.
