### ISSUE TITLE
Mixins can not modify non-coremods in a production environment.

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/Mixin#57]
I realise that this is not the intended purpose of this library, but it can come in handy. What I tried to do is write a mixins for the mod ComputerCraft. As mixins are much easier than manually ASM everything around. I wanted to add additional behaviour to the turtle block, so that it will give a break event with the last clicked user as breaking user.

[MixinClass](https://gist.github.com/thomas15v/c86ec61a581cc2ad5b09) 
(As far I understood I need to use the obfuscated names, as mixins doesn't check inheritance on compiletime)
[ErrorLog](http://hastebin.com/wusoxuyoca.vbs)

As far I understood, this is caused because mixins thinks the loading is done after coremods are loaded.

**Comment by thomas15v** [comment]
I just realise that the problem is this:
```java
@Mixin(TileTurtle.class)
```
When the classloader loads the above. It will try to look for ```TileTurtle.class``` The problem is that the class does not exist yet. A solution would be:
```java
@Mixin(targets = "dan200/computercraft/shared/turtle/blocks/TileTurtle", remap = false)
```
Only problem is that the mixin compiler doesn't allow this:
```java
MixinTileTurtle.java:14: error: Mixin target dan200/computercraft/shared/turtle/blocks/TileTurtle is public and must be specified in value

```

**Comment by Mumfrey** [comment]
Please stop guessing what the issue is, it's not helpful. Just state the problem and leave it at that.

It's quite simple: mixins cannot transform mods because they are not on the classpath **at the transition to the `DEFAULT` Environment**, when those configs are loaded and the metadata generation pass occurs. Allowing this to happen would require another Environment Phase to be added. Since this cannot be done in a platform-agnostic way, it would require the additon of arbitrary Environments (or at least some pre-defined ones), which is not impossible but is not going to be a priority to implement because in order to implement it neatly it obviously needs some extra infrastructure.

I'm going to officially state for the moment that transforming mods is *currently not supported*, but *will be supported at some time in the future*.

**Comment by thomas15v** [comment]
Oke :worried:. I will currently will just convert normal mods to coremods in order to patch them. Somehow forge doesn't really seems to care if the mods are already in the classpath or not. But I have to say. Mod modification support would definitely help out a lot of modded server communities. As ASM and reflection are mostly their only hope, unless they want to ban the specific modded items. 

But I understand, it doesn't really add much to the sponge project and it is probably a lot of work to make it work to. Not to mention that it might break compatibility with SpongeVanilla... .

**Comment by Mumfrey** [comment]
> But I understand, it doesn't really add much to the sponge project and it is probably a lot of work to make it work to. Not to mention that it might break compatibility with SpongeVanilla... .

It's not that really, I mean there are other use-cases for additional environment phases. It's just that they're not particularly high priority and as I said it needs careful planning in order to not become messy.

**Comment by thomas15v** [comment]
I just leave this for people who also have this problem and want to mix non-coremods. To make normal mods available in the DEFAULT Environment all you have to do is this: https://github.com/densitycraft/Glue/blob/master/src/main/java/com/densitycraft/glue/loader/PatchLoader.java#L55-L58.
