### ISSUE TITLE
Wiki - Tutorial on setting up a mod to add mixins

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Mixin#58]
The wiki doesn't seem to have any tutorials on how to create a mod that uses mixins. I'm not talking about writing the code (that's already added); I'm talking about setting up stuff like `build.gradle`. Any plans to add this?

**Comment by Mumfrey** [comment]
Yes, the final component (other than bootstrapping, which is already covered) is that article at the bottom labelled "using the mixin annotation processor", which will cover the necessary steps to set up the build environment. Since this is already planned (see the wiki home page) this issue isn't really needed.

**Comment by JBYoshi** [comment]
Is there any setup needed in build.gradle?

**Comment by Mumfrey** [comment]
No, only the AP stuff.

**Comment by JBYoshi** [comment]
Thanks.

**Comment by Mumfrey** [comment]
For current references, just look at the Sponge codebase, since all the AP scaffolding is there already.

**Comment by JBYoshi** [comment]
From what I can tell, I just need to:
- Create a core mod that invokes `MixinBootstrap.initialize()` and `MixinEnvironment.addConfig()`.
- Add the annotation processor properties to `javac`.
- Make mixins and register them in the mixins config file.

Is that all?

**Comment by Mumfrey** [comment]
You need to use the tweaker in production if you're using FML because coremods don't get access to the AppClassLoader. The coremod handles boostrap in dev and the tweaker handles it in production.

But yeah, other than that you just need to configure the AP and route the output appropriately, you need to take the generated refmap and reference it in your mixin config too, and don't forget to package it into your mod file.

**Comment by JBYoshi** [comment]
Will the coremod/tweaker stuff be mentioned on the wiki page?

**Comment by Mumfrey** [comment]
No because it's already mentioned in giant text in the existing article:

![](http://eq2.co.uk/screenshots/2015-07-08_22-30-53.png)

**Comment by JBYoshi** [comment]
Whoops, didn't see that. Sorry.

**Comment by Mumfrey** [comment]
I guess I should make the text biggerer.

**Comment by JBYoshi** [comment]
:)

**Comment by liach** [comment]
@JBYoshi Every one of [ForgeEssentialsMain] (https://github.com/ForgeEssentials/ForgeEssentialsMain) ,[Sponge] (https://github.com/SpongePowered/Sponge) and [Almura] (https://github.com/AlmuraDev/Almura) is a good example on how to use mixins. There're also different ways bootstraping. As I see in FE, they call the bootstrap method in `FMLConstructionEvent`.
