### ISSUE TITLE
hi my minecraft modpack doesnt work

### ISSUE THREAD

**Issue by jorgemf95** [SpongePowered/Mixin#587]
heres the debug.log

https://paste.ofcode.org/xFWDPVGKgeDsgXXTwsJufB

**Comment by Mumfrey** [comment]
This is an issue tracker for Mixin, not a support forum. Normally I'd suggest joining our Discord channel but that is for support *writing* mixins, you appear to have a an issue with a mod, so you should contact that mod's support channels. Though be aware that because you are using an old version of the game, it may no longer be supported.
