### ISSUE TITLE
Incorrect javadocs prevent compilation from completing with JDK 8

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#6]
Title says it all.

**Comment by Mumfrey** [comment]
I was under the impression that we were working with JDK 6 which is what all of my testing has been performed under. If it's only javadoc then I can fix building in JDK 8 easily though.

**Comment by progwml6** [comment]
jdk 8 is rather picky w/ javadoc

**Comment by Mumfrey** [comment]
I know, I kind of like the javadoc to be clean though and generally spend quite a bit of time adding javadoc comments to everything. Not sure what JDK8 would be choking on but I'll investigate.

**Comment by Kobata** [comment]
It's a few things: For one, it doesn't like the &lt;/pre&gt;&lt;/blockquote&gt;&lt;/p&gt; because &lt;pre&gt; and &lt;blockquote&gt; imply &lt;/p&gt; on the opening tags.

There's also a spot or two where you have &lt;init&gt;, which makes it complain because that's not a tag, and using @-returns instead of @-return

**Comment by Mumfrey** [comment]
I actually took the nesting of blockquotes/pre etc from the JDK javadoc, so go figure why that breaks! The ctor reference makes sense and I can replace the html entities.
