### ISSUE TITLE
Not working on legacy version(1.11.2 with mixin:0.7.11)

### ISSUE THREAD

**Issue by FYWinds** [SpongePowered/Mixin#606]
Minecraft Version: 1.11.2 with forge 2588
Mixin Version: 0.7.11-SNAPSHOT

Client startup will end up in: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
```
[08:32:30] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[08:32:30] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_341]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_341]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by Mumfrey** [comment]
This is an issue tracker for bugs and feature requests for Mixin, not a support forum. Normally for support questions you should ask in discord but the version you are running is very old and not supported any more. You may have some luck if you can track down any developer communities which support old versions of the game but I'm not aware of any in particular.

**Comment by FYWinds** [comment]
Actually not asking for support, I'm currently develop a legacy version forge mod using mixin. build.gradle presented here.

```gradle
buildscript {
    repositories {
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
        maven { url = 'https://repo.spongepowered.org/maven' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.2-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

version = "1.0"
group = "a.b.xxxxxx"
archivesBaseName = "Xxxxxx"

sourceCompatibility = targetCompatibility = "1.8" 
compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

repositories {
    maven { url = 'https://repo.spongepowered.org/maven' }
}

minecraft {
    version = "1.11.2-13.20.1.2588"
    runDir = "run"

    mappings = "snapshot_20161220"
}

dependencies {
    compile('org.spongepowered:mixin:0.7.11-SNAPSHOT')
    annotationProcessor 'org.spongepowered:mixin:0.7.11-SNAPSHOT'

}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

mixin {
    add sourceSets.main, "mixins.xxxxxx.refmap.json"
    defaultObfuscationEnv notch
}

jar {
    manifest.attributes(
            "TweakOrder": "-900",
            "TweakClass": 'org.spongepowered.asm.launch.MixinTweaker',
            "MixinConfigs": 'mixins.modshadow.json',
    )

}
```

**Comment by Mumfrey** [comment]
Sorry but what you're describing isn't a bug or a feature request, it looks like the problem you're having is to do with a misconfigured build environment. Even if it was a bug, the version of Mixin you're using is very old and it would be likely the bug had been fixed by now.

If you use a current version of Forge then you are entitled to support under Forge's support policies, but because you are using a very old version which is no longer supported, then rectifying build-related issues falls to you, as that pipeline is not supported any longer, and supporting those old versions isn't within scope for myself either.

If you have a Mixin bug or issue, with a current version, you can report it here no problem, or ask for help in discord and will always receive guidance. But what you're asking for here is not a mixin problem, it's a build problem, and specifically it's a build problem with some now extremely out-of-date libraries which themselves aren't supported any longer.

If you're willing to update to 1.18 or 1.19 then you are welcome to seek assistance in the forge discord, or in the mixin channel on the sponge discord (link in the README), howevever if you stick with the 1.11 forge then you will need to seek guidance elsewhere.

**Comment by Mumfrey** [comment]
The one bit of guidance I will give, because it's a general direction you can take: check out mods of the same era which were using Mixin, their `build.gradle` files may provide some help. In most cases, there will be tags or branches on their repositories you can use to wind back time to their legacy versions.
