### ISSUE TITLE
[Feature Request] redirect entire slices of code

### ISSUE THREAD

**Issue by wntiv-main** [SpongePowered/Mixin#609]
If it is not already possible, I think it would be very useful to specify a slice of code (probably using the pre-existing `@Slice` annotation) and replace the entire contents of that slice of bytecode with custom code. This would be useful in large functions where we want to keep functionality at the beginning AND end, but replace some functionality in the middle. This would be better than overwriting the entire function as (theoretically) another mixin inject that does not affect the sliced area could still be injected.

**Comment by Mumfrey** [comment]
While it would be useful, it's not something which is going to be supported.

> I think it would be very useful to specify a slice of code (probably using the pre-existing `@Slice` annotation) and replace the entire contents of that slice of bytecode with custom code.

Rerouting *arbitrary* segments of code is very, very out of scope because mixin is looking for efficient ways to interact with method bodies and verifying what you select is valid is incredibly complex, especially in any way which is repeatable. So that's never going to happen.

I did originally have a feature called *rerouters* planned which could reroute existing blocks, eg conditional bodies or loops, and I talk about why that was scrapped [here](https://github.com/SpongePowered/Mixin/issues/365#issuecomment-539464542) in some detail.

It's not that it's a bad idea fundamentally or something I'd like Mixin to do, but it just doesn't fall in scope in terms of something that can fit well with Mixin's feature set since Mixin makes certain guarantees about the integrity of its transformations and those guarantees just aren't available without a colossal amount of complexity which just makes it not really feasible to do.

Hope that makes sense.
