### ISSUE TITLE
Mixin conflicts with CoFHCores ASM Class Loader

### ISSUE THREAD

**Issue by mcsnetworks** [SpongePowered/Mixin#63]
Almura is using an older version of Mixin tech within 1.7.10 environment.

http://www.github.com/AlmuraDev/Almura

We have an issue currently where a specific class will not mixin correctly with a specific build of CoFHCore.  In-fact the mixin doesn't even attempt to load, no error, yet all of our other mixins work just fine.

This is our mixin that won't load:

https://github.com/AlmuraDev/Almura/blob/master/src/main/java/com/almuradev/almura/core/mixin/client/renderer/entity/MixinRendererLivingEntity.java

The commit that breaks our compatibility is this:

https://github.com/CoFH/CoFHCore/commit/a0e21021f2b5d0a409e632ba934c62a6e5c93373

There is an additional commit that the developer said "should" have fixed it but didn't.

https://github.com/CoFH/CoFHCore/commit/180f939917aa2bd4abd4ba183f2fc434a5d81762

Below is a transcript of the chat conversation surrounding this issue.

http://pastie.org/pastes/10363181/text?key=x5qajcbfei6pb0xvtywsw

I am looking for way to over come this issue.  Discussing this with @Zidane he indicated that it appeared skyboy put in place protections from other mods coming in and running additional ASM on classes that have already been touched.

**Comment by Mumfrey** [comment]
Please confirm that this bug exists in the latest version of the Mixin library, quite a lot has changed (especially with respect to re-entrance handling and class metadata generation) in recent releases and it's entirely possible that this is already fixed. As far as I can tell from your code you are using mixin 0.1, which certainly predates some quite significant improvements in Mixin's internal architecture, some of which were specifically designed to combat classloader circularity shenanigans.

As for @skyboy's commits you linked, I don't see anything there which would screw over Mixin, at least not the recent versions.

**Comment by Mumfrey** [comment]
On further inspection of your code it does indeed look like you are still using an extremely old version of Mixin. I am marking this as invalid until it's verified to exist in the current library.

**Comment by Zidane** [comment]
@Mumfrey 

You should remember why I haven't bumped this up and that was because of the fact that the newer versions breaks another mod we use (the one called MalisisCore)...at least a few months ago.

I'll give bumping it up another shot and "we'll see".

**Comment by Mumfrey** [comment]
In the case of MalisisCore however it was a clear cut case of a poorly designed transformer on their part. Whether it's usable or not for Dockter's server is irrelevant in the context of *this* bug report: I need to know if the bug reported *in this specific issue* is fixed by later versions of the library in order to know whether this issue is valid or not, other mods have no bearing on that whatsoever.

Now, if it's tested with the new version and still broken, then the issue can be considered valid and I will spend time looking into it. However it just doesn't make any sense to spend time diagnosing an issue if it turns out it was actually fixed months ago. Hence marking this issue as invalid until that can be ascertained.

The issue with MalisisCore was most assuredly with *that* mod, and the thing which broke it is actually the thing which (I suspect) is actually the *fix* for the issue being reported here.

**Comment by Zidane** [comment]
I'm going to close this as bumping Mixin seems to work fine with MalisisCore and the CoFH devs issued a patch on their end that fixed the initial issue.

**Comment by Mumfrey** [comment]
That makes sense, thanks for testing. We can just continue and troubleshoot the dual-injection with the FML launch handler then.
