### ISSUE TITLE
Can't mixin into ClassLoader?

### ISSUE THREAD

**Issue by kropt** [SpongePowered/Mixin#637]
I'm not entirely sure if this is intended behaviour, but whatever I do, mixins for any ClassLoader just don't get applied. 
No errors or logs suggesting anything went wrong. Class doesn't get dumped with `-Dmixin.debug.export=true`. Mixin just doesn't do anything.

```java
@Mixin(value = ClassLoader.class, remap = false)
public abstract class ClassLoaderMixin {
    // ...
}
```

Mixin is in correct package and listed in *.mixins.json.
Feels like I've tried everything, and nothing I do can get a mixin to apply to a ClassLoader.
The only possible issue I can think of is [Jigsaw](https://openjdk.org/jeps/403) being funny about `java.lang.ClassLoader`? I have a method to disable that, but I don't know how I can run it before mixins are applied.

**Comment by kropt** [comment]
Targetting Fabric/Quilt if that matters.

**Comment by LlamaLad7** [comment]
You cannot mix into classes that are already loaded. ClassLoader is obviously one of the first classes to load in any application. You should have no reason to do that in the first place, but regardless this is an issue tracker, not a support forum. Take it to the fabric / quilt discord with your actual problem, since you obviously cannot modify the classloader.

**Comment by kropt** [comment]
Fair enough, guess I'm out of luck then.
