### ISSUE TITLE
Revisit Redirecting Setting Fields (Like That of Methods)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#65]
So I was using the newest Mixin in Almura and I came across a situation in-which being able to set the local variable's value when it assigns the field would prevent a very hard injection (or at worse an Overwrite).

Is there any possibility to revisit allowing this capability?

**Comment by Mumfrey** [comment]
I guess I should probably create issues or something for everything I have roadmapped for this project, but yes that's very much something I have been planning for. Development of this project is taking a back seat to Sponge proper at the moment but I will be resuming work on this primarily in the near future, I primarily want to finish off a big new feature which is *Rerouters*, which we discussed some time ago and there is significant work already completed on. However being able to modify local variables is also a planned feature and fi it's a priority then I can make that the next thing on the list.

The basic premise of modifying variables in the method's locals table is that the locals will all be captured into a special `CallbackInfo` and can be modified via that object.

Since this is already roadmapped I will close this issue, I'll possibly create issues for all the features I have roadmapped at some point so that questions like this can be pre-empted. If in doubt, just ask me in IRC or something.
