### ISSUE TITLE
[Question] Any ways to add a static method to an existing class with mixins?

### ISSUE THREAD

**Issue by Jog-Ming** [SpongePowered/Mixin#673]
I want to add `public static void foo()` to existing class `Bar`. I know that adding non-static methods to existing classes can be achieved by 'interface injection' provided by fabric loom, but is there any way to add static methods to existing classes?

**Comment by LexManos** [comment]
What would the purpose of this be?
What are you expecting the resulting syntax to look like?

**Comment by Jog-Ming** [comment]
I came across this problem when I'm porting a mod from 1.19.2 to 1.18.2, where some minecraft apis are missing. To solve this I need to reimplement the apis in 1.18.2. I know that there are many ways to do that, but if I can add a static method to the class that lacks the api, it would allow any further updates of the mod in version 1.19.2 be transferred to 1.18.2 more smoothly and simply.

**Comment by Jog-Ming** [comment]
The resulting syntax would probably be something like:
```
@Mixin(Bar.class)
public abstract class BarMixin implements IBar {
    public static void foo() {
        doSomething();
    }
}
```
And then, in fabric.mod.json:
```
{
    ...
    "custom": {
        "loom:injected_interfaces": {
            "net/minecraft/something/class_xxx": ["path/to/interface/IBar"]
        }
    }
}
```
Which is basically the standard fabric loom way of achieving 'interface injection'.
However, this is impossible, because you can't declare a class to be public static inside a mixin.

**Comment by Earthcomputer** [comment]
It's a static method. Just put it in your own class.
This is a bug tracker, not a place for questions. For further questions please go to the mixin channel in the Sponge discord.

**Comment by Jog-Ming** [comment]
So there isn't a way. I'll wait for a developer to either close this issue as unrelated or mark this as a feature request.

**Comment by Pokechu22** [comment]
Even if you added a static method to a different class at runtime, code that tried to use that would not compile since it wouldn't know about that method at compile time. This would only by useful if you were trying to use older code without recompiling, which is an easy way to create `LinkageError`s (and run into issues with reobfuscation, etc.)

The simpler solution for cross-version stuff is to create your own class with static methods and use that class everywhere; then you can call the vanilla static method from that class if it exists and use your own reimplementation on other versions.

**Comment by Zidane** [comment]
The comments above have covered this quite well. Not to mention, this is an issue tracker not a discussion forum (as @Earthcomputer  mentioned).
