### ISSUE TITLE
[Feature] Overwriting statements within methods

### ISSUE THREAD

**Issue by spaceemotion** [SpongePowered/Mixin#75]
Afaik, Mixin does not currently support changing statements within the target method. It is possible to inject before or after a statement (or even replace the whole method itself), but not directly replacing it (e.g. a field set, method call, …).

If the feature can already be achieved, I would love to know how :)

**Comment by JBYoshi** [comment]
Does `@Redirect` work for your needs?

**Comment by spaceemotion** [comment]
@JBYoshi No, this only redirects method calls, not field get or set statements for example.
I am already using them and they work like advertised :)

**Comment by Mumfrey** [comment]
Arbitrary code injection isn't planned however modifying local variables very much is. I keep meaning to add everything to a roadmap somewhere so questions like this don't keep coming up.

**Comment by spaceemotion** [comment]
Ah okay, thanks! Local variable modification is what I wanted initially, although a whole statement would be nice. Maybe I can figure something out and create a PR if I manage to achieve results.

**Comment by Mumfrey** [comment]
There are various reasons why "arbitrary" statements can't be replaced as discussed in previous issues. However things which *can* be achieved whilst preserving method integrity are planned or already being actively developed. These are the previously-discussed rerouter functionality for conditional blocks, and the ability to modify arbitrary locals. 

Mixin's primary goal is to allow safe modification of target classes and only transformations which can be applied without causing damage to a method or class, this is why the existing injectors are all carefully designed to be stack/local neutral, thus even if they are injected in the wrong place the worst that can happen is that a callback happens in the wrong place, the method will still work. This is why I'm dead against any kind of "arbitrary" opcode replacement, because it's difficult - or in some cases impossible - to provide those same guarantees.

If you can suggest functionality which satisfies this requirement, then I'm more than happy to add new things. Essentially I just won't allow replacement of a chunk of opcodes or anything like that because it deviates from Mixin's main principal.
