### ISSUE TITLE
Mixin in SpongeForge extending Mixin in SpongeCommon doesn't get remapped

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Mixin#81]
As first reported on the forums: https://forums.spongepowered.org/t/server-crash-when-one-of-the-players-try-to-join/10072

Basically, [`MixinEntityPlayer` (SpongeForge)](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/entity/player/MixinEntityPlayer.java#L94) extends [`MixinEntityLivingBase` (SpongeCommon)](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/living/MixinEntityLivingBase.java).
The worldObj field is shadowed in common's MixinEntity and accessed in MixinEntityPlayer.
Problem is that while worldObj is renamed to the srgname in common's mixin, it seems that the spongeforge mixin don't get the references renamed.

**Comment by Mumfrey** [comment]
This is related to the same problem solved in 5814ea195775fa24d6efc52491a61994bd0facab which is effectively "AP state is lost between project compile passes". I solved the supermixin issue there by storing the class data in a bundle which gets passed down the compiles.

In this case it's the field remappings which need to get passed between compile passes, this **may** be as simple as passing the srgs into the next compile task from the previous one (which is frankly a hell of a lot easier now I have `MixinGradle`) or it may be more complicated, depending on how SS handles this (I'm not sure if it remaps field/method accesses if the field/method *itself* is not remapped.

If there's a solution to this then it's certainly going to be a lot easier to handle now `MixinGradle` exists, because I have access to things in the build environment which I previously couldn't touch, so hopefully this shouldn't be too tricky to address... famous last words.

Consider it accepted and I'll work on a solution across both projects.
