### ISSUE TITLE
Bad type on operand stack when capturing locals

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#88]
On Minecraft 1.8.9 there seems to be a problem with capturing locals in an injection where Mixin reports a variable of type `String` that doesn't actually exist and later tries to assign an `Iterator` to it. I could imagine this is caused by the for-each loop, although I'm not entirely sure about that.

The problem exists on Mixin 0.4.7 and 0.4.10, and Java is throwing the following error when the class is loaded:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/command/server/CommandScoreboard.leaveTeam(Lnet/minecraft/command/ICommandSender;[Ljava/lang/String;I)V @164: invokespecial
  Reason:
    Type 'java/util/Iterator' (current frame, stack[11]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @164
    flags: { }
    locals: { 'net/minecraft/command/server/CommandScoreboard', 'net/minecraft/command/ICommandSender', '[Ljava/lang/String;', integer, 'net/minecraft/scoreboard/Scoreboard', 'java/util/HashSet', 'java/util/HashSet', 'java/lang/String', 'java/util/Iterator', 'net/minecraft/entity/Entity' }
    stack: { 'net/minecraft/command/ICommandSender', 'net/minecraft/entity/Entity', 'net/minecraft/command/server/CommandScoreboard', 'net/minecraft/command/ICommandSender', '[Ljava/lang/String;', integer, 'org/spongepowered/asm/mixin/injection/callback/CallbackInfo', 'net/minecraft/scoreboard/Scoreboard', 'java/util/HashSet', 'java/util/HashSet', 'java/lang/String', 'java/util/Iterator', 'net/minecraft/entity/Entity' }
```
Full error: https://gist.github.com/Minecrell/e3a5dd0d1c1f9e3299f7

This is the method where the injection is in: https://gist.github.com/Minecrell/f9a1ec9a5321b1fec8bd#file-java-L31

... And this is what mixin generates (decompiled): It seems to pass the iterator generated for the for-each loop as a local it detects as additional string: https://gist.github.com/Minecrell/f9a1ec9a5321b1fec8bd#file-mixin-java-L28

Injection (with locals as suggested by `LocalCapture.PRINT`):
```java
@Inject(method = "joinTeam", at = @At(value = "INVOKE", target = GET_UNIQUE_ID), locals = LocalCapture.CAPTURE_FAILHARD)
public void onGetUUIDJoin(ICommandSender p_147190_1_, String p_147190_2_[], int p_147190_3_, CallbackInfo ci, Scoreboard scoreboard, String s,
        Set<String> set, Set<String> set1, String s1, String s2, Entity entity) {
    // ...
}
```

**By the way:** Would there be (theoretically) any way to use the LVT present in 1.8.3+ in Mixin to prevent problems with the local variable detection? Because if I understand it correctly, the methods should already contain a valid local variable table, so could that be possibly used as validation or as a help to generate the LVT for Mixin?

**Comment by Mumfrey** [comment]
I'll look into it.

> By the way: Would there be (theoretically) any way to use the LVT present in 1.8.3+ in Mixin to prevent problems with the local variable detection? Because if I understand it correctly, the methods should already contain a valid local variable table, so could that be possibly used as validation or as a help to generate the LVT for Mixin?

If an LVT and/or stack frames are present then they are not generated. The main problem has always been not so much whether LVT/frames are available, but issues with how ASM handles them and differences between the frames present in retroguarded code and decompiled-then-recompiled code. There are irreconcilable differences between the frame nodes which won't be solved by having the LVT. I know we refer to all these issues capturing locals as "LVT issues", but that's just a shorthand for saying "issues working out what the fuck variables are available where within a method", and the LVT is only part of that story.

In all honesty the generated LVT works pretty well now, since it basically uses the ASM analyser to work out the frame state at every instruction, that point is moot if the LVT is present. In *development* code the LVT has always been present, but that hasn't stopped the frame thing being the main problem. Having the LVT available in development might reduce the need for surrogates a little, but it's not going to be a magic bullet because the issue with the frames still exist.

The frames only establish a contract for the locals state at the point they refer to in the code, from that point forward it will **always** be necessary to "play through" the bytecode from *there* to *here* (where *there* is the last available frame and *here* is where the injection is) and work out the new frame state. The problem is that ASM is pretty gung-ho with how it uncompresses various types of frame, and whilst the frames it expands are *valid*, they aren't necessarily the "best" frames for that point in the code, just the most permissive. I frankly suspect (since conversations with other ASM users has leant a lot of weight to this belief) that the ASM frame expander is just crap.

So just to revisit your question:

> By the way: Would there be (theoretically) any way to use the LVT present in 1.8.3+ in Mixin to prevent problems with the local variable detection? Because if I understand it correctly, the methods should already contain a valid local variable table, so could that be possibly used as validation or as a help to generate the LVT for Mixin?

Yes, if it's present it's used. But it doesn't actually help as much as you think, since the root problem is ASM expanding frames, not the presence/absence of the LVT. It might help a *bit*, but it won't solve problems like this one.

I will look into the issue, it's most likely a frame problem again.

**Comment by Mumfrey** [comment]
Just to add one thing, the *main* thing that will be solved by having the LVT in production is the need for `@Coerce` when a local type such as a `boolean` can only be captured as an `int` (or a `boolean` using `@Coerce`) because in the bytecode `short`, `int`, `byte` are all the same. In development I have the LVT available and thus the correct type (and name) can be ascertained. In production this was not previously available and so having that may reduce the need for surrogates and/or `@Coerce` in those specific circumstances.

**Comment by Mumfrey** [comment]
Ok I've looked into this and here is the skinny:

Having the local variable table is actually what screwed this up, which is kind of ironic. I mean I suspected this given that we know the LVT is present in 1.8.9 and it was breaking in 1.8.9.

As I mentioned above, I only *generate* the LVT when the LVT is not actually present. The compiler-generated LVT actually only contains entries for variables which exist in the source, whereas my generated LVT is actually more like the LVT you'd see after decompiling, in that it contains synthetic entries as well, such as the `Iterator` in question.

The previous fallback behaviour when a variable type could not be matched was to just match any LVT entry in the same slot, in this case local variable slot 9 was occupied by a `String` in the `else` clause and there was *no* other entry for slot 9 in the compiler-generated LVT because the `Iterator` variable was synthetic. Ironically, ignoring the compiled LVT and generating it from scratch yielded the synthetic variable, and caused the correct type to be returned.

So what I will do is instead of failing over to a var in slot but not in range, if a var is not matched I will generate the LVT and lookup the var in the generated table. If this doesn't work I will fall back on the original behaviour.
