### ISSUE TITLE
Support for ForgeGradle's SRG->MCP dependency deobfuscation

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#91]
As of ForgeGradle 2 it has the ability to deobfuscate mod dependencies automatically from SRG to the used MCP mapping set. This basically removes the need for deobfuscated (dev) JARs and allows for different MCP mapping versions to be used throughout the projects.

From what I've noticed when testing this for SpongeForge in general ForgeGradle is able to deobfuscate the mixins properly again, because it doesn't map SRG fields/methods to their class but just replaces all SRG names with their MCP name. However, once trying to run such a dependency at runtime Mixin fails to find the targets for the injections, most likely because the refmap is present, and therefore it is trying to look up using the SRG names instead.

As of https://github.com/MinecraftForge/MinecraftForge/commit/9a737b0c906d2dd7d9a679eb099ff733b8f31453, Forge is also able to remap SRG mods natively to their MCP names. Do you see any chance to make this system work with Mixin? Up to now I was planning to just provide deobfuscated JARs, however it would be easier integratable if we would also have a way of supporting the deobfuscation.

The difficulty here is that simply ignoring the refmap in a deobfuscated environment won't solve the issue - for different MCP mapping versions there can be (theoretically) different names for a SRG name, in that case simply ignoring the refmap would also fail.

**Comment by Mumfrey** [comment]
Wiring for this kind of deobf already exists thanks to the `RemapperChain`, so it's possible that we could hook into however forge is doing this and provide remapping support for refmap entries. I'll add it to my "to look into" list after the current set of features I'm working on are completed. As you say, it's currently workable via just providing a deobf jar, and refmaps can also now be forcibly disabled via a system property.

**Comment by Minecrell** [comment]
I'm probably just too stupid but after looking at the commit, I'm a bit confused because it seems to be mostly refactoring, where did you make changes to remap the refmap entries?
The reason I'm asking is mostly because I was looking if there are any changes that I need to make in SpongeVanilla to make it work there too.

**Comment by Mumfrey** [comment]
It was basically already supported, and the refmap doesn't get processed it just gets disabled. All that was needed was for the remapper to be registered in dev, which I realised was already happening in multiphase so I merged that part in.

To make it work in SV you need to disable the refmap and inject an agent into the remapperchain. The only thing that won't work is obviously if the original references use a different set of mappings, but that's a minor issue which can be addressed later on when there's time.

The bigger issue which is far more pressing in the short run is that SF doesn't work in dev using this setup, so we need to revisit some assumptions. I've only done this because @Zidane wanted remapping to work in dev time for Almura, but the fact that the mixin issues were hiding a much larger problem is going to need attention first.
